### ISSUE TITLE
Setting up dedicated service accounts for xSQLserverSetup

### ISSUE THREAD

**Issue by bodunjo** [PowerShell/xSQLServer#107]
I Can't get to setup a dedicated service accounts using the following naming convention:

$SQLServer = $env:computername
$DomainName = $env:USERDOMAIN

$DBServiceName = "$DomainName\$SQLServer" + "DE"
$AgtServiceName = "$DomainName\$SQLServer" + "AG"
$FTServiceName = "$DomainName\$SQLServer" + "FT"
$RSServiceName = "$DomainName\$SQLServer" + "RS"
$ASServiceName = "$DomainName\$SQLServer" + "AS"
$ISServiceName = "$DomainName\$SQLServer" + "IS"

Is there anyway of doing this?

Thanks in advance

**Comment by nabrond** [comment]
The `Get-Credential` cmdlet allows you to pass in a default user name. The code below should provide you a good starting point to solving this problem.

`"DE","AG","FT","RS","AS","IS" | ForEach-Object { Set-Variable -Name "$($_)ServiceName" -Value (Get-Credential -UserName "$($env:USERDOMAIN)\$($env:ComputerName)$($_)" -Message "Enter service account password") }`

What is happening here? The first part `DE","AG","FT","RS","AS","IS"` creates an array of service account suffixes you wish to use. These suffixes will also be used for saving the credential to the appropriate variable. To make this a bit more dynamic, I chose to use the `Set-Variable` cmdlet to assign the variable. I build a string representation of the variable name, following your naming scheme, that includes the suffix being passed into the loop. The final part is to prompt for the credential using `Get-Credential`. As you can see, we are able to also define the user name shown by default within the control. This cmdlet also requires that a message be displayed as well.

**Comment by bodunjo** [comment]
This worked now. Had to pass in the parameters to the Service accounts, then assign the values of the service account name. Thanks
