### ISSUE TITLE
Request for Enhancements to Resource [xWaitForAvailabilityGroup]

### ISSUE THREAD

**Issue by forensicsguy20012004** [PowerShell/xSQLServer#109]
Hello,

Would it be possible for this resource to take a string/array of objects? Meaning I would like the resource to wait on multiple resources. Why, if I want to build 4 or 5 AGs I would like to just pass all of them in one instead of coding this out 4 or 5 times. So in the example below I would like to be able to pass AG1,AG2,AG3 and so.

I hope this makes sense.

```
 xWaitForAvailabilityGroup waitforAG
 { 
Name = "MyAG" 
RetryIntervalSec = 20 
RetryCount = 6       
DependsOn = (“[xSQLServerEndpoint]" +$Node.Nodename),(“[xSQLServerAlwaysOnService]" +$Node.Nodename) 
 }
```

**Comment by johlju** [comment]
This is not possible since Name is a Key. An array cannot be a Key. 

I learned that the hard way... I coded the functionality for this just to see it bomb in the tests. Well it was a fun hour of coding at least. 😆 

Closing this issue. Thanks!
