### ISSUE TITLE
BREAKING CHANGE: xSQLServerMaxDop cannot be used on more than one instance on the same server

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#117]
I suggest we change xSQLServerMaxDop so it also uses SQLInstanceName as a key to make it possible to use the resource on more than one instance on the same server.

_This is being worked on in PR #64_

**Comment by gigi81** [comment]
Hi @johlju. PR #64 has been merged. I think this can be closed.

**Comment by johlju** [comment]
This has been resolved in PR #64 which has been merged.
