### ISSUE TITLE
Cannot find drive. A drive with the name 'F' does not exist.

### ISSUE THREAD

**Issue by bodunjo** [PowerShell/xSQLServer#118]
I encountered the following issue installing SQL on a clean server. The weird thing is that it fails when i tried to install this for the first time but succeeds at the next attempt on the same server. 
I'm trying to install SQL on the 2 environments at the same time on server A and B

VERBOSE: [LONSQL60B]: LCM:  [ Start  Resource ]  [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]]
VERBOSE: [LONSQL60B]: LCM:  [ Start  Test     ]  [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]]
VERBOSE: [LONSQL60B]:                            [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]] Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\xSQLServer\1.
8.0.0\xPDT.psm1'.
VERBOSE: [LONSQL60B]:                            [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]] Importing function 'GetxPDTVariable'.
VERBOSE: [LONSQL60B]:                            [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]] Importing function 'NetUse'.
VERBOSE: [LONSQL60B]:                            [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]] Importing function 'ResolvePath'.
VERBOSE: [LONSQL60B]:                            [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]] Importing function 'StartWin32Process'.
VERBOSE: [LONSQL60B]:                            [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]] Importing function 'WaitForWin32ProcessEnd'.
Cannot find drive. A drive with the name 'F' does not exist.
![drives](https://cloud.githubusercontent.com/assets/19158282/17999386/fc82d96a-6b70-11e6-8fc8-7828ca41dc3e.PNG)

```
+ CategoryInfo          : ObjectNotFound: (F:) [], CimException
+ FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
+ PSComputerName        : LONSQL60B
```

Cannot bind argument to parameter 'Path' because it is null.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand
    + PSComputerName        : LONSQL60B

Cannot validate argument on parameter 'Path'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,ResolvePath
    + PSComputerName        : LONSQL60B

VERBOSE: [LONSQL60B]:                            [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]] Path:
Cannot bind argument to parameter 'Path' because it is an empty string.
    + CategoryInfo          : InvalidData: (:) [], CimException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,GetSQLVersion
    + PSComputerName        : LONSQL60B

VERBOSE: [LONSQL60B]: LCM:  [ End    Test     ]  [[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]]  in 2.3290 seconds.
The PowerShell DSC resource '[xSQLServerSetup]SqlInstaller::[TestScript]::[TestScript]' with SourceInfo '::265::1::xSqlServerSetup' threw one or more non-terminating errors while running 
the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : LONSQL60B

VERBOSE: [LONSQL60B]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : LONSQL60B

SQL Installer Script:

xSqlServerSetup SqlInstaller
     {
        Dependson = "[Script]DisableFirewall","[xMountImage]OSImage","[xMountImage]SQLImage","[File]DSCResourceFolder","[WindowsFeature]NetFramework35Core","[WindowsFeature]NetFramework45Core","[WindowsFeature]WindowsPowerShellISE","[WindowsFeature]WindowsPowerShell50","[WindowsFeature]ActiveDirectoryModuleForWindowsPowerShell","[WindowsFeature]FailoverClustering","[WindowsFeature]FailoverClusterTools","[WindowsFeature]FailoverClusteringPowerShell","[xADUser]$AGsvcAccount","[xADUser]$DEsvcAccount","[xADUser]$FTSvcAccount","[xADUser]$ISSvcAccount","[xADUser]$ASSvcAccount","[xADUser]$RSSvcAccount"
        InstanceName = $InstanceName 
        Setupcredential = $Setupcredential
        SApwd = $SACredential
        SourcePath = "F:\" 
        SourceFolder = ""
        FEATURES="SQLENGINE,RS,IS,SSMS,ADV_SSMS,SQL" #FullText,SNAC_SDK,Conn,DQ,BC,DQC,Replication,MDS,Tools
        InstallSharedDir = "C:\Program Files"
        InstallSharedWOWDir = "C:\Program Files (x86)"
        InstanceDir = "D:\Program Files\Microsoft SQL Server"
        InstallSQLDataDir = "G:\SQLData"
        SQLUserDBDir = "H:\SQLData"
        SQLUserDBLogDir = "L:\SQLLogs"
        SQLTempDBDir = "V:\SQLTemp\$InstanceName"
        SQLTempDBLogDir = "W:\SQLTempLog\$InstanceName" 
        SQLBackupDir = "G:\SQLData"
        ASDataDir = "C:\Program Files"
        ASLogDir = "C:\Program Files"
        ASBackupDir = "C:\Program Files"
        ASTempDir = "C:\Program Files"
        ASConfigDir = "C:\Program Files"
        UpdateSource = "MU" # set this to windows update, otherwise it will use the default and cause the setup to crash
        UpdateEnabled = 'True'
        SuppressReboot = $False
        ForceReboot = $False
        PsDscRunAsCredential = $cred
        FTSvcAccount = $cred
        ASSvcAccount = $cred
        ASSysAdminAccounts = $cred
        ISSvcAccount = $cred
        RSSvcAccount = $cred
        #PID =
     }

**Comment by bodunjo** [comment]
Or could this possibly be because the drives were mounted using the xstorade DSC resource? I'm beginning to wonder why. I've mounted the drives manually in the past and it worked.

**Comment by johlju** [comment]
xStorage have an issue with the drive not being visible to the system quick enough. Might be the same problem. See issue PowerShell/xStorage#58. Can that be your issue?

**Comment by bodunjo** [comment]
@johlju Thanks again. That was definitely my issue. That fixed it. I added the xWaitForVolume resource for the xmount image resource to depend on.

**Comment by movergan** [comment]
Same issue using DSC in Ansible. Even WaitFor doesn't help. Works only on second run. 
```
- name: Mount ISO
  win_dsc:
    resource_name: MountImage
    Ensure: 'Present'
    ImagePath: "c:\\temp\\{{ mssql_iso_name }}"
    DriveLetter: 'S'
    StorageType: 'ISO'
  tags:
  - install_db

- name: Wait for ISO to be mounted
  win_dsc:
    resource_name: WaitForVolume
    DriveLetter: 'S'
    RetryIntervalSec: 5
    RetryCount: 10

- name: Configure SqlSetup
  win_dsc:
    resource_name: SqlSetup
    ForceReboot: False
    UpdateEnabled: False
    SourcePath: "S:\\"
    InstanceName: "{{ db_settings.instance_name|upper }}"
    Features: "SQLENGINE,AS"
...
```
