### ISSUE TITLE
Where is "NetUse" supposed to come from?  Please support local copy of SQL Setup

### ISSUE THREAD

**Issue by DarwinJS** [PowerShell/xSQLServer#12]
This assumes setup.exe will always be on a remote UNC and so requires credentials, a UNC and path.

However, the function NetUse on line 597 and 601 are not in the module.

In functions where I reference a path I check if it contains "\\" for uncs and ":\" for drive letters.  If it is a drive letter, I don't bother with credentials.

It would be better if the resource supported local copies of the SQL source as well.

**Comment by Arturas-K** [comment]
NetUse is a function that is defined in xPDT.psm1 file in root folder.

And i agree, i'm trying to use this in VirtualBox and NetUse produces errors when my installs are shared from host by built in VBOXSRV file server.

I think good option would be to set $SetupCredential as optional parameter and skip netuse if they are not provided.

**Comment by Arturas-K** [comment]
I think this is now fixed in #19 as it has introduced SourceCredetials parameter if they are omited net use is not performed.

**Comment by NarineM** [comment]
Fixed by #19
