### ISSUE TITLE
Ability to create AvailabilityMode=ASYNC AlwaysOn AG group 

### ISSUE THREAD

**Issue by quizard** [PowerShell/xSQLServer#124]
Not seeing an option to specify synchronization mode while creating the AG group. Am I missing something or is this not implemented yet? Thanks!

**Comment by aultt** [comment]
Correct currently the resource is taking first two nodes and they will account for Synchronous Automatic Failover, Any additional will be Asynchronous

**Comment by johlju** [comment]
@quizard I do have a resource available in my repo where you can say if the node should be synch or asynch. But that resource is in conflict with the current resource (`xSQLAOGroupEnsure` ) in this repo so I can't just submit it here as is. But do please check it out and see if it helps anyway. Let me know if I should submit it to this PR, or implement the functionality it has. And please let me know if it did not solve anything for you either, so we know that too :)
See resource `xSQLServerAlwaysOnAvailabilityGroup` in my [repo](https://github.com/johlju/xSqlServerAlwaysOn)

**Comment by johlju** [comment]
The resource xSQLAOGroupEnsure and xSQLAOGroupJoin has been deprecated. Closing this issue since those has been replaced by xSQLServerAlwaysOnAvailabilityGroup and xSQLServerAlwaysOnAvailabilityGroupReplica. If there is a problem with the new resource, please submit a new issue.
Thank you!
