### ISSUE TITLE
BREAKING CHANGE: Using Start-Process instead of StartWin32Process

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#126]
The submitted PR #123 changes the way SQL setup is launched. I thought this is such a major design change so it warrants a breaking change label. This is so a discussion around this change can be made.

**Comment by johlju** [comment]
@gigi81 @Zuldan Are we in agreement that this PR resolves issue #93?

**Comment by johlju** [comment]
What happens is the process hangs and never completes with Start-Process? Shouldn't `Start-Job` and `Wait-Job` be used, or something similar, so it can timeout and throw an error if the process doesn't complete. The timeout value could be a parameter set by the configuration.

**Comment by Zuldan** [comment]
@johlju maybe we could ask @kwirkykat to find out internally why StartWin32Process was used instead of using Start-Process. There is a lot of code in StartWin32Process so there would have had to be some good reason unless the helper function was initially created for something else.

With your solution...If a timeout is going to be used the maybe a timeout property should be exposed in the resource. The installation of SQL server varies greatly from server to server.

**Comment by kwirkykat** [comment]
@Zuldan @johlju I asked the team and got no response. I don't think anyone here wrote this module. 

StartWin32Process seems to wait for the process though whereas Start-Process does not.

**Comment by gigi81** [comment]
Hi,
@kwirkykat Start-Process will be used with the -Wait flag, so it  will definitely waits for the process to complete.

@johlju about the timeout, I'm not sure is the correct way to go. If the sql setup is started it rather complete successfully or fails, but it shouldn't just hang. Killing the process while it's running might have more undesired effects then benefits in my opinion.

I also agree with @johlju that if the xPDT module is not used by any other resource it should be removed.

Considering the above, I will update the PR #123.

As a last observation, I don't completely agree on the fact that this should be marked as a breaking change as it's changing the internals of how the dsc resource works, and it's not affecting any end user interaction.

**Comment by johlju** [comment]
I agree with that killing the process would not be beneficial when debugging what's wrong and as you say, might be hard to recover from. 
With this I can agree that we can skip the timeout and if there is an issue later on which a timeout might solve then that can be implemented at that time. 

And regarding to the breaking change, good that we discuss this. I saw it first as a breaking change because of this text in the CONTRIBUTION.md; "Fundamentally changing an existing functionality of a resource". And the reason for that I thought of it as a breaking change was because it change (removed) so much code, and the way it started the process is different which needed to be discussed, but it does not changing the functionality of the resource, SQL gets installed. :)
When I read it back now, that line could be interpreted in different ways. So I can go either way. 
But I think it wouldn't hurt for the release notes to say something like `"BREAKING CHANGE: Reworked how SQL setup process is started"`. Then the users know something big happened :) 

But as I say. I can go either way.

**Comment by nabrond** [comment]
I think this will break compatibility with WMF 4.0 with respect to the SetupCredential parameter. WMF 5 added support for PsDscRunAsCredential, globally allowing resources to be executed under a given credential. The StartWin32Process function was part of the xPDT module to provide this same functionality to older versions of PowerShell. See this [article](https://blogs.technet.microsoft.com/privatecloud/2015/01/30/xpdt-credentials-credssp-and-execution/) for more information.

**Comment by gigi81** [comment]
Hi @nabrond 
I like your theory. The only problem is that, from what I can see, the SetupCredential parameter is actually not used to start the setup process. This would probably require a separate issue by itself. Please double check the code here in case I'm missing something:
https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1

**Comment by nabrond** [comment]
You are correct @gigi81; will need to log a separate issue. However, once that issue is resolved, it will introduce the compatibility issue I described here. However, once that issue is resolved, I think we'll be back to my point of WMF 4 compatibility.

**Comment by Zuldan** [comment]
StartWin32Process should be removed. It add a lot of overhead that is really not needed.

**Comment by gigi81** [comment]
I agree with @Zuldan. I think it should use Start-Process and the documentation around the SetupCredential parameter should be fixed. Nobody never even noticed the setup was not run with the SetupCredentials, so I think it's not really a requirement.
In any case, as @nabrond correctly mentioned, If anyone needs to run the setup with some particular credentials, they can use PsDscRunAsCredential using WMF5.
I'm happy to modify PR #123 accordingly if some maintainer agrees and will be ok to merge the changes.
