### ISSUE TITLE
Why is xSqlServerPowerPlan tied to SQL?

### ISSUE THREAD

**Issue by afscrome** [PowerShell/xSQLServer#129]
The `xSQLServerPowerPlan` actually has no dependency on SQL Server.  Can it just be renamed to `xPowerPlan` ?  Setting the power plan has many uses cases out side of SQL Server.

**Comment by Zuldan** [comment]
@afscrome I agree it should be renamed and the resource should also be moved to xComputerManagement.

**Comment by johlju** [comment]
I also agree that this should be moved to xComputerManagement. Does anyone want to run with this and raise an issue in xComputerManagement and then move it there (but renamed as @afscrome suggest)?

**Comment by johlju** [comment]
I have initiated the move by sending in a new and improved resource to the xComputerManagement repo. See the pull request PowerShell/xComputerManagement#47.

When the PR is merged, I will continue the process of removing the xSQLServerPowerPlan from this repo.

**Comment by johlju** [comment]
The PR PowerShell/xComputerManagement#47 was merged. So now we can finally remove xSQLServerPowerPlan. 😃
