### ISSUE TITLE
xSQLServerSetup should be able to execute setup process using SetupCredential or built-in PsDscRunAsCredential

### ISSUE THREAD

**Issue by nabrond** [PowerShell/xSQLServer#139]
The xSQLServerSetup resource includes a parameter `$SetupCredential` to allow the setup process to be executed as a specific user. However, when reviewing the code, it appears this credential is never passed to the function which starts the setup process. 

The code:
`$Process = StartWin32Process -Path $Path -Arguments $Arguments` 
should be 
`$Process = StartWin32Process -Path $Path -Arguments $Arguments -Credential $SetupCredential`

**Comment by Zuldan** [comment]
If SetupCredential was never used (because it's not in the code) and no one has complained then it's probably not needed. If this was added in and we replace StartWin32Process with Start-Process ( #126  ) then this would break compatiblity with WMF4.

**Comment by nabrond** [comment]
My guess would be that since `$SetupCredential` is a required parameter, an assumption was made by users that it was required for the setup process to actually execute.

**Comment by johlju** [comment]
I can only see that the `$SetupCredential` is used to set the _first_ user for the `SQLSysAdminAccount` and `ASSysAdminAccounts` command-line parameter. So for those not using `SQLSysAdminAccounts` parameter or `ASSysAdminAccounts` parameter in their config file, removing the `$SetupCredential` will be a breaking change.

Line 758:
```
$Arguments += " /SQLSysAdminAccounts=`"" + $SetupCredential.UserName + "`"" 
```

Line 773:
```
$Arguments += " /ASSysAdminAccounts=`"" + $SetupCredential.UserName + "`""
```

**Comment by johlju** [comment]
I would like to suggest the following:
- That we fix issue #139 with a combination of the changes in PR #123.
- That we make sure that `SetupCredential` is not mandatory, so it could be left out so that the built-in `PsDscRunAsCredential` can be used.
- That when using `PsDscRunAsCredential` it is still possible to use `SourceCredential` to copy media to the target node.

**Comment by nabrond** [comment]
This sounds good to me @johlju. However, I still have one question; as a project, is there value in maintaining compatibility with WMF 4.0? The automatic parameter ````PsDscRunAsCredential```` is only available beginning with WMF 5.0.

**Comment by johlju** [comment]
I wouldn't mind moving to support WMF 5.0 and having WMF 4.0 "work-if-it-works". But I think this is a bigger question. I have not seen anything mentioned about it, so I asked the question to the community https://github.com/PowerShell/DscResources/issues/237

**Comment by johlju** [comment]
After discussion at the community call it was concluded that we are allowed to move away from WMF 4.0.

**Comment by johlju** [comment]
When the above is fixed then issue #379 should also be tested and make to work if it is possible.

**Comment by yardbirdsax** [comment]
FYI I actually changed this in #363 in order to fix #345 , but only for certain clustered installations, so as to minimize impact.

**Comment by johlju** [comment]
Updated https://github.com/PowerShell/xSQLServer/issues/139#issuecomment-270136906 to make sure issue #405 is fixed also.

**Comment by johlju** [comment]
Renamed this issue to be more clear what the goal is: "xSQLServerSetup should be able to execute setup process using SetupCredential or built-in PsDscRunAsCredential"

**Comment by johlju** [comment]
I have started to work on this issue finally. Currently I got the resource working with PsDscRunAsCredential and when the resource is running as SYSTEM (the old behavior).

Trying to keep PowerShell 4.0 support (using the now non-mandatory parameter SetupCredential). I tried to use `Start-Process` with `-Credential $SetupCredential`, but that failed with an error.

```
PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Set-TargetResource functionality with error message: This command cannot be run due to the error: The requested operation requires elevation.
```
If someone knows another way to start a process elevated and impersonating a different user, please let me know. 😄 

I will try to use the old `StartWin32Process` tomorrow, see if that works to pass in the credential object of `SetupCredential` when it is set. But I was hoping to be able to remove that code entirely. 😞

**Comment by nabrond** [comment]
With Start-Process, add "-Verb RunAs" to launch an elevated process.

---
Brandon Adams (Mobile)

**Comment by johlju** [comment]
I tried that, `-Verb` is not allowed together with `-Credential`. So I get it elevated, but no impersonation :/

I also tried to start 'PowerShell.exe'  using `Start-Proces` with credentials and use `-Command` to start 'setup.exe'. But UAC kicks in and prompts when running interactively. And fails with an error code (did not save the error code) when LCM tries to run it. Even if we loose most of the control over the process I thought it was worth a shot. But didn't work.

**Comment by johlju** [comment]
I wonder if it possible with WMI? Win32_Process class or something. 🤔

Previous comment I forgot to write that the try was to run `Start-Process` in two steps, first with `-Credential` and then another `Start-Process` With `-Verb` in the `-Command` of 'PowerShell.exe'. 
It was one of the first examples I found when doing a quick search on the webs. But reading further it seems UAC is always there and disturbs.

**Comment by johlju** [comment]
Seems that @mbreakey3 did not find a better way either than using "PInvoke" for MsiPackage in PSDscResource, so I guess there is no better way to impersonate a user. 😄 

https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/MSFT_MsiPackage/MSFT_MsiPackage.psm1#L1155

So I think we try the same code as from PSDscResource to get PowerShell 4.0 support. The alternative is to remove 4.0 that support entirely. I created an issue for that so the community can discuss it.

**Comment by johlju** [comment]
In PR #578 we are moving away from WMF 4.0. So the SetupCredential parameter is removed in that same PR.
