### ISSUE TITLE
Use of Win32_Product WMI class causes msiinstaller to reconfigure all installed programs.

### ISSUE THREAD

**Issue by keyrage** [PowerShell/xSQLServer#15]
The two setup resources uses the Win32_Product WMI class which is not recommended for use because it causes the msiinstaller to reconfigure every installed application registered. This is very slow and risks issues with other applications.

https://support.microsoft.com/en-nz/kb/974524

The use of this class should be replaced with an alternative class.

**Comment by luigilink** [comment]
Win32_Product still presents in:
MSFT_xSQLServerFailoverClusterSetup\MSFT_xSQLServerFailoverClusterSetup.psm1

**Comment by johlju** [comment]
That resource is deprecated. It will be deleted when the cluster functionality has been verified working in xSQLServerSetup. 
So no more work should be done to this resource. I'm closing this issue since it is fixed in all others. 

Thanks for catching this @luigilink
