### ISSUE TITLE
xSQLAOGroupEnsure - Design is wrong

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xSQLServer#150]
xSQLAOGroupEnsure forces you to have an Availability Group Listener. An Availability Group does not require you to use one. Microsoft's intent was for Availability Groups to be used with or without a Listener. The xSQLAOGroupEnsure is changing that intent by forcing you to use a listener. 

In our environment, we need to setup Availability Groups without listeners (as we just need replication of dev environments etc), listeners put you in a world of pain if you don't have access to Active Directory and you're in a very large organization.

**xSQLAOGroupEnsure** should only create Availability Groups
**xSQLServerAvailabilityGroupListener** should only create Availability Groups Listeners

**Comment by johlju** [comment]
I have created resources here https://github.com/johlju/xSqlServerAlwaysOn which I was suppose to PR in to this module. But some are in conflict with the present resource in this module. But my intent was that each resource should be independent. 
Would they work for what you are after? If so I can look at PR the rest of them in here.

**Comment by Zuldan** [comment]
@johlju I'm so sorry for not replying to this sooner. I must have missed the email alert. I only came across it again by browsing the issues list. 

I totally agree with you. Each resource should be independent and not overlap with each other. 

PLEASE please do a PR ;-) xSQLAOGroupEnsure a terrible implementation of AOAG and should be removed all together. We need your resources!

While you are fixing the conflicts could you also fix a small typo and rename xSQLServerAlwaysOnAvailabilityGroupListner to xSQLServerAlwaysOnAvailabilityGroupListener.

If I can help in anyway please let me know. Happy to test.

**Comment by johlju** [comment]
@Zuldan no worries :)

I would like to see them in here too so more people can use them. I can start by submitting a issue for each resource I got in my repo so others can comment on them before PR them in. It will be some undertaking writing proper unit tests for them. But I happy to do that work to get them in here. 

Regarding the typo in resource name I will submit a new issue for it so that can be fixed.

**Comment by johlju** [comment]
Ah, it is misspelled in my repo, right! xSQLServerAlwaysOnAvailabilityGroupListener is actually already in this module. The review pointed out that 'listener' was misspelled so I fixed it here. 😄 
I will focus on getting the rest of the resources here, instead than fixing that I think. If you really want me to fix that in my repo, then please submit an issue for it there. :)

**Comment by randomnote1** [comment]
@johlju , please feel free to assign this to me. I'm beginning work on this.

**Comment by johlju** [comment]
@randomnote1 Consider yourself assigned 😄
