### ISSUE TITLE
xSQLServerRole defaults to Ensure = Absent

### ISSUE THREAD

**Issue by magnustomte** [PowerShell/xSQLServer#151]
xSQLServerRole defaults to Ensure = Absent because no default value is set in the resource. E.g. xSQLServerLogin is set to `[ValidateSet('Present', 'Absent')] [System.String] $Ensure = 'Present',` while xSQLServerRole is set to `[ValidateSet("Present","Absent")] [System.String] $Ensure,` causing it to default to Absent since the check in the resource is `if ($Ensure -eq "Present"){}...else{}`.

Is this by design? I would expect it to default to Present when not specified explicitly.

**Comment by johlju** [comment]
I think that default should be 'Present' if parameter `Ensure` is not mandatory. This as a bug that sneaked thru :)

**Comment by luigilink** [comment]
Fix suggested in PR #154
