### ISSUE TITLE
Request for Advice on Adding Functionality for new Feature support

### ISSUE THREAD

**Issue by joshan1120** [PowerShell/xSQLServer#159]
I am going to try to add the ability to add more SQL Features during the installation process as they are required for my installation requirements.

These are the features I require:
SqlInstallFeatures = 'SQLENGINE,FULLTEXT,SSMS,ADV_SSMS,IS,CONN,BC'

It appears that 'CONN,BC ' are not support in the module as they throw errors.

While my skillset is still at the novice end, I am willing to try and add this into the module. Is anyone able to give me a little guidance on how to start?

Thanks!!

**Comment by joshan1120** [comment]
Hmm, I think I see why this was not done. The other features seem to install a service and you can query the service for verification. But CONN,BC do not install a service...

**Comment by johlju** [comment]
Maybe you can see if it is installed thru registry. 
Look at the code and search for `#test if Replication sub component is configured for this instance`. The code below it verify if the replication is installed. 
Maybe the CONN and BC is registered in the registry the same way when installed?

**Comment by joshan1120** [comment]
thanks, I will give it a try :)

**Comment by joshan1120** [comment]
not sure exactly how this all works as I am new here :)

But I just pushed up branch "FIX_#159"

This contains the code to correct this issue.

**Comment by joshan1120** [comment]
just created pull request as I think that is what i was supposed to do :) Let me know.

**Comment by joshan1120** [comment]
Hmm, just realized I kind of made it only for sql2014...

Guessing I need to add the following to make it work?

$FeaturesVersion = $SqlVersion + "0"

And plug that in like this? Let me know and I can update and do another pull request.

Write-Verbose "Detecting Client Connectivity Tools feature"
		Write-Verbose "Reading registry key HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full"
		$isCONNInstalled = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$FeaturesVersion\Tools\Setup\Client_Components_Full").FeatureList
		Write-Verbose "SQL_Client_Connectivity_Tools = $isCONNInstalled"
		if ($isCONNInstalled -like '*Connectivity_FNS=3*') { }
		 {
			Write-Verbose "Client Connectivity Tools feature detected"
			$Features += "CONN,"

**Comment by joshan1120** [comment]
test was successful. I have added the following pull request
**Add support for SQL Features "CONN" & "BC" #162**

**Comment by joshan1120** [comment]
Add support for SQL Features "CONN" & "BC" #163

**Comment by johlju** [comment]
Never thought about this. Might be something we should add to the specific guidelines.

But I would guess that you need to make it work for all still supported (extended also?) SQL Server versions that contains the functionality the resource targets. That would be SQL Server 2008 SP4 if we also target extended support.

I will review your PR as soon as I have an opportunity (unless someone else beat me to it).
