### ISSUE TITLE
Rename helper functions *-SqlServerRole to *-SqlServerRoleMember

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#165]
The helper functions `Add-SqlServerRole`, `Remove-SqlServerRole` and `Confirm-SqlServerRole` should be renamed since they handles members in a server role, not the actual server role.

The new names would preferably be `Add-SqlServerRoleMember`, `Remove-SqlServerRoleMember` and `Confirm-SqlServerRoleMember`

**Comment by johlju** [comment]
@kwirkykat I think you could add 'easyfix' tag to this too. This issue could be good to take on for someone new to contributing. Would be awesome to see some new faces in this repo  :smile:

**Comment by luigilink** [comment]
Yes new faces it's a good idea 😸

**Comment by johlju** [comment]
This is being worked on in PR #154

**Comment by kwirkykat** [comment]
Looks like this was fixed in #154
