### ISSUE TITLE
Currently the PR #74 is in conflict with the current xSQLServerRole

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#166]
I think we need to do some actions to resolve this to make PR #74 able to go thru the review process and be merged.

My findings is that 
- The proposed resource MSFT_xSQLServerRoleMembership in PR #74 
  - Is duplicate to the presently merged MSFT_xSQLServerRole (almost, see last bullet point).
  - Creates a new server role. The presently merged MSFT_xSQLServerRole does not. 
- The presently merged resource MSFT_xSQLServerRole
  - Is hard-coded to use built-in server roles only. The MSFT_xSQLServerRoleMembership resource in PR #74 can handle any server role.

**So the actions I see we need to take:**
1. The presently merged MSFT_xSQLServerRole needs to be renamed to MSFT_xSQLServerRoleMember **This will be a breaking change.**
2. The presently merged MSFT_xSQLServerRole must be able to use any name of server role, not hard-coded to just the built-in server roles. **This will be a breaking change.**
3. The proposed resource MSFT_xSQLServerRoleMembership in PR #74 should be removed from the PR.
4. (optional) PR #74 should add a resource, or change the proposed resource MSFT_xSQLServerRole, to also add the permissions to the server role that it adds. _I have not given a thought which is the best solution. Just saw that it was lacking that functionality._

@luigilink Do you have any comments on this?

**Comment by johlju** [comment]
One take away from this is that we need to be more careful how resources are named before we allow them to merge. 
We learn by our mistakes :smile:

**Comment by kwirkykat** [comment]
@johlju 
Instead of splitting into two resources, what about just adding a parameter called Members to xSQLServerRole? (plus fixing the resource to do more than built-in roles of course)
It could be a list of the login names to include in that role.
Or you could do MembersToInclude/MembersToExclude as in the Group resource in [PSDscResources](https://github.com/powershell/psDSCResources).

**Comment by johlju** [comment]
@kwirkykat That could work. Great idea. Did not think of merging them. I was stuck in thinking "one task (change), one resource".
@kwirkykat looking at the schema for [Group](https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/MSFT_GroupResource/MSFT_GroupResource.schema.mof) could you tell me why it is `Members` (plural) and not `Member` (singular)? Thought we were going for singular in PowerShell parameters/variables?

If we keep the name, then the current xSQLServerRole will also need to add the functionality to add and remove new server roles. Which the proposed xSQLServerRole resources does in #74. 
I think `MembersToInclude` and `MembersToExclude` would be the closet to the current functionality, optionally also add `Members`, to match the functionality in PSDscResources, which would replace all the memberships in the server role. 

So a new action list could be.

1. Merge the functionality to add and remove server roles from the proposed xSQLServerRole in PR #74 to the currently merged xSQLServerRole. The current `Name` parameter will instead pass the server role name (it previously passed the login name). **This will be a breaking change.**
2. The currently merged xSQLServerRole must be able to use any name of server role, not hard-coded to just the built-in server roles. _I think this will be automatically solved with step 1._ **This will be a breaking change.**
3. Add a parameters `MembersToInclude` and `MembersToExclude` to the currently merged xSQLServerRole. This will contain all the logins that will be added to the server role or removed from the server role.
4. (Optionally) Add a parameter `Members` which would replace all the memberships in the server role.

**Comment by johlju** [comment]
When this is fixed it will also resolve issue #30
