### ISSUE TITLE
xSQLServerAlwaysOnService: Should restart the SQL Agent if it was previously running.

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/xSQLServer#187]
The cmdlets Disable-SqlAlwaysOn and Enable-SqlAlwaysOn do not automatically restart the agent service if it was previously running. The xSQLServerAlwaysOnService should check the SQL Server and Agent services to determine what states they were in prior to  executing the cmdlets and return them to the same state after enabling/disabling Always On.

**Comment by johlju** [comment]
That would be a good improvement. Then you don't need to use the Service resource as a workaround to start it (if you know you want it started).

```
Service SQLServerServiceStarted
{
    Name = "MSSQLSERVER"
    State = "Running"

    PsDscRunAsCredential = $SqlInstallCredential

    DependsOn = "[xSQLServerAlwaysOnService]SQLConfigureAlwaysOnService"
}

Service SQLServerAgentServiceStarted
{
    Name = "SQLSERVERAGENT"
    State = "Running"

    PsDscRunAsCredential = $SqlInstallCredential

    DependsOn = "[Service]SQLServerServiceStarted"
}
```

In the xSQLServerConfiguration there are code for restarting SQL Server and SQL Server Agent both for a single instance and for a cluster instance. Maybe that function could be moved out as a helper function and used in this resource as well.

https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerConfiguration/MSFT_xSQLServerConfiguration.psm1?#L239
