### ISSUE TITLE
FeedBack - Split ReadMe and ChangeLog in two separate files

### ISSUE THREAD

**Issue by luigilink** [PowerShell/xSQLServer#189]
What do you think of the splitting of readme and changelog in two .md files ?
We can also put the detail of resources in a new file ?

Suggested PR #190

**Comment by johlju** [comment]
Awesome suggestion! I'm all for it! :smile:

@kwirkykat would this work for your release management?

**Comment by johlju** [comment]
@luigilink Regarding detail of the resource. Is it how SharePointDsc does it? if so we have a separate issue #182 for that already :D

**Comment by johlju** [comment]
@kwirkykat or @mbreakey3 Is it okay that we split this into to separate files like SharePointDsc? There won't be any problems when you release?

**Comment by kwirkykat** [comment]
@johlju No problems splitting out the change log
