### ISSUE TITLE
xSQLAOGroupEnsure: For named instances, replicas require full instance name

### ISSUE THREAD

**Issue by detailedschematic** [PowerShell/xSQLServer#193]
With the code in xSQLAOGroupEnsure's SET method, I noticed that the creation of Availability Groups (AGs) fail when dealing with named SQL Server instances.

The problem is the value supplied to the replica object's constructor. Currently, it's the cluster node's name. It should probably be the full instance name, in the format of: nodename\instancename.

In pseudo-code, the logic would look like this:
```
if $SQLInstanceName == to 'MSSQLSERVER'
then $replicaName = $SQLInstanceName
else
$replicaName = "$node\$SQLInstanceName"
```

We would then supply $replicaName to the replica's constructor. I made this patch in my setup using named instances, and the AG was then able to form afterwards. 

I'm refraining from submitting a PR since I'm waiting on my company to clarify their stance on non-trivial open source contributions. But I still wanted to raise this issue in case anyone else is running into the same problem.

**Comment by randomnote1** [comment]
@johlju , please assign this to me.

**Comment by johlju** [comment]
@randomnote1 Can not set you as assignee unless you are the author of the issue (or a maintainer) :/ But I did set the label 'In progress' so we can see someone is working on it.

**Comment by johlju** [comment]
@randomnote1 So consider yourself assigned 😉
