### ISSUE TITLE
Add template for New Issue and New Pull Request

### ISSUE THREAD

**Issue by luigilink** [PowerShell/xSQLServer#197]
Add template for Issue and Pull Request
Example for Issue Template:
**Details of the scenario you try and problem that is occurring:**

**The DSC configuration that is using the resource:**

**Version of the Operating System and PowerShell the DSC Target Node is running:**

**Version of the DSC module you're using:**

PR #191

**Comment by johlju** [comment]
I like this idea with templates. Could you explain more how you see both templates being used?

If I want to file an issue, how would I do that? Would I browse to the template and copy it, and then click on 'New issue' and paste the template in?

**Comment by luigilink** [comment]
No it's automatic when you click on new issue, you'll have exactly the content of ISSUE_TEMPLATE.md
and the same thing with a new pull request.
Try it on SharepointDsc, you will see 😸

**Comment by johlju** [comment]
@luigilink Tested it on SharePointDsc. That is awesome! Was hoping it would be automatic, did not know it could be. 😄 

I will review this as soon as possible so we can get started with this,

Awesome work!
