### ISSUE TITLE
xSQLServer: Localization should change to align with HQRM modules

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#205]
Today localization strings in one place. We should change this so that the localization is in each of the resources. This would align with the HQRM modules.

**Module example:** 
Resource: [MSFT_WindowsOptionalFeature](https://github.com/PowerShell/PSDscResources/tree/dev/DscResources/MSFT_WindowsOptionalFeature)
Resource strings: [MSFT_WindowsOptionalFeature.strings.psd1](https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/MSFT_WindowsOptionalFeature/en-US)

It uses a another approach to get the localization strings`and has a helper function under the DscResources tree.
https://github.com/PowerShell/PSDscResources/blob/dev/DscResources/CommonResourceHelper.psm1

And getting the localization strings is done like this.
```
Write-Verbose -Message ($script:localizedData.PowerPlanIsActive -f $Name)

throw ($script:localizedData.PowerPlanNotFound -f $Name)
```

With this approach we will also resolve a lot of the PSSA rule warnings during testing in AppVeyor (see issue #203) when `Write-Verbose` is not used in the Get-/Set-/Test-methods. If we use this approach we don't have to suppress those rules and we are closer to HQRM.

**Comment by johlju** [comment]
Status of localization (according to new approach) for each resource

- [ ] MSFT_xSQLAlias
- [ ] MSFT_xSQLAOGroupEnsure
- [ ] MSFT_xSQLAOGroupJoin
- [ ] MSFT_xSQLDatabaseRecoveryModel
- [ ] MSFT_xSQLServerAlwaysOnService
- [ ] MSFT_xSQLServerAvailabilityGroupListener
- [ ] MSFT_xSQLServerConfiguration
- [ ] MSFT_xSQLServerDatabase
- [ ] MSFT_xSQLServerDatabaseOwner
- [ ] MSFT_xSQLServerDatabasePermissions
- [ ] MSFT_xSQLServerDatabaseRole
- [ ] MSFT_xSQLServerEndpoint
- [ ] MSFT_xSQLServerEndpointPermission
- [ ] MSFT_xSQLServerEndpointState
- [ ] MSFT_xSQLServerFailoverClusterSetup
- [ ] MSFT_xSQLServerFirewall
- [ ] MSFT_xSQLServerLogin
- [ ] MSFT_xSQLServerMaxDop
- [ ] MSFT_xSQLServerMemory
- [ ] MSFT_xSQLServerNetwork
- [ ] MSFT_xSQLServerPermission
- [ ] MSFT_xSQLServerReplication
- [ ] MSFT_xSQLServerRole
- [ ] MSFT_xSQLServerRSConfig
- [ ] MSFT_xSQLServerRSSecureConnectionLevel
- [ ] MSFT_xSQLServerScript
- [ ] MSFT_xSQLServerSetup
- [ ] MSFT_xWaitForAvailabilityGroup

**Comment by johlju** [comment]
I created a issue for each resource. I'm will start working on xSQLServerSetup (issue #601) so we get the prerequisites for HQRM localization. Then it's will go faster to do the rest I think.

I close this issue now when there is an issue per resource for this.

**Comment by randomnote1** [comment]
@johlju, I want to make sure I'm following correctly. Are we moving all of the localization from the module root directory to each individual resource? And then each individual resource will get its own set of localization directories? Is the following directory tree correct?

- xSQLServer
  - < version >
    - DSCResources
      - < Resource >
        - en-US
        - < other language >
    - en-US

**Comment by johlju** [comment]
Yes you are correct. That structure is correct. 
The root en-US is just for backward compatibility now. 

I tried to explain that I CONTRiBUTION.md but maybe need to be clarified?

I see that xSQLServerHelper also will move to it's own folder under DSCResources later so it's localization folder follow the same structure. But think that we do that when all other resources are localized. I needed to get xSQLServerHelper localized to be able to close two issues. That's why I localized it at its current location. 
And for the current localized error messages to work (with the same logic) I had to move them into xSQLServerHelper localized strings file.

**Comment by randomnote1** [comment]
Thanks! I'll start working on getting the xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership module updated. Your work in xSQLServerSetup should be a good example.

**Comment by johlju** [comment]
Also there are new helper functions to throw errors (see CONTRIBUTING.md). And for verbose and warning message we should use Write-Verbose and Write-Warning. That will get the PSSA rule warnings about Write-Verbose to go away.

**Comment by johlju** [comment]
Awesome!
