### ISSUE TITLE
The Win32_Product WMI class should not be used

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#207]
This is to see if we can change to not use this class according to the issue submitted in DscResources.

See referenced articles in the issue over at PowerShell/DscResources#108

**Comment by luigilink** [comment]
Status of Win32_Product WMI removed from resource

- [ ] MSFT_xSQLAlias => PR #147 
- [ ] MSFT_xSQLServerConfiguration
- [ ] MSFT_xSQLServerFailoverClusterSetup
- [ ] MSFT_xSQLServerRSConfig
- [ ] MSFT_xSQLServerRSSecureConnectionLevel
- [ ] MSFT_xSQLServerSetup

**Comment by johlju** [comment]
Only resource left that is using Win32_Product is MSFT_xSQLServerFailoverClusterSetup, and that resource is deprecated. It will be removed in the future, so no need to fix Win32_Product for that resource. Closing this issue.
