### ISSUE TITLE
BREAKING CHANGE: xSQLServerFailoverClusterSetup: Should be merged to xSQLServerSetup if possible

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#227]
**Details of the scenario you try and problem that is occurring:**
I think xSQLServerFailoverClusterSetup should be merged to xSQLServerSetup since they both install SQL Server with just different parameters and parameter values. 

In xSQLServerFailoverClusterSetup there are support for `/ACTION=PrepareFailoverCluster` and `/ACTION=CompleteFailoverCluster`. But there are no support for `/ACTION=InstallFailoverCluster`. Don't know the reason for supporting `PrepareFailoverCluster` and `CompleteFailoverCluster`, but not `InstallFailoverCluster`. When resource is merged into xSQLServerSetup at the same time we should look into supporting `/ACTION=InstallFailoverCluster`.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Any

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by nabrond** [comment]
I think there is enough overlap between these resources to warrant merging them. After living in ````xSQLServerFailoverClusterSetup```` for a bit, I think the key parts to migrate are for clustered disk and clustered network resource detection. I would like to see this combined resource support the traditional cluster installation pattern of "InstallFailoverCluster / Add Node" as well as including additional disk resources during installation.

@johlju, I know you were doing some major work in the xSQLServerSetup resource. When those changes have been merged, I would be willing to bring over the updated cluster code that I have been working on for ````xSQLServerFailoverClusterSetup```` as well as the additional parameters required when building a cluster.

**Comment by forensicsguy20012004** [comment]
@johlju and @nabrond .... let me know what I can do to help out with the cluster stuff. I got some code over to you guys hoping that can help out as you re-work. I now have a test multi-subnet cluster...so if there is something you guys need me to try...I can now do that.

**Comment by johlju** [comment]
@nabrond Would be awesome if you want to take on this! :smile: 
I have already merged all the changes I made to xSQLServerSetup. There are still a lot of tests to write which we will have to try to get around to eventually (for testing all parameters), but all that is left I have submitted in a separate issue so that it is documented. Also a bunch of bugs I find which should be fixed. 
But I think nothing of that is a stopper for you to start working on merging the resources. We should try to limit the changes to xSQLServerSetup to just critical while you are working on the merge, so the conflicts don't stack up.

You mention Clustered disk and Clustered network detection. Is that SQL specific resources? Or could the module [xFailoverClustering](https://github.com/PowerShell/xFailOverCluster) be used for those instead? Only if possible. My thinking is that we should not try to invent the wheel again (or invent them over at that module instead) if there are not SQL specific. :)

@forensicsguy20012004 Do you have a repo with the code in it? If so link it here so @nabrond could look at it. If not, you could create a Gist for the code https://gist.github.com/

**Comment by johlju** [comment]
@nabrond I'm assigning this one to you. If you need any help, or anything changes, let us know. 😄

**Comment by nabrond** [comment]
@johlju The clustered disk and network detection is a task specific to SQL Server setup. When installing a clustered SQL Server instance, you are required to supply the file system paths as well as the clustered disk resource names associated with those paths. In the xSQLServerFailoverClusterSetup resource, there is logic to take these paths and automatically determine the disk resources. Similar logic and process exists for the cluster networks. Both of these require some updates to use CIM (#203) as well as add support for multi-subnet clusters (#157).

**Comment by Zuldan** [comment]
@nabrond I'm not sure merging xSQLServerFailoverClusterSetup With xSQLServerSetup is a good idea. I'm sure there are some mandatory property's in xSQLServerFailoverClusterSetup, You wouldn't be able to make them mandatory in xSQLServerSetup since it would be used for non-Clustered setups as well. What are your thoughts?

@nabrond, I agree with @johlju, xFailoverClustering should be able to setup all the clustering. When you said "In the xSQLServerFailoverClusterSetup resource, there is logic to take these paths and automatically determine the disk resources", could you give an example of what this does?

On another note, if it's decided that xSQLServerFailoverClusteringSetup is still required then I think it should be renamed to xSQLServerFailoverClusteringInstanceSetup as it only used for a Failover Clustered **Instance** and not an Failover Clustered Availability Group.

**Comment by nabrond** [comment]
@Zuldan Good thought! I think enforcing the additional mandatory parameter requirements can be implemented in code or potentially using Parameter Sets (still investigating this approach). 

When installing SQL Server, clustered or not, you must specify all the usual paths, data directory, log directory, backup directory, etc. However, when installing a clustered instance, you additionally need to include a listing of cluster disk resources on which those directories exist. Consider the following structure:

Parameter | Path/Value | Disk Resource
--- | --- | ---
$SQLUserDBDir | G:\\SQLServer\\Data | CLU01_SQL_Data
$SQLUserDBLogDir | H:\\SQLServer\\Logs | CLU01_SQL_Logs
$SQLBackupDir | K:\\SQLServer\\Backups | CLU01_SQL_Backups

In this scenario, the xFailoverCluster resource would be responsible for ensuring the disk resources exist within the failover cluster and the xSQLServerSetup resource is responsible for mapping a path to the associated disk resource. This is to streamline the configuration process for the end user. The table above results in the following parameters being passed to the SQL Server setup program:

````/SQLUSERDBDIR="G:\SQLServer\Data" /SQLUSERDBLOGDIR="H:\SQLServer\Logs" /SQLBACKUP="K:\SQLServer\Backups" /FAILOVERCLUSTERDISKS="CLU01_SQL_Data" "CLU01_SQL_Logs" "CLU01_SQL_Backups"````

Differentiating a clustered SQL instance and an AlwaysOn cluster is an interesting idea. Do you think there is value in creating a [composite resource](https://msdn.microsoft.com/en-us/powershell/dsc/authoringresourcecomposite) for building an Always On cluster? It could tie together the xFailoverCluster components as well as the applicable xSQLServer components and would drastically reduce the requirements for building a configuration to support that feature. Might be worth opening another issue to discuss.

**Comment by johlju** [comment]
@nabrond Don't know if using Parameter Sets will work since it is the schema.mof that ultimately controls the mandatory parameters? What you can do is to throw an error if the required parameters is not set. If we loose validation logic when the user builds the configuration file, then we might think twice about merging the two resources and instead do as @Zuldan suggest, to rename the resource and then implement he missing installation options in that renamed resource.

I leave that up to you, since I'm not to familiar with that resource.

Regarding AlwaysOn, I have resources already made for that purpose. See https://github.com/johlju/xSqlServerAlwaysOn. I gonna fix an issue for each resource so that we can discuss them. And after that it is just to have time to PR them in here (after at least fixing all Style Guideline changes that is needed). I will try getting issue for each resource as son as possible.

**Comment by forensicsguy20012004** [comment]
@nabrond an @johlju ... I do not have a repository out there...however, I do have a gist https://gist.github.com/forensicsguy20012004/92ca18dd0ed4297d2641158661e60363 which is for the Set-TargetResource function, I also had to make changes to the MSFT_xSQLServerFailoverClusterSetup.schema.mof and that can be found at this gist: https://gist.github.com/forensicsguy20012004/ea1918ca42b792396d2714a15ac3dd23; the key line is: String FailoverClusterIPAddress [];

The code in the function Set-TargetResource is not pretty, so don't freak out, but it does work and does get all the data to the command line install.

Just to put it out there again...here is what the command line install should look like for the 'CompleteFailoverCluster'

> setup.exe /SkipRules="Cluster_VerifyForErrors" /Quiet="True" /IAcceptSQLServerLicenseTerms="True" /Action="CompleteFailoverCluster" /InstanceName="MSSQLSERVER" /FailoverClusterGroup="SQL Server (MSSQLSERVER)" /FailoverClusterNetworkName="TST0000SQL" /FailoverClusterIPAddresses="IPv4;172.xx.xxx.xx;Cluster Network 1;255.255.255.0" "IPv4;10.xx.xxx.xxx;Cluster Network 2;255.255.255.0" /InstallSQLDataDir="S:\Program Files\Microsoft SQL Server\SystemDbs" /SQLUserDBDir="U:\Program Files\Microsoft SQL Server\Data" /SQLUserDBLogDir="L:\Program Files\Microsoft SQL Server\Logs" /SQLTempDBDir="T:\TempDB" /SQLTempDBLogDir="T:\TempDB" /SQLBackupDir="V:\Program Files\Microsoft SQL Server\Backups" /SQLSysAdminAccounts="Contoso\Admin" "Contoso\Admin2" /CONFIRMIPDEPENDENCYCHANGE=1

Let me know what else I can do?

**Comment by forensicsguy20012004** [comment]
Hey gang, where are we at on this...the FailoverClustering [non-AlwaysOn]?

**Comment by nabrond** [comment]
@forensicsguy20012004 I updated all the methods to handle merging the cluster setup code. I just have to write the unit tests before submitting a pull request. You can see my changes here https://github.com/nabrond/xSQLServer/tree/feat-issue-227.

**Comment by johlju** [comment]
@nabrond Can't see the new parameters in the schema.mof. Shouldn't they be there as well?

**Comment by nabrond** [comment]
@johlju I had not yet added the new parameters to the MOF. Just pushed them to my branch.

**Comment by forensicsguy20012004** [comment]
@nabrond...that is great to hear. Did what I provide you guys help out?
