### ISSUE TITLE
BREAKING CHANGE: xSQLServerEndpoint: Suggest replacing this resource with new version

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#232]
I suggest we replace the existing xSQLServerEndpoint with the [xSQLServerAlwaysOnEndpoint](https://github.com/johlju/xSqlServerAlwaysOn/tree/dev/DSCResources/xSQLServerAlwaysOnEndpoint) resource which we rename to xSQLServerEndpoint.

The current resource is hardcoded to give a provided user with the permission needed. But it is not just one user that needs to have the permission, it is the Health Detection account (SYSTEM) plus every account used to run the SQL Service which can be different on each replica. It would be better to use xSQLServerPermission resource to set the required permissions for each account.
Also the current resource does not provide the option to specify what IP address to use.

New resource:
https://github.com/johlju/xSqlServerAlwaysOn/tree/dev/DSCResources/xSQLServerAlwaysOnEndpoint
New resource schema:
```
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerEndpoint")]
class xSQLServerEndpoint : OMI_BaseResource
{
    [Key, Description("The SQL Server instance name.")] String InstanceName;
    [Required, Description("The host name or FQDN.")] String NodeName;
    [Write, Description("If the endpoint should be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Required, Description("The name of the endpoint.")] String Name;
    [Write, Description("The network port the endpoint is listening on. Default value is 5022.")] Uint16 Port;
    [Write, Description("The network IP address the endpoint is listening on. Default the endpoint will listen on all valid IP addresses.")] String IpAddress;
};
```

Old resource schema:
```
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerEndpoint")]
class MSFT_xSQLServerEndpoint : OMI_BaseResource
{
    [Key] String EndPointName;
    [Write, ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write] Uint32 Port;
    [Write] String AuthorizedUser;
    [Write] String SQLServer;
    [Write] String SQLInstanceName;
};
```

**Comment by johlju** [comment]
My suggestion is to remove AuthorizedUser (see issue #466) from xSQLServerEndpoint, and move over parameter IpAddress from xSQLServerAlwaysOnEndpoint.

**Comment by johlju** [comment]
xSQLServerAlwaysOnEndpoint uses cmdlet specific for creating Database Mirror endpoint, so that resource should be named xSQLServerDatabaseMirrorEndpoint. So think it is better to refactor he present xSQLServerEndpoint resource.

**Comment by Zuldan** [comment]
@johlju I agree with the rename of this resource. I also agree that the AuthorizedUser parameter in #466 should be removed. It doesn't make sense having 2 resources controlling permissions.

Regarding the scheme, there are some resources like xSQLServerAlwaysOnAvailabilityGroup and xSQLServerAlwaysOnAvailabilityGroupReplica that refer to the SQL Server as 'SQLServer' and yet other resources use 'NodeName'. Do you think the reference to the SQL Server should be standardised across resources?

**Comment by johlju** [comment]
@Zuldan My reference to renaming the resource was if we would go with using the resource in https://github.com/johlju/xSqlServerAlwaysOn/tree/dev/DSCResources/xSQLServerAlwaysOnEndpoint. That resource uses SQLPS cmdlets that can only be used for creating a Database Mirror endpoint. 
So my thought is to keep the existing resource (and the name) and to refactor the current resource to remove AuthorizedUser and add IpAddress. In the future I think xSQLServerEndpoint can be used to create other types of endpoints, so there is no need to change the present resource to use the SQLPS cmdlets, but keep the present logic and add to it instead. Make sense? Should I think differently? 

Regarding naming convention for parameters I really like it the were the same, and I started and issue for discussing that, see issue #308. Please add your idea about using NodeName for clustering resources to that issue. :)
