### ISSUE TITLE
New resource proposal: xSQLServerAlwaysOnAvailabilityGroup (could replace xSQLAOGroupEnsure)

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#236]
I have an existing resource that could be moved into this module
https://github.com/johlju/xSqlServerAlwaysOn/tree/dev/DSCResources/xSQLServerAlwaysOnAvailabilityGroup

This resource adds or removes the Primary Replica. The resource validate so that changes that are required to be done on the Primary Replica is only attempted when the node is Primary Replica. Before changing it verifies that the node is the Primary Replica, in this case when removing the Availability Group. It also handles if the state is no longer desired. If options has changes, this resource will set them back.
This resource already has a few more options and functionality than xSQLAOGroupEnsure. But to replace the resource xSQLAOGroupEnsure we need to add the following parameters `ReadableSecondary`,`ReadableSecondary` and `BackupPriority`. 

Schema
```
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerAlwaysOnAvailabilityGroup")]
class xSQLServerAlwaysOnAvailabilityGroup : OMI_BaseResource
{
    [Key, Description("The SQL Server instance name of the primary replica.")] String InstanceName;
    [Required, Description("The host name or FQDN of the primary replica.")] String NodeName;
    [Key, Description("The name of the availability group.")] String Name;
    [Write, Description("If the availability group should be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The availability mode for the primary replica"), ValueMap{"SynchronousCommit","AsynchronousCommit"}, Values{"SynchronousCommit","AsynchronousCommit"}] String AvailabilityMode;
    [Write, Description("The failover mode for the primary replica"), ValueMap{"Automatic","Manual"}, Values{"Automatic","Manual"}] String FailoverMode;
    [Write, Description("The length of time, in milliseconds, after which the availability group declares an unresponsive server to be unhealthy.")] UInt32 HealthCheckTimeout;
    [Write, Description("The automatic failover behavior of the availability group"), ValueMap{"OnServerDown","OnServerUnresponsive","OnCriticalServerErrors","OnModerateServerErrors","OnAnyQualifiedFailureCondition"}, Values{"OnServerDown","OnServerUnresponsive","OnCriticalServerErrors","OnModerateServerErrors","OnAnyQualifiedFailureCondition"}] String FailureConditionLevel;
};
```

**Comment by randomnote1** [comment]
I think this is a great idea. It'll really simplify the configs and make this resource more focused on doing one thing.

**Comment by johlju** [comment]
If this resource proposal is choosen, anyone is more than welcome to bring the resource over here.

**Comment by johlju** [comment]
@randomnote1 If you feel your changes is better done to this resource, you are more than welcome to fetch the code and PR it in here, new and improved. 😄

**Comment by randomnote1** [comment]
Cool, it sounds like you're pretty well along here. I'll pull it down and check it out. Thx!

**Comment by johlju** [comment]
Awesome! 😄  If you need help later on writing test or anything. Let me know. I'm happy to help. 😄 

_It is fully working. I installed a AlwaysOn cluster with that code. See full example in the Examples folder._

**Comment by randomnote1** [comment]
Is there a preferred method for me to lift the files from your repo and add them to the xSQLServer repo? Or will a simple copy/paste work fine for our purposes?

**Comment by johlju** [comment]
Since my repo is not based on xSQLServer I think it would be easier for you to copy the files into a working branch in your clone of xSQLServer and then PR in that working branch.

And also make sure it uses helper functions of xSQLServerHelper.psm1 where applicable.

**Comment by randomnote1** [comment]
Excellent, thanks!

**Comment by randomnote1** [comment]
I suppose I should also ask about deprecating xSQLServerAOGroupEnsure in favor of xSQLServerAlwaysOnAvailabilityGroup. We can probably discuss that down the road when this gets fleshed out a bit more.

**Comment by johlju** [comment]
I think we issue a separate issue discussing, and take action, on that once this are merged. That will become a breaking change which because of that needs a separate issue.
