### ISSUE TITLE
New resource proposal: xSQLServerAlwaysOnAvailabilityGroupReplica (could replace xSQLAOGroupJoin)

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#237]
I have an existing resource that could be moved into this module
https://github.com/johlju/xSqlServerAlwaysOn/tree/dev/DSCResources/xSQLServerAlwaysOnAvailabilityGroupReplica

This resource will create a Secondary Replica and join the replica to the Availability Group. But only if the Primary Replica is actually the node in `PrimaryReplicaNodeName` and will join the instance `PrimaryReplicaInstanceName` on the Primary Replica (this could be enhanced to failover the Primary Replica to the node in `PrimaryReplicaNodeName`)
It will remove a Secondary Replica from the Availability Group only if the node in `PrimaryReplicaNodeName` is the Primary Replica.
Any changes to the options on the secondary replica will be set back if if changes from desired state.
This should also add the any added parameters that is done to the  xSQLServerAlwaysOnAvailabilityGroup resource.

```
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerAlwaysOnAvailabilityGroupReplica")]
class xSQLServerAlwaysOnAvailabilityGroupReplica : OMI_BaseResource
{
    [Key, Description("The SQL Server instance name of the secondary replica.")] String InstanceName;
    [Key, Description("The host name or FQDN of the secondary replica.")] String NodeName;
    [Required, Description("The SQL Server instance name of the primary replica.")] String PrimaryReplicaInstanceName;
    [Required, Description("The host name or FQDN of the primary replica.")] String PrimaryReplicaNodeName;
    [Key, Description("The name of the availability group to which the secondary replica is or will be connected.")] String AvailabilityGroup;
    [Write, Description("If the secondary replica should be present or absent."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("The availability mode for the secondary replica."), ValueMap{"SynchronousCommit","AsynchronousCommit"}, Values{"SynchronousCommit","AsynchronousCommit"}] String AvailabilityMode;
    [Write, Description("The failover mode for the secondary replica."), ValueMap{"Automatic","Manual"}, Values{"Automatic","Manual"}] String FailoverMode;
    [Write, Description("If the primary replica has not responded, or can not be verified to be the primary replica within this time period, an error will be thrown.")] UInt16 Timeout;
};
```

**Comment by johlju** [comment]
If this resource proposal is choosen, anyone is more than welcome to bring the resource over here.

**Comment by randomnote1** [comment]
I think this is a great idea. It'll really simplify the configs and make this resource more focused on doing one thing. Additionally, it'll scale to all versions of SQL that support AGs.
