### ISSUE TITLE
xSQLServerLogin: Need to remove ShouldProcess from code

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#240]
**Details of the scenario you try and problem that is occurring:**
This resource is using non supported functions. Best practices are to not use ShouldProcess in DSC resources.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by randomnote1** [comment]
I have some code I've been working on to enhance this. Feel free to pass it my way.

**Comment by johlju** [comment]
It's yours. 😄

**Comment by randomnote1** [comment]
@johlju, I ccould use some assistance editing the SMO stubs since I don't have a ton of experience in C#.

I am trying to catch the [Microsoft.SqlServer.Management.Smo.FailedOperationException] exception and drill into an inner exception to get additional details.

I put the code excerpts here for quick review:
https://gist.github.com/randomnote1/4662b7b5f66c765c091cad3abbffeea9

Thanks!

**Comment by johlju** [comment]
Absolutely, I will look at this tonight or during the weekend.

**Comment by johlju** [comment]
Hmm... I see you throwing `throw new FailedOperationException` in the method `Create()` the User class. Shouldn't you move this `public void Create( SecureString password, LoginCreateOptions options )` method to the Login class?

**Comment by randomnote1** [comment]
Thanks man, not sure why I put it there.

**Comment by johlju** [comment]
@randomnote1 Was about to look into helping you to catch `[Microsoft.SqlServer.Management.Smo.FailedOperationException]`.
But I saw the gist was gone now. And looking at your working branch it seems you have solved it yourself 😄 👍 

Let me know if you need any further help with anything. Sorry it took so long for me to assist you. But you did a good job doing it yourself 😄 

For your knowledge, if you need to, you can also use the global class to tell the mock class to generate mock data. See the class Server() for an example. And from the tests you can dynamically turn it off and on with.
```powershell
[Microsoft.SqlServer.Management.Smo.Globals]::GenerateMockData = $true
```

**Comment by randomnote1** [comment]
Cool, thanks! 👍 I'll have to try that out at some point.
