### ISSUE TITLE
BREAKING CHANGE: xSQLServerDatabasePermissions: Rename resource

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#243]
**Details of the scenario you try and problem that is occurring:**
This resource has the wrong name compared to the other resources. This resource uses plural in it's name and the other resources are using singular in their name.
I suggest we rename this resource to 'xSQLServerDatabasePermission'.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
'dev'

**Comment by luigilink** [comment]
I can add this issue in PR #140.
Just tell me 😃

**Comment by johlju** [comment]
Yes you you wouldn't mind, since your change in PR #140 already is a breaking change this change would be suitable there as well. 

This is yours @luigilink 😄
