### ISSUE TITLE
Process of release cycle to PS Gallery

### ISSUE THREAD

**Issue by Arturas-K** [PowerShell/xSQLServer#25]
Hi,

I have a general question regarding release process.
I was wondering when can we expect changes in Dev branch to be merged into master and released to PS Gallery as 1.4.0.0?
Is there an agreed process or release train, on how often or at what times this is done?
Is there any guidelines that someone could point me to that explain this?

This is just for general awareness, would be good to know what to expect.

Andy info would be appreciated.

Thanks, Arturas

**Comment by kilasuit** [comment]
@KarolKaczmarek This would be beneficial to be updated (pref in the Readme of all xDSCResources repos) not just this one like i've raised in the DSCResources repository in https://github.com/PowerShell/DscResources/issues/100

**Comment by KarolKaczmarek** [comment]
1.4.0.0 has been released on 2/3/2016 (http://www.powershellgallery.com/packages/xSQLServer/1.4.0.0) 
Regarding the question about release schedule, I've addressed it in PowerShell/DscResources#100 , so we can continue discussion there. Closing this issue
