### ISSUE TITLE
xSQLServerSetup: Impossible to update paths and service account of an existing instance?

### ISSUE THREAD

**Issue by Yvand** [PowerShell/xSQLServer#253]
**Details of the scenario you try and problem that is occurring:**
I have an existing SQL Server 2016 instance and I'm trying to update following settings:
- Path for SQL database files
- Path for SQL log files
- Service account for the SQL service

**The DSC configuration that is using the resource (as detailed as possible):**
The only resource that seems capable of doing that is xSQLServerSetup, but it seems only designed to add new instances, not update existing ones.
Is there a way to achieve what I need?
I tried this but it fails because it doesn't find setup.exe:
```powershell
xSQLServerSetup ConfigureSQLServer
{
	SetupCredential = $AdminCreds
	InstanceName = "MSSQLSERVER"
	SQLUserDBDir = "F:\DATA"
	SQLUserDBLogDir = "G:\LOG"
	SQLCollation = "Latin1_General_CI_AS_KS_WS"
}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
na

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
xSQLServer 4.0.0.0

**Comment by johlju** [comment]
@Yvand thanks for submitting you issue!

Unfortunately today xSQLServerSetup is currently limited to install SQL Server, and does not handle any drift in desired state. There is a issue for that, see issue #37. 

I keep this issue open since this particular properties could be resolved in either by xSQLServerSetup or in a new separate resource. The discussion around this issue will pan out which way to go.

**Comment by randomnote1** [comment]
I believe part of this is being addressed in issue #656.

**Comment by nabrond** [comment]
Part of this was covered in issue #706. @Yvand managing service accounts was added through pull request #795. Not sure when it will be formally released, but you grab a copy of dev if you want to jump on this now.

**Comment by Yvand** [comment]
Thank you!
I'll wait for this PR to be published in an official release and I'll test it.

**Comment by johlju** [comment]
There is a community call on the 27:th (see [agenda](https://github.com/PowerShell/DscResources/blob/master/CommunityCalls/2017-09-27/agenda.md)). Release is normally schedule within two weeks from that (but can differ). Usually the release date is announced during the community call. 

Closing this as this (the missing functionality) is being tracked in other issues.
