### ISSUE TITLE
When will Version 1.4.0 be released

### ISSUE THREAD

**Issue by abouman** [PowerShell/xSQLServer#26]
I have started using resources in this version, and was surprised to see that it wasn't yet released.
When will this be released?
Using the following command, I only show version 1.3.0:
find-module -includes DscResource -verbose
Please advise - thank you!
Angela Bouman

**Comment by TravisEz13** [comment]
@KarolKaczmarek can you answer this question?

**Comment by abouman** [comment]
As a side note - in the meantime, I have taken the code provided and created custom resources for those that I needed.  AB

**Comment by KarolKaczmarek** [comment]
@abouman 
1.4.0.0 has been released http://www.powershellgallery.com/packages/xSQLServer/1.4.0.0 ( we aim to have new releases every few weeks).
