### ISSUE TITLE
Server roles

### ISSUE THREAD

**Issue by tonituovinen** [PowerShell/xSQLServer#30]
Is it possible to grant server roles to users? It would be great if you could grant them using xSQLServerLogin resource.

**Comment by Arturas-K** [comment]
Second that.

I'm willing to contribute this, but not sure if it is better to update xSQLServerLogin with parameter that would be array of serverRoles, or create separate resource xSQLServerRoleMember that would manage one role, login at a time?

Guidance would be appreciated what would be preferred approach.

**Comment by johlju** [comment]
I would prefer xSqlServerRoleMember so you can use it on existing logins. And if a login does not exist I would rather have this as a two step (two resources), add the login in step one and in step two set the permission for that login (which could be more than server roles in a third step).

**Comment by johlju** [comment]
I would like to see xSqlServerRoleMember manage one role, but it could take more than one login in the member parameter.

**Comment by luigilink** [comment]
DSC Resource coded : see pull request #67.

**Comment by rakkhin** [comment]
Since PR #67 went dormant and i wasn't able to reach it's source repo, here's my take on this issue in PR #74.
