### ISSUE TITLE
Readme out of date for xSqlServerDatabase

### ISSUE THREAD

**Issue by ndarwincorn** [PowerShell/xSQLServer#302]
**Details of the scenario you try and problem that is occurring:**

Tried running xSqlServerDatabase with the params described in the readme. It errored out on invalid params. Examining the current schema and docs still shows the discrepancy.

Readme params:
- SqlServer
- SqlInstance
- Database
- Ensure

Actual params:
- SqlServer
- SqlInstance*Name*
- *Name*
- Ensure

Didn't see anyone else pointing it out so I thought I would. I'd submit a PR but for a docs change that seems like overkill.

**The DSC configuration that is using the resource (as detailed as possible):** N/A

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:** N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:** 4.0.0.0

**Comment by johlju** [comment]
Thanks for reporting this issue. :)

If you can submit a PR to resolve this issue I would appreciate it. The only correct way to change this is thru PR.
Let me know if this is something you want to do.

**Comment by ndarwincorn** [comment]
Yeah I can do that.

**Comment by johlju** [comment]
Awesome, then this is yours. I will label this as in progress.

Thanks!
