### ISSUE TITLE
xSQLServerSetup: should not use PID to store the Product Key

### ISSUE THREAD

**Issue by danielboth** [PowerShell/xSQLServer#332]
**Details of the scenario you try and problem that is occurring:**
XSQLServerSetup uses the parameter PID to store the product key for SQL Server. However, $PID is an automatic variable used internally by PowerShell to store the Process ID. This variable is read-only, although in DSC context it does get overwritten. This causes issues while debugging the resource, as the $PID variable no longer holds the Process ID of the process.

**The DSC configuration that is using the resource (as detailed as possible):**
All configurations using PID parameter to specify Product ID.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Any

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
4.0.0.0

**Suggestion**
Rename PID to ProductKey, that way it will not collide with the automatic variable $PID

**Comment by johlju** [comment]
Thanks for reporting this!

All parameter names use the same names as the arguments used by setup.exe (which I personally think is bad for readability). This conflict was obviously overlooked. Thank you for suggestion a fix. Let's get that fix in soon.

**Comment by danielboth** [comment]
Thanks! I noticed xSQLServerFailoverClusterSetup has the same issue.
Feel free to assign this one to me, I'll work on a fix.. should be a pretty easy one.

**Comment by johlju** [comment]
xSQLServerFailoverClusterSetup is being deprecated soon, moved to xSQLServerSetup. PR in the works. 

But if you like you can fix it in xSQLServerSetup 😄 You are assigned! Thanks!
