### ISSUE TITLE
xSQLServerSetup: When attempting to install a clustered instance, installation fails with 'WMI service not running' error

### ISSUE THREAD

**Issue by yardbirdsax** [PowerShell/xSQLServer#345]
**Details of the scenario you try and problem that is occurring:**
When attempting to install a clustered instance, the setup process fails with the error shown below.
`
Exception type: Microsoft.SqlServer.Configuration.RulesEngineExtension.RulesEngineRuleFailureException
    Message: 
        The WMI service is not running on the cluster node.
    HResult : 0x84be0bbc
        FacilityCode : 1214 (4be)
        ErrorCode : 3004 (0bbc)
    Data: 
      SQL.Setup.FailureCategory = RuleViolationFailure
      DisableWatson = true
    Stack: 
        at Microsoft.SqlServer.Configuration.RulesEngineExtension.RunRulesAction.ExecuteAction(String actionId)
        at Microsoft.SqlServer.Chainer.Infrastructure.Action.Execute(String actionId, TextWriter errorStream)
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.<>c__DisplayClasse.<ExecuteActionWithRetryHelper>b__b()
        at Microsoft.SqlServer.Setup.Chainer.Workflow.ActionInvocation.ExecuteActionHelper(ActionWorker workerDelegate)
`

I believe this is because the process is run in the context of a local account, which cannot access the remote cluster nodes. If I run the generated setup command manually as a logged in domain user, it works fine.

**The DSC configuration that is using the resource (as detailed as possible):**
Any configuration using the "InstallFailoverCluster" action. It might apply to other cluster based cases but I haven't used them.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
SQL 2016 and Windows 2016

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by yardbirdsax** [comment]
Just to note this only popped up after I modified some things to fix the problem in #344 .

**Comment by johlju** [comment]
Seems that this needs a bit of more work! Thanks for reporting! I'm setting up a lab so I can test this in.

**Comment by yardbirdsax** [comment]
@johlju I actually have fixes for this and the other issues I'm opening, would be happy to create a pull request when I'm done and have a working install.

**Comment by yardbirdsax** [comment]
@johlju Do you want me to open separate issues for the (~2 other) problems I found and fixed to get a working setup, or should I just update this (or #344 ) to include a list of the other problems?

**Comment by johlju** [comment]
Sorry I was slow to respond. Has been busy days. 

Yes, please open up separate issues, if they are unrelated to this or #344. 

It would be awesome if you can send in a pull request with the changes. When you send in the PR, the description field will be pre-filled with help text, and you will see that you can add all issue numbers your PR solves in the PR description. If you do they will be auto-closed on merge of the PR.

Thank you @yardbirdsax!

**Comment by yardbirdsax** [comment]
No problem, we're all busy! :) I will open the additional issues and then submit the PR once I've tested everything. I am trying to update the unit tests as best I can, first time user of Pester here, so please let me know if you see additional tests I should incorporate.

**Comment by johlju** [comment]
It has been a first time using Pester for all of us :) I will review your PR, if there are any tests I feel are lacking I will let you know. :)

**Comment by johlju** [comment]
@yardbirdsax I label this as in progress. In each issue you are working on, could you please comment that you are working on it and I will label those in progress as well. :)

**Comment by yardbirdsax** [comment]
@johlju Done! Hope to have everything sorted early this week. My deadlines at work to have an install complete will be beneficial in this case.

**Comment by johlju** [comment]
Great! Labelled all the issues. Looking forward to the PR. :)
