### ISSUE TITLE
xSQLServer: Invoke-Sqlcmd' command was found in the module 'SqlServer

### ISSUE THREAD

**Issue by bodunjo** [PowerShell/xSQLServer#350]
I ran into the following error message when i was trying to run the Xsqlserverscript module:

VERBOSE: [ServerName]: LCM:  [ Start  Test     ]  [[xSQLServerScript]PostSQLInstall::[TestScript]SAUser::[TestScript]SAUser]
VERBOSE: [ServerName]:                            [[xSQLServerScript]PostSQLInstall::[TestScript]SAUser::[TestScript]SAUser] 2017-01-27_16-59-48: Importing SQL
PS module.
The 'Invoke-Sqlcmd' command was found in the module 'SqlServer', but the module could not be loaded. For more information, run 'Import-Module SqlServer'.
    + CategoryInfo          : ObjectNotFound: (Invoke-Sqlcmd:) [], CimException
    + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule,Invoke-SqlScript
    + PSComputerName        : ServerName
 
VERBOSE: [ServerName]: LCM:  [ End    Test     ]  [[xSQLServerScript]PostSQLInstall::[TestScript]SAUser::[TestScript]SAUser]  in 17.1100 seconds.
The PowerShell DSC resource '[xSQLServerScript]PostSQLInstall::[TestScript]SAUser::[TestScript]SAUser' with SourceInfo '::356::1::xSQLServerScript' threw one or 
more non-terminating errors while running the Test-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : ServerName
 
VERBOSE: [CTDMTI01VMSQL02]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : ServerName

--xSQLServerScript Resource
xSQLServerScript PostSQLInstall
{
    GetFilePath =  "\\Sharefilepath\SQL Team\SQLInstalls\SQLInstaller\DBA\First-Responder-Kit-20150910\--Master_Script.sql"
    ServerInstance = $InstanceName
    SetFilePath =  "\\Sharefilepath\SQL Team\SQLInstalls\SQLInstaller\DBA\First-Responder-Kit-20150910\--Master_Script.sql"
    TestFilePath = $False
    Credential = (Get-Credential -UserName ("domain\user") -Message 'Enter Credential for DSC Setup')
    DependsOn = "[xSQLServerRole]DatabaseOwnerPublic"
    PsDscRunAsCredential = (Get-Credential -UserName ("domain\user") -Message 'Enter Credential for DSC Setup')
    #Variable = string
}
---- DELETE THIS LINE AND ABOVE ----

**Details of the scenario you try and problem that is occurring:**

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

**Comment by johlju** [comment]
We currently does not support the new SqlServer module, only SQLPS module that is part of SQL Server. SQLServer is part of the new SQL Server Management Studio. 
We should support both, so let's keep this issue open so this can be solved.

**Comment by bodunjo** [comment]
Is there any alternative resource to run a Sqlcmd script?

Sent from my iPhone

On 27 Jan 2017, at 18:38, Johan Ljunggren <notifications@github.com<mailto:notifications@github.com>> wrote:


We currently does not support the new SqlServer module, only SQLPS module that is part of SQL Server. SQLServer is part of the new SQL Server Management Studio.
We should support both, so let's keep this issue open so this can be solved.

-

**Comment by johlju** [comment]
Not in xSQLServer module. But you could try using the built-in Script Resource. 
https://msdn.microsoft.com/en-us/powershell/dsc/scriptresource

**Comment by virtrixke** [comment]
You can fix this by removing (or commenting out) the "Import-SQLPSModule" call in function Invoke-SqlScript in MSFT_xSQLServerScript.psm1. I was able to use the xSQLScript function successfully after that. In SQL 2016, it is now import-module sqlserver, and not import-SQLPSModule...

**Comment by johlju** [comment]
In issue #91 there is a suggestion to load SQLServer module if it exist. 

I will close this issue now. Please reopen if there are still issues not resolved.
