### ISSUE TITLE
xSQLServerSetup: When attempting clustered installations, the FAILOVERCLUSTERIPADDRESS parameter value has extra spaces in it

### ISSUE THREAD

**Issue by yardbirdsax** [PowerShell/xSQLServer#352]
**Details of the scenario you try and problem that is occurring:**
When specifying either InstallFailoverCluster, AddNode, or CompleteFailoverCluster as Action, the setup parameter FAILOVERCLUSTERIPADDRESS is generated with extra spaces and causes the installation to fail.

**The DSC configuration that is using the resource (as detailed as possible):**
Any configuration specifying the InstallFailoverCluster, AddNode, or CompleteFailoverCluster Action.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
SQL Server 2016 on Windows 2016

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by johlju** [comment]
@yardbirdsax do you have a fix in the works for this already? Or can @nabrond take this one?

**Comment by yardbirdsax** [comment]
I've got the fix already done, just trying to get the work done for #353 as well before submitting the pull request.

**Comment by johlju** [comment]
@nabrond @yardbirdsax got this one then.
