### ISSUE TITLE
xSQLServerHelper: Confirm-SqlServerRoleMember is referencing the wrong variable name

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#355]
**Details of the scenario you try and problem that is occurring:**
Confirm-SqlServerRoleMember has parameter name $LoginName but uses variable $Name where it should be using $LoginName.

This leads to that xSQLServerRole can not correctly reports that the desired state is present when the login is already a member of the server roles.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by luigilink** [comment]
#351
