### ISSUE TITLE
xSQLServerDatabaseOwner: Helper function Get-SqlDatabaseOwner is missing localization key 'FailedToGetOwnerDatabase'

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#365]
**Details of the scenario you try and problem that is occurring:**
Helper function Get-SqlDatabaseOwner is referencing localization key 'FailedToGetOwnerDatabase' but it does not exist in xSQLServer.strings.psd1.
Localization key needs to be added with a correct descriptive error message.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by luigilink** [comment]
Bug fixed in PR #409
