### ISSUE TITLE
xSqlServerSetup: Why can't xSqlServerSetup use identity of LCM?

### ISSUE THREAD

**Issue by pmcevoy** [PowerShell/xSQLServer#379]
Until recently, I have been setting up Sql Server on test VMs using a version of the Script resource approach documented [here:](http://www.colinsalmcorner.com/post/install-and-configure-sql-server-using-powershell-dsc).   Using that approach, I'm pretty sure that the  identity of the LCM (LocalSystem) is being used to install sql server as that is the identity running the script

Today I started to look at xSqlServerSetup resource, as I would prefer to use native resources over custom ones. I'm stuck trying to resolve the required "SetupCredential" property on the resource:  I don't want to use a domain account because 

- I don't want to store passwords in MOF files (PSDscAllowPlainTextPassword) - even encrypted using a cert. 
- The credential is provided at the time the MOF is compiled, not when the configuration is applied and our domain account passwords are set to expire monthly (requiring maintenance) 

Why exactly is SetupCredential needed for Sql Server setup?  Compare this to Chocolatey or Package resources which also install things to the machine, but don't require a credential

**Comment by pmcevoy** [comment]
Hmm - seems this may be dupe of [139](https://github.com/PowerShell/xSQLServer/issues/139) - in particular this [comment](https://github.com/PowerShell/xSQLServer/issues/139#issuecomment-270136906)

I will watch the other thread and hold off on using the resource..

**Comment by johlju** [comment]
Actually, issue #139 doesn't take in account that it should be able to be installed using SYSTEM. Actually I never thought that it was even possible. So lets keep this issue open to track that possibility. If the conclusion is that there are problems around that, then at the minimum it should be added to the documentation that it is not possible to install using SYSTEM.

**Comment by johlju** [comment]
In PR #578 will enable xSQLServerSetup to be installed using SYSTEM. SetupCredential has been removed and if not specifying PsDscRunAsCredential, the resource will run and install as SYSTEM.
