### ISSUE TITLE
xSqlServerSetup - SQLSysAdminAccounts is ignored

### ISSUE THREAD

**Issue by pmcevoy** [PowerShell/xSQLServer#381]
I'm trying to pass in an array of domain accounts and groups that should be set as SQLSysAdminAccounts. But my instance is being created with the admin account being the same as the SetupCredential.  My configuration specifies:

`
SQLSysAdminAccounts = @("EZETOP\Developers", "EZETOP\SG-QA", "EZETOP\Domain Admins", "BUILTIN\Administrators")
`

However I see this in the "set" code for the resource:

`
VERBOSE: [TESTEZE-BE67HAU]: [[xSQLServerSetup]RDBMS] 2017-02-10_16-53-11: Starting setup using arguments: /ACTION="Install" /INSTANCEID="MSSQLSERVER2" /INSTANCEDIR="C:\DbDataFiles" /AGTSVCSTARTUPTYPE="Automatic" /QUIET="True" /IACCEPTSQLSERVERLICENSETERMS="True" /SECURITYMODE="SQL" /SQLCOLLATION="Latin1_General_CI_AS" /INSTANCENAME="MSSQLSERVER2" /UPDATESOURCE="\\sv-hq-nas01\installers\M\Microsoft\MicrosoftSQLServer2012DeveloperEdition_WithSP2_Slipstream\SQLUpdates" /SQMREPORTING="False" /SQLSYSADMINACCOUNTS="NT AUTHORITY\SYSTEM" /ERRORREPORTING="False" /FEATURES=SQLENGINE,FULLTEXT /UPDATEENABLED="True" /SAPWD="********"
`

I can't help but think this is a bug due to the line 928 in `MSFT_xSQLServerSetup.psm1`:

`
if ($PSBoundParameters -icontains 'SQLSysAdminAccounts')
`

while every other check of input params is using the following pattern

`
if($PSBoundParameters.ContainsKey('AgtSvcAccount'))
`

[This comment](https://github.com/PowerShell/xSQLServer/issues/116#issuecomment-241960371) seems to indicate that the `-icontains` wasn't always there, so this seems like a regression...

**Comment by pmcevoy** [comment]
Doh! duplicate of https://github.com/PowerShell/xSQLServer/issues/371

**Comment by johlju** [comment]
And it is being worked on in #370 also.
