### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroup not creating Availability Replica

### ISSUE THREAD

**Issue by iyoumans** [PowerShell/xSQLServer#385]
I'm hitting a problem with xSQLServerAlwaysOnAvailabilityGroup (dev branch) where it is failing to create the availability replica but not throwing an error.  Thus, the availability group create bombs out with an error saying that the current instance must be included as an availability replica.

When I go through the xSQLServerAlwaysOnAvailabilityGroup code line by line (as SYSTEM), when I run the New-SQLAvailabilityReplica command, no errors occur but the replica isn't created:

PS C:\Users\myuser> $newReplicaParams

Name                           Value                                                                                                                                                         
----                           -----                                                                                                                                                         
Version                        12                                                                                                                                                            
AsTemplate                     True                                                                                                                                                          
Name                           localhost\myinst                                                                                                                                             
ConnectionModeInPrimaryRole    AllowAllConnections                                                                                                                                           
AvailabilityMode               AsynchronousCommit                                                                                                                                            
FailoverMode                   Automatic                                                                                                                                                     
ConnectionModeInSecondaryRole  AllowAllConnections                                                                                                                                           
EndpointUrl                    TCP://localhost:5022                                                                                                                                          

PS C:\Users\myuser> $primaryReplica = New-SqlAvailabilityReplica @newReplicaParams -ErrorAction Stop

PS C:\Users\myuser> $primaryReplica

Name                 Role      ConnectionState RollupSynchronizationState
----                 ----      --------------- --------------------------
localhost\myinst                                                        

This is on Windows 2012, SQL Server 2014, Powershell 5.x.  SQL Server is installed with instance myinst and endpoint Hadr_Enpoint created. Cluster is already created.

Thanks!

**Comment by johlju** [comment]
Just to make sure. You have either of these accounts set with these permissions? So that there is no problem in the logic to test these permissions.

>'NT SERVICE\ClusSvc' or 'NT AUTHORITY\SYSTEM' must have the 'Connect SQL', 'Alter Any Availability Group', and 'View Server State' permissions.

Could you test using a domain account with the built-in parameter `PsDscRunAsCredential`? Just to rule that out.

Could you post your configuration (replace any sensitive information)? It is easier to debug using the same config.

**Comment by iyoumans** [comment]
'NT AUTHORITY\SYSTEM'  has those permissions (I ran through the code line by line and checked the perms when I hit that part - ALTER ANY AVAILABILITY GROUP, CONNECT SQL, CREATE AVAILABILITY GROUP, VIEW ANY DATABASE, VIEW SERVER STATE).  I can try with a domain account but it doesn't appear that is the problem.  Here's my config:



Configuration AlwaysOnInstall
{
    Param(
    
        [Parameter()][string]$Role,
        [Parameter()][string]$ClusterName,
        [Parameter()][string]$ClusterIPAddress,
        [Parameter()][string]$AvailGroupName,
        [Parameter()][string]$AvailGroupListenerName,
        [Parameter()][string]$AvailGroupListenerIPAddress,
        [Parameter()][string]$AvailGroupListenerSubnetMask
    
    )

    Import-DscResource –ModuleName @{ModuleName = 'PSDesiredStateConfiguration';ModuleVersion = '1.1'}
    Import-DscResource -ModuleName @{ModuleName = 'xPSDesiredStateConfiguration';ModuleVersion = '3.5.0.0'}
    Import-DscResource -ModuleName @{ModuleName = 'xSQLServer';ModuleVersion = '5.0.0.0'}
    Import-DscResource -ModuleName @{ModuleName = 'xFailoverCluster';ModuleVersion = '1.6.0.0'}

    Node ("localhost")
    {
           $PassWord = ConvertTo-SecureString -AsPlainText -String '#########' -Force
           $SetupCredential = New-Object System.Management.Automation.PSCredential ("DOMAIN\user", $PassWord)

           WindowsFeature FailoverFeature
           {
               Ensure = "Present"
               Name      = "Failover-clustering"
           }

           WindowsFeature RSATClusteringMgmt
           {
               Ensure = "Present"
               Name = "RSAT-Clustering-Mgmt"
               DependsOn = "[WindowsFeature]FailoverFeature"
           }

           WindowsFeature RSATClusteringPowerShell
           {
               Ensure = "Present"
               Name   = "RSAT-Clustering-PowerShell"   
               DependsOn = "[WindowsFeature]RSATClusteringMgmt"
           }

           WindowsFeature RSATClusteringCmdInterface
           {
               Ensure = "Present"
               Name   = "RSAT-Clustering-CmdInterface"
               DependsOn = "[WindowsFeature]RSATClusteringPowerShell"
           }

           if ($Role -eq 'PrimaryClusterNode')
           {

               WindowsFeature ADTools
               {
                   Ensure = "Present"
                   Name = "RSAT-AD-PowerShell"
                   Source = "C:\Windows\WinSxS"
                   DependsOn = “[WindowsFeature]RSATClusteringCmdInterface”
               }

               xCluster ensureCreated
               {
                   Name = $ClusterName
                   StaticIPAddress = $ClusterIPAddress
                   DomainAdministratorCredential = $SetupCredential
                   DependsOn = “[WindowsFeature]ADTools”
               }

               xSQLServerAlwaysOnService AlwaysOnService
               {
                    Ensure = "Present"
                    SQLServer = "localhost"
                    SQLInstanceName = "myinst"
                    DependsOn = "[xCluster]ensureCreated"
               } 
       
               xSQLServerEndpoint SQLEndpoint
               {
                   Ensure = "Present"
                   Port = 5022
                   AuthorizedUser = $SetupCredential.UserName
                   EndPointName = "Hadr_endpoint"
                   SQLServer = "localhost"
                   SQLInstanceName = "myinst"
                   DependsOn = "[xSQLServerAlwaysOnService]AlwaysOnService"
               }
       
               xSQLServerAlwaysOnAvailabilityGroup CreateAvailabilityGroup
               {
                  Ensure = "Present"
                  Name = $AvailGroupName
                  AvailabilityMode = "AsynchronousCommit"
                  ConnectionModeInPrimaryRole = "AllowAllConnections"
                  ConnectionModeInSecondaryRole = "AllowAllConnections"
                  FailureConditionLevel = "OnServerUnresponsive"
                  FailoverMode = "Automatic"
                  SQLServer = "localhost"
                  SQLInstanceName = "myinst"
                  EndpointHostName = "localhost"
                  DependsOn = "[xSQLServerEndpoint]SQLEndpoint"
               }
       
               xSQLServerAvailabilityGroupListener CreateGroupListener
               {
                  Ensure = "Present"
                  Name = $AvailGroupListenerName
                  AvailabilityGroup = $AvailGroupName
                  IpAddress = $AvailGroupListenerIPAddress + '/' + $AvailGroupListenerSubnetMask
                  Port = 5022
                  DHCP = $false
                  NodeName = "localhost"
                  InstanceName = "myinst"
                  DependsOn = "[xSQLServerAlwaysOnAvailabilityGroup]CreateAvailabilityGroup"
               }

           }
           elseif ($Role -eq 'ReplicaServerNode')
           {
        
               xWaitForCluster waitForCluster 
               { 
                   Name = $ClusterName 
                   RetryIntervalSec = 10 
                   RetryCount = 6
                   DependsOn = "[WindowsFeature]RSATClusteringCmdInterface"
               } 
       
               xCluster joinCluster 
               { 
                   Name = $ClusterName 
                   StaticIPAddress = $ClusterIPAddress 
                   DomainAdministratorCredential = $SetupCredential
                   DependsOn = "[xWaitForCluster]waitForCluster" 
               }

               xSQLServerAlwaysOnService AlwaysOnService
               {
                    Ensure = "Present"
                    SQLServer = "localhost"
                    SQLInstanceName = "myinst"
                    DependsOn = "[xCluster]joinCluster"
               }

               xSQLServerEndpoint SQLEndpoint
               {
                   Ensure = "Present"
                   Port = 5022
                   AuthorizedUser = "FPGEUSDEV\hford9"
                   EndPointName = "Hadr_endpoint"
                   DependsOn = "[xSQLServerAlwaysOnService]AlwaysOnService"
               }
       
               xWaitForAvailabilityGroup waitforAG
               { 
                   Name = $AvailGroupName 
                   RetryIntervalSec = 20 
                   RetryCount = 6
                   DependsOn = "[xSQLServerEndpoint]SQLEndpoint"
               } 
       
               xSQLAOGroupJoin JoinAvailabilityGroup
               {
                  Ensure = "Present"
                  AvailabilityGroupName = $AvailGroupName
                  SetupCredential = $SetupCredential
                  PsDscRunAsCredential = $SetupCredential
                  DependsOn = "[xWaitForAvailabilityGroup]waitforAG"
               }

           }
           else
           {
        
               xWaitForCluster waitForCluster 
               { 
                   Name = $ClusterName 
                   RetryIntervalSec = 10 
                   RetryCount = 6
                   DependsOn = "[WindowsFeature]RSATClusteringCmdInterface"
               } 
       
               xCluster joinCluster 
               { 
                   Name = $ClusterName 
                   StaticIPAddress = $ClusterIPAddress 
                   DomainAdministratorCredential = $SetupCredential
                   DependsOn = "[xWaitForCluster]waitForCluster" 
               }

           }

    }

}


$params = @{
    'Role'                           ='PrimaryClusterNode'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
    'ClusterName'                    ='mycluster'
    'ClusterIPAddress'               ='10.1.2.250'
    'AvailGroupName'                 ='myavg'
    'AvailGroupListenerName'         ='mylistener'
    'AvailGroupListenerIPAddress'    ='10.1.2.5'
    'AvailGroupListenerSubnetMask'   ='255.255.252.0'
}

$cd = @{
    AllNodes = @(
        @{
            NodeName = 'localhost'
            PSDscAllowPlainTextPassword = $true
            PSDscAllowDomainUser = $true
        }
    )
}

**Comment by johlju** [comment]
I wonder if endpoint should be the node name (server name) instead. First thing I would test. I don't have an environment ready to run this at the moment.

Also could you run `New-SqlAvailabilityReplica` with the `-Verbose` parameter to see if that gives anything. Or maybe `-Debug`. 
It is very strange it just returns without an error. No errors in ERRORLOG in SQL Server? No errors in Event Log?

**Comment by randomnote1** [comment]
If I recall correctly, EndPointHostName must be the same as the NetName property, or the FQDN of the NetName.

**Comment by iyoumans** [comment]
I think you're on to something with the EndpointHostName, but my test environment is currently messed up.  I'll post my results when I get it back up.  Thanks for the help.

**Comment by iyoumans** [comment]
Okay - progress!  I was able to create the Availability Group (I switched EndpointHostName from 'localhost' to $env:COMPUTERNAME).  Now I'm getting an error on creating the listener with xSQLServerAvailabilityGroupListener.  I'm indicating port 5022 but it says it's in use.  I specified 5022 when I set up the sql endpoint, but that should be okay right?  Exact error is:

DSC resource MSFT_xSQLServerAvailabilityGroupListener  failed to execute Set-TargetResource functionality with error message: The configuration changes to the availability group listener were completed, but the TCP 
provider of the instance of SQL Server failed to listen on the specified port [mylistener:5022]. This TCP port is already in use. Reconfigure the availability group listener, specifying an available TCP port. For information 
about altering an availability group listener, see the "ALTER AVAILABILITY GROUP (Transact-SQL)" topic in SQL Server Books Online.

See my code snippet below:

    Node ("localhost")
    {
           WindowsFeature FailoverFeature
           {
               Ensure = "Present"
               Name      = "Failover-clustering"
           }

           WindowsFeature RSATClusteringMgmt
           {
               Ensure = "Present"
               Name = "RSAT-Clustering-Mgmt"
               DependsOn = "[WindowsFeature]FailoverFeature"
           }

           WindowsFeature RSATClusteringPowerShell
           {
               Ensure = "Present"
               Name   = "RSAT-Clustering-PowerShell"   
               DependsOn = "[WindowsFeature]RSATClusteringMgmt"
           }

           WindowsFeature RSATClusteringCmdInterface
           {
               Ensure = "Present"
               Name   = "RSAT-Clustering-CmdInterface"
               DependsOn = "[WindowsFeature]RSATClusteringPowerShell"
           }

           if ($Role -eq 'PrimaryClusterNode')
           {

               WindowsFeature ADTools
               {
                   Ensure = "Present"
                   Name = "RSAT-AD-PowerShell"
                   Source = "C:\Windows\WinSxS"
                   DependsOn = “[WindowsFeature]RSATClusteringCmdInterface”
               }

               xCluster ensureCreated
               {
                   Name = "mycluster"
                   StaticIPAddress = "10.1.2.250"
                   DomainAdministratorCredential = $SetupCredential
                   DependsOn = “[WindowsFeature]ADTools”
               }
        
               xWaitForCluster waitForCluster 
               { 
                   Name = "mycluster" 
                   RetryIntervalSec = 10 
                   RetryCount = 6
                   DependsOn = "[xCluster]ensureCreated"
               } 

               xSQLServerAlwaysOnService AlwaysOnService
               {
                    Ensure = "Present"
                    SQLServer = $env:COMPUTERNAME
                    SQLInstanceName = "myinst"
                    DependsOn = "[xWaitForCluster]waitForCluster"
               } 
       
               xSQLServerEndpoint SQLEndpoint
               {
                   Ensure = "Present"
                   Port = 5022
                   AuthorizedUser = $SetupCredential.UserName
                   EndPointName = "Hadr_endpoint"
                   SQLServer = $env:COMPUTERNAME
                   SQLInstanceName = "myinst"
                   DependsOn = "[xSQLServerAlwaysOnService]AlwaysOnService"
               }
       
               xSQLServerAlwaysOnAvailabilityGroup CreateAvailabilityGroup
               {
                  Ensure = "Present"
                  Name ="myavg"
                  AvailabilityMode = "SynchronousCommit"
                  ConnectionModeInPrimaryRole = "AllowAllConnections"
                  ConnectionModeInSecondaryRole = "AllowAllConnections"
                  FailureConditionLevel = "OnServerUnresponsive"
                  FailoverMode = "Automatic"
                  SQLServer = $env:COMPUTERNAME
                  SQLInstanceName = "myinst"
                  EndpointHostName = $env:COMPUTERNAME
                  DependsOn = "[xSQLServerEndpoint]SQLEndpoint"
               }
           }
       
               xSQLServerAvailabilityGroupListener CreateGroupListener
               {
                  Ensure = "Present"
                  Name = "mylistener"
                  AvailabilityGroup = "myavg"
                  IpAddress = "10.1.2.62\255.255.255.0"
                  Port = 5022
                  DHCP = $false
                  NodeName = $env:COMPUTERNAME
                  InstanceName = "myinst"
                  DependsOn = "[xSQLServerAlwaysOnAvailabilityGroup]CreateAvailabilityGroup"
               }

    }

**Comment by johlju** [comment]
@iyoumans Just a tip that $env:COMPUTERNAME is evaluated when mof is compiled, not when the configuration is applied. So if you compile the mof remotely, like a client named CLIENT1, but push the configuration to server named SERVER1. Then the configuration being applied to SERVER1 will use CLIENT1 as EndpointHostName.
So when compiling the MOF, make sure it contains the correct hostname that should be used the applying the configuration. :)

**Comment by iyoumans** [comment]
Cool - thanks again!
