### ISSUE TITLE
BREAKING CHANGE: Install from ISO fails due to hardcoded reliance on Source folder

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/xSQLServer#40]
If you mount a SQL Server ISO to the disk of a machine then the SourceFolder is always set as "Source" which in the SQL Server ISO isnt a valid path

**Comment by afscrome** [comment]
You can override this by setting the SourceFolder to the empty string on the resoruce.  It does however seem very odd that the 'Sources' directory is automatically appended to the `SourcePath` parameter - surely it is the responsibility of the SourcePath to include the 'sources' directory if that is the location of the sql sources?

``` powershell
xSqlServerSetup SqlServer {
	SourcePath = "d:\"
	SourceFolder = ''
	# ..
}
```

**Comment by cwegener** [comment]
I am very interested to hear the logic behind the 'SourceFolder' attribute. I also don't quite understand why this attribute exists and why it is set to 'Source' by default.

**Comment by rolflobker** [comment]
I agree.  Empty strings should be optional. Not necessary to bypass hardcoded values. 

The use of both a Source folder and a Source path sees redundant to me.

**Comment by johlju** [comment]
After a quick glance at the code it seems that when using the parameter `SourceCredential`, then only `SourcePath` is used to mount the UNC path using `net use`.
So I think that `SourcePath` was meant to be the UNC path to the share. And `SourceFolder` was an optional folder under the share from which to `robocopy` the setup files to a temporary folder (creating the optional `SourceFolder` in the temporary folder too) on to the server which is being configured. When the files has be copied, the share is dismounted and `SourcePath` is switch to the new temporary folder, then setup is run from the joined path of both `SourcePath` and `SourceFolder`.

So I think if `net use` could be used to directly mount a folder under a share, like `\\fileserver\share\folder`, then we might be able to remove the parameter `SourceFolder`.

**Comment by rolflobker** [comment]
net use can be used to directly mount a folder under a share.
net use * \\fileserver\share\folder\otherfolder\whysomany works just fine.

Alternatively, use native powershell:
New-PSDrive -Name "sqlsetup" -PSProvider FileSystem -Root "\\server\share\folder"

**Comment by johlju** [comment]
Regarding if it necessary to create the mapping, probably not. It's using `net use` with the `SourceCredential` to logon to the UNC path. I believe if we run the resource using a credential in `PsDscRunAsCredential` then `net use` wouldn't be needed to logon to the UNC path.
But then we also need to rename `SourceCredential` parameter to `Credential` to handle PowerShell 4.0 DSC?

**Comment by johlju** [comment]
I'm working on removing `SourceFolder` parameter. In my tests it successfully connected to a folder beneath the resource when providing the entire path in `SourcePath`.
