### ISSUE TITLE
xSQLServerSetup references Setup ProcessID but doesnt capture it

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/xSQLServer#41]
In the possible variables there is a PID Variable being used that is meant to be used to capture the process for the SQL Setup.exe

However the PID variable doesn't get set properly and because of this causes the Set method to close early which then invokes the test method straight away causing it to error out

**Comment by kilasuit** [comment]
Oddly on a further run when the SQL media is extracted to the source folder as specified in #40 this runs and does correctly grab the process ID 

However I do still think that the dependency on #40 could be made to be more dynamic and allow ISO mounts instead of being hardcoded still.

**Comment by anwather** [comment]
Facing the same issue - the process is launched however the Test fails soon after.

**Comment by johlju** [comment]
This will be resolved when PR #123 is merged.
