### ISSUE TITLE
xSQLServerSetup: PrepareFailover Cluster should not pass FailoverClusterGroup

### ISSUE THREAD

**Issue by aultt** [PowerShell/xSQLServer#410]
**Details of the scenario you try and problem that is occurring:**
Unable to prepare SQL Failover Cluster instance because error:
(01) 2017-02-27 13:39:16 Slp: Exception type: Microsoft.SqlServer.Chainer.Infrastructure.InputSettingValidationException
(01) 2017-02-27 13:39:16 Slp:     Message: 
(01) 2017-02-27 13:39:16 Slp:         The setting 'FAILOVERCLUSTERGROUP' is not allowed when the value of setting 'ACTION' is 'PrepareFailoverCluster'.

**The DSC configuration that is using the resource (as detailed as possible):**
        xSQLServerSetup "PrepareMSSQLSERVER"
        {
            DependsOn = @(
                "[WindowsFeature]NET-Framework-Core",
                "[WindowsFeature]Failover-Clustering"
            )
            Action = "PrepareFailoverCluster"
            SourcePath = $Node.SourcePath
            SetupCredential = $Node.InstallerServiceAccount
            Features = $Node.Features
            InstanceName = $Node.InstanceName
            PsDscRunAsCredential = $Node.InstallerServiceAccount
        }

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows 2016, SQL 2016, 5.1
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by yardbirdsax** [comment]
I'll grab this one too since I'll be touching that code.

**Comment by johlju** [comment]
@aultt I merging a fix for this into Dev. Please test and see if it fixes your issue.
