### ISSUE TITLE
xSQLServerSetup not adding SQLSysAdminAccounts

### ISSUE THREAD

**Issue by iyoumans** [PowerShell/xSQLServer#417]
I am running xSQLServerSetup (5.0.0.0 of xSQLServer) and it works fine apart from not adding my SQL Sys Admin.  It adds the Setup Credential as an admin, but not SQLSysAdminAccounts.  Here's a snippet from my MOF, where you can see I specified the parameter:

instance of MSFT_xSQLServerSetup as $MSFT_xSQLServerSetup1ref
{
Features = "SQLENGINE,REPLICATION,FULLTEXT,SSMS,ADV_SSMS,RS";
 SQLUserDBDir = "F:\\MSSQL\\Data";
 SQLTempDBLogDir = "H:\\MSSQL\\TempDBLog";
 AgtSvcAccount = $MSFT_Credential1ref;
 SQLBackupDir = "I:\\MSSQL\\Backup";
 SetupCredential = $MSFT_Credential2ref;
 InstallSharedWOWDir = "C:\\Program Files (x86)\\Microsoft SQL Server";
 InstallSharedDir = "C:\\Program Files\\Microsoft SQL Server";
 RSSvcAccount = $MSFT_Credential3ref;
 ErrorReporting = "False";
 UpdateSource = "MU";
 SQMReporting = "False";
 BrowserSvcStartupType = "Automatic";
 InstallSQLDataDir = "F:\\MSSQL\\Data";
 ResourceID = "[xSQLServerSetup]SQL2014";
 SQLTempDBDir = "H:\\MSSQL\\TempDB";
 SQLCollation = "SQL_Latin1_General_CP1_CI_AS";
 SAPwd = $MSFT_Credential4ref;
 SourcePath = "Z:\\";
 UpdateEnabled = "True";
 SQLUserDBLogDir = "G:\\MSSQL\\Log";
 InstanceName = "MYINST";
 InstanceDir = "C:\\Program Files\\Microsoft SQL Server";
 ModuleVersion = "5.0.0.0";
 SourceInfo = "::176::13::xSQLServerSetup";
 SecurityMode = "SQL";
 SQLSysAdminAccounts = {
    "MYDOMAIN\\SQLAdminUser"
};

But here is the command line that gets run:
[[xSQLServerSetup]SQL2014] 2017-03-01_14-04-26: Starting setup using arguments: /FEATU
RES=SQLENGINE,REPLICATION,FULLTEXT,SSMS,ADV_SSMS,RS /SQLUSERDBDIR="F:\MSSQL\Data" /QUIET="True" /SQLTEMPDBLOGDIR="H:\MSSQL\TempDBLog" /AGTSV
CACCOUNT="MYDOMAIN\SQLAgentUser" /SQLBACKUPDIR="I:\MSSQL\Backup" /FTSVCPASSWORD="********" /IACCEPTSQLSERVERLICENSETERMS="True" /SECURITYMO
DE="SQL" /ACTION="Install" /AGTSVCSTARTUPTYPE="Automatic" /INSTALLSHAREDDIR="C:\Program Files\Microsoft SQL Server" /SQLSVCPASSWORD="*******
*" /RSSVCACCOUNT="MYDOMAIN\SQLReportingUser" /ERRORREPORTING="False" /UPDATESOURCE="MU" /BROWSERSVCSTARTUPTYPE="Automatic" /INSTALLSQLDATAD
IR="F:\MSSQL\Data" /SQLTEMPDBDIR="H:\MSSQL\TempDB" /SQLCOLLATION="SQL_Latin1_General_CP1_CI_AS" /SAPWD="********" /SQMREPORTING="False" /UPD
ATEENABLED="True" /SQLUSERDBLOGDIR="G:\MSSQL\Log" /INSTANCENAME="MYINST" /AGTSVCPASSWORD="********" /INSTANCEDIR="C:\Program Files\Microsof
t SQL Server" /INSTALLSHAREDWOWDIR="C:\Program Files (x86)\Microsoft SQL Server" /SQLSYSADMINACCOUNTS="MYDOMAIN\SetupInstallUser" /RSSVCPAS
SWORD="********" /FTSVCACCOUNT="MYDOMAIN\SQLSearchUser" /SQLSVCACCOUNT="MYDOMAIN\SQLServiceUser"

Looking in the code, I notice that the SQLSysAdminAccounts line is using -icontains rather than ContainsKey.  Not sure if that's the problem or not.
This is a Windows 2012 server installing SQL Server 2014, with PowerShell 5.x.

**Comment by johlju** [comment]
This should be fixed and will be in the next release on March 8:th https://github.com/PowerShell/xSQLServer/blob/dev/CHANGELOG.md#unreleased

**Comment by iyoumans** [comment]
Thanks!
