### ISSUE TITLE
xSQLServerSetup: when "<drive>:" is used as install dir it fails

### ISSUE THREAD

**Issue by dhjensen** [PowerShell/xSQLServer#418]
**Details of the scenario you try and problem that is occurring:**
I want to install Instancedir and instancesqldatadir to a drive root. From the config below:
InstanceDir = "M:"
InstallSQLDataDir = "M:"

It produce an installer arg list that is "wrong":

> Slp: Value specified: M:" /SQLUSERDBDIR=D:\MSSQL13.MSSQLSERVER\MSSQL\Data /AGTSVCSTARTUPTYPE=Automatic /IACCEPTSQLSERVERLICENSETERMS=True /SQLTEMPDBLOGDIR=T:\MSSQL13.MSSQLSERVER\MSSQL\Data /INSTALLSHAREDWOWDIR=C:\Program,Files,(x86)\Microsoft,SQL,Server /QUIET=True /INSTANCENAME=MSSQLSERVER /SQLBACKUPDIR=M:\MSSQL13.MSSQLSERVER\MSSQL\Data /SQLUSERDBLOGDIR=L:\MSSQL13.MSSQLSERVER\MSSQL\Data /SQLSYSADMINACCOUNTS=xxx\administrator /SQLTEMPDBDIR=T:\MSSQL13.MSSQLSERVER\MSSQL\Data /FEATURES=SQLENGINE /INSTALLSQLDATADIR=M: /INSTALLSHAREDDIR=C:\Program,Files\Microsoft,SQL,Server  /ACTION=Install

**The DSC configuration that is using the resource (as detailed as possible):**
          
xSqlServerSetup ($Node.NodeName)
{
               
               SourcePath = $Node.SourcePath
               
               SetupCredential = $Node.InstallerServiceAccount
               InstanceName = $Node.InstanceName
               Features = $Node.Features
               SQLSysAdminAccounts = $Node.AdminAccount
               InstallSharedDir = "C:\Program Files\Microsoft SQL Server"
               InstallSharedWOWDir = "C:\Program Files (x86)\Microsoft SQL Server"
               InstanceDir = "M:"
               InstallSQLDataDir = "M:"
               SQLUserDBDir = "D:\MSSQL13." + $Node.InstanceName + "\MSSQL\Data"
               SQLUserDBLogDir = "L:\MSSQL13." + $Node.InstanceName + "\MSSQL\Data"
               SQLTempDBDir = "N:\MSSQL13." + $Node.InstanceName + "\MSSQL\Data"
               SQLTempDBLogDir = "N:\MSSQL13." + $Node.InstanceName + "\MSSQL\Data"
               SQLBackupDir = "M:\MSSQL13." + $Node.InstanceName + "\MSSQL\Backup"
               
}

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2016, SQL Server 2016
WMF 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
5.0.0.0

**Comment by johlju** [comment]
I see another problem too

```
InstallSharedDir = "C:\Program Files\Microsoft SQL Server"
InstallSharedWOWDir = "C:\Program Files (x86)\Microsoft SQL Server"
```

returns

```
/INSTALLSHAREDWOWDIR=C:\Program,Files,(x86)\Microsoft,SQL,Server /QUIET=True /INSTALLSHAREDDIR=C:\Program,Files\Microsoft,SQL,Server /ACTION=Install
```

There should not be commas in these paths, and probably need to be double quotes around them too.

**Comment by johlju** [comment]
@dhjensen I solved the problem with InstanceDir and InstallSQLDataDir could not be set to just a qualifier (PR #418).
But I could not replicate the comma problem with the Dev version. So that must have been fixed in the current Dev version! :)

I will try to merge this in a day or so, so this can be in the release on the 8th. Thanks for reporting this issue!
