### ISSUE TITLE
xSQLServer requires refactoring to reduce need on xPDT & xSQLServerHelper

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/xSQLServer#42]
Looking at the xSQLServerSetup there is alot of reliance on helper functions that are included in here that very much look like they were built for PowerShell v2

Is there still any real requirement to use these helper modules?

**Comment by aultt** [comment]
Yes xSQLServerHelper is utilized for many of the AlwaysOn functionality.  xPDT is there from first iteration and has some nice error handling which would be nice to utilize.  I dont see phasing it out but rather adding to it and utilizing more.
