### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership: New Resource

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/xSQLServer#425]
**Details of the scenario you try and problem that is occurring:**
Manage the databases that are members of availability groups

```
xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership
{
	[DatabaseName = [string[]]] # Array of database names to add to the availability group. Wildcards are supported.
	SQLServer = [string]
	SQLInstanceName = [string]
	AvailabilityGroup = [string]
	[BackupPath = [string]] # UNC path that is accessible by both the primary and secondary instances. This is required if the seeding mode of the Availability Group Replica is Manual. This is always required for SQL 2012 and 2014.
	[Ensure = [string]{ Absent | Present }] # Defaults to Present
	[MatchDatabaseOwner = [switch]{ $true }] # Ensures the database owner on the secondary matches the owner on the primary. PsDscRunAsCredential must have impersonate rights to run as the database owner in order to perform the database restore. The database owner must exist on all instances.
}
```

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
SQL Server 2012, 2014, 2016

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by randomnote1** [comment]
I plan on working on this next. I'm thinking of writing this as a class-based resource. Any comments or concerns before I get rolling?

**Comment by johlju** [comment]
No comments, looks good to me. And class-based should be all good (don't know if we have to tweak AppVeyor testing maybe). Go for it. 😄

**Comment by randomnote1** [comment]
One thing I've identified that will be significantly different is the help file. As it stands now, we do comment-based help in every resource. With the class-based resource I need to create module-based help using .help files.

Quite frankly, we should consider doing this for the project rather than using comment-based help so the end user can utilize the help without cracking open the script.

**Comment by johlju** [comment]
Comment-based help is requirement for the .mof resources to align with the guideline and HQRM. If we can get as close as possible to that with a class-based resource that would be good.
This is new territory, don't know if any module has a class-based resource yet. So we just have to do what we think is best and go from there :smile: 

I did not know about the .help files. I can't find any documentation on it, do you have a link?

Also it seems it could be comment-based help for class-based resource in the (distant) future:
https://github.com/PowerShell/PowerShell issue 2225

Regarding doing this for the the entire project, I don't know. That would mean yet another place to have the parameter description for a .mof resource.
Currently there are in the comment-based help, in the .schema.mof file, and in the README.md. README.md hopefully will be removed soon when we can start using the wiki, like xNetworking and SharePointDsc.

**Comment by randomnote1** [comment]
Makes sense. It just seems odd that we're writing help in a location that is not helpful for the end user to get to. Maybe I'm missing something too.

Here's the link for the .help files. 
https://msdn.microsoft.com/en-us/library/dd878343(v=vs.85).aspx

I'm all about getting rid of duplicated effort! I'd love to see the help removed from the psm1 files, especially since the help is already in the schema.mof files. That would make the .psm1 files much smaller and much more manageable. :)

**Comment by johlju** [comment]
Yes, I agree that adding the same information in two (and currently three) locations are to many. I could write a issue in DscResources to query about the guideline of comment-based help.

**Comment by randomnote1** [comment]
Thanks @johlju , I appreciate you raising the question!

**Comment by randomnote1** [comment]
Apparently a class-based resource cannot be mixed with a MOF-based resource. :( I'm starting to convert it to  MOF-based resource now.

**Comment by johlju** [comment]
Oh! :/ How do you mean? Because of the module as a whole is MOF its not possible to compile a configuration? 

That is to bad, I was looking forward having the first class based resource :)

**Comment by randomnote1** [comment]
I can't get the module to recognize a class-based resource exists until I remove all of the MOF based resources. I didn't even try to compile a configuration because it didn't see the resource when I did a Get-DscResource.

**Comment by johlju** [comment]
Okay! That doesn't seem good, then we can never have class-based resources unless creating a new module. :/

@kwirkykat and @mbreakey3 is this the case? Or is there something missing to get mof and class-based to work together?

**Comment by mbreakey3** [comment]
Yes, this is the case. Currently you can't have both mof and class-based resources in the same module.

**Comment by kwirkykat** [comment]
I'm pretty sure you can have both in the same module. We were considering adding WindowsPackageCab to xPSDesiredStateConfiguration as a class-based resource. We didn't because that would require xPSDSC to require WMF 5.0.

@randomnote1 What have you tried? Did you add the class-based resource to the 'DscResourcesToExport' field in the module manifest? If that field does not exist in the module manifest, you will need to add it for the class-based resources.

**Comment by mbreakey3** [comment]
My mistake, yes, you should be able to have them in the same module. The main issue we've faced with adding class-based resources to our current modules is their dependency on WMF 5.0 and the fact that they require a different testing format than what we currently use.

**Comment by kwirkykat** [comment]
@mbreakey3 @johlju @randomnote1 
@nitinbps just tried out having a module with both a mof-based resource and a class-based resource and it worked. That was with WMF 5.1 and it worked for both Get-DscResource and compiling a configuration.

There are a couple problems that you may be running into:
- You have to have the DSCResourcesToExport field in your manifest with the value as a list of the names of all your class-based resources to export.
- You must be running at least WMF 5.0. The DSCResourcesToExport field will cause a parsing error on WMF 4 or older. The module manifest should also be updated to require at least WMF 5.0 because of this.
- Your mof-based resources must reside in a folder called 'DscResources' within your module. This is how they are discovered. (Your class-based resources can also reside in this folder. This should not cause discovery issues since they do not have mof files.)

**Comment by randomnote1** [comment]
@kwirkykat , you made my day!

I was able to get the class-based resource to return using `Get-DscResource -xSQLServer`, but only if I ran `Import-Module xSQLServer` first. This is likely because the module has to load the SMO assemblies first.

The other thing I found is that I have to reference the .psm1 file the class is in directly using the RootModule property. This was the missing piece. Did you have similar findings?

Here's the psd1 in question:
https://github.com/randomnote1/xSQLServer/blob/xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership/xSQLServer.psd1

**Comment by randomnote1** [comment]
I was able to get Get-DscResource -xSQLServer to display the class-based resource if I remove all explicit references to types defined in the SQL SMO objects. This makes sense technically, but I believe it makes the code a little less clean. More to come.

**Comment by johlju** [comment]
@randomnote1 Great that you have gotten further with this! 

It would have been nice if `using namespace` could actually load the assembly too, but that .
http://info.sapien.com/index.php/scripting/scripting-classes/import-powershell-classes-from-modules

But could you use `using module xSQLServer` to load the SQL SMO objects? When the `RequiredAssemblies` property has the correct assemblies? Just guessing here.

**Comment by randomnote1** [comment]
Yeah, it's a shame that `using namespace` didn't do the trick. It looks like `using module` also has the same limitation where it doesn't load the assemblies when running `Get-DscResource`.

I have a workaround in place that will check the object type in the method body rather than at the parameter level. It's not pretty, but it allows everything to work as expected.

**Comment by johlju** [comment]
@randomnote1 I see in the current proposed resource in PR #593 you have Ensure parameter as three different values; Present, Absent **and Exactly**. This is entirely different of how Ensure is used all over the DSC Resource Kit. And and in help.txt file you say about the value `Exactly` of the `Ensure` parameter "The availability group member database(s) are added and removed until they match the defined databases.".
Ensure parameter should be used, in this case, if a database should be present or absent from the availability group. Ensure is always used over DSC Resource Kit as Present = Create/Add, Absent = Delete/Remove. Adding another value to this parameter would be, I think, confusing.

I would rather see three parameters `DatabaseName`, `DatabaseNameToInclude` and `DatabaseNameToExclude`. Each parameter can take one or more databases (including wildcards). Where `DatabaseName` cannot be used at the same time as `DatabaseNameToInclude` and `DatabaseNameToExclude`.
When `DatabaseName` is set to one or more database names then the same logic is applied as the current proposed `Exactly` value of `Ensure` parameter. That is "only these, an no other databases".
The other to parameters `DatabaseNameToInclude` and `DatabaseNameToExclude` will add and/or remove databases from the availability group.
In this case the `Ensure` parameter might not be needed at all.

**Comment by randomnote1** [comment]
Sounds like a plan to me. I'll work on re-factoring that. With any luck it won't require too much in code change :)

**Comment by johlju** [comment]
Awesome! I continue the review in the meanwhile.
