### ISSUE TITLE
xSQLServerSetup: Should be set xPDT.strings on root directory

### ISSUE THREAD

**Issue by tsubasaxZZZ** [PowerShell/xSQLServer#443]
**Details of the scenario you try and problem that is occurring:**
I tried xSQLServerSetup but cannot execute following error:

> PowerShell DSC リソース MSFT_xSQLServerScript は Set-TargetResource 機能を実行できませんでした。
> 
> モジュール MSFT_xSQLServerSetup のインポートが失敗しました。エラー: ディレクトリ 'C:\Program Files\WindowsPowerShell\Modules\xSQLServer\6.0.0.0\ja-JP\' または親のカルチャ ディレクトリに Windows PowerShell
>  データ ファイル 'xPDT.strings.psd1' が見つかりません。
>     + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) []、CimException
>     + FullyQualifiedErrorId : ImportModuleFailed
>     + PSComputerName        : VM4

This means, couldn't find 'xPDT.strings.psd1' in ja-JP directory.

**!!!! So should be set 'xPDT.strings.psd1' on root directory. !!!!**

**The DSC configuration that is using the resource (as detailed as possible):**
```
        xSQLServerSetup setup {
            SetupCredential = $credential
            InstanceName = "test0314"
            DependsOn = "[WindowsFeature]NET-Framework-core"
            SourcePath = "C:\SQLServer"
            ForceReboot = $true
            Features = "SQLEngine,BC,Conn"
            SQLSysAdminAccounts = "corp.contoso.com\tsunomur"
        }
```
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
OS : Windows Server 2016
SQL Server : SQL Server 2016
PowerShell:

> PS C:\temp\setupsqlser> $PSVersionTable
> 
> Name                           Value                                                                                                                            
> ----                           -----                                                                                                                            
> PSVersion                      5.1.14393.693                                                                                                                    
> PSEdition                      Desktop                                                                                                                          
> PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                          
> BuildVersion                   10.0.14393.693                                                                                                                   
> CLRVersion                     4.0.30319.42000                                                                                                                  
> WSManStackVersion              3.0                                                                                                                              
> PSRemotingProtocolVersion      2.3                                                                                                                              
> SerializationVersion           1.1.0.1                                                                                                                          
> 
> 

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
> PowerShell      xSQLServerSetup           xSQLServer                     6.0.0.0

**Comment by johlju** [comment]
@tsubasaxZZZ thanks for reporting this!

It seems that it is this [row](https://github.com/PowerShell/xSQLServer/blob/dev/xPDT.psm1#L1) in the file xPDT.psm1 that has a bug in it.

It is:
```
Import-LocalizedData LocalizedData -filename xPDT.strings.psd1
```

But should be:
```
Import-LocalizedData LocalizedData -filename xPDT.strings.psd1 -ErrorAction SilentlyContinue
```

Another solution would be to create a folder 'ja-JP' in root folder and then copy the files from the 'en-US' folder to the newly created 'ja-JP' folder (and optionally translate the strings to Japanese).

If you do translate the strings, then please feel free to send in a pull request with the changes.

**Comment by luigilink** [comment]
Same issue here, but for French 😄 
Issue ref: #153

**Comment by johlju** [comment]
In PR #578 xPDT-files will be remove altogether. So this this particular problem will not be an issue anymore. But maybe there is the same problem in the localization for xSQLServer.strings.psd1? 

Let's keep this issue open until we get the correct localization for this module and this resource in particular. This will be the next thing I will be working on after merging #578 (that, and integration tests).

**Comment by johlju** [comment]
@tsubasaxZZZ Localization has been added for xSQLServerSetup and the helper functions (xSQLServerhelper). When the next release is released (in July I think), you should no longer get this issue. 

And if you would like to contribute the Japanese localization strings that would be great 😄 But that is a separate issue. 

I will close this issue now. Thank you for reporting this!
