### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroup & xSQLServerAlwaysOnAvailabilityGroupReplica: Create helper function to check cluster permissions

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/xSQLServer#446]
**Details of the scenario you try and problem that is occurring:**
Code is duplicated in xSQLServerAlwaysOnAvailabilityGroup and xSQLServerAlwaysOnAvailabilityGroupReplica for testing the permissions on the cluster. Need to create a help function to reduce code duplication.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
All

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by randomnote1** [comment]
I'm working this one

**Comment by johlju** [comment]
Thanks @randomnote1! Labeled as in progress.
