### ISSUE TITLE
xSqlServerAlwaysOnAvailabilityGroup -  'Invoke-Query' is not recognized 

### ISSUE THREAD

**Issue by joshan1120** [PowerShell/xSQLServer#447]
I am trying to use the xSqlServerAlwaysOnAvailabilityGroup resource and am running into the following error and cannot find any info on the cause. Does anyone have any ideas?

This is on SQL2014 on a Windows 2012R2 server.

## **Here is the resource**

xSQLServerAlwaysOnAvailabilityGroup ensureCreated 
        {
            Name = $environmentNode.AvailabilityGroupName
            SqlServer = $env:COMPUTERNAME
            SqlInstanceName = $environmentNode.sqlInstanceName
            AutomatedBackupPreference = $roleNode.AutomatedBackupPreference
            AvailabilityMode = $roleNode.primaryAvailabilityMode
            ConnectionModeInPrimaryRole = $roleNode.ConnectionModeInPrimaryRole
            ConnectionModeInSecondaryRole  = $roleNode.ConnectionModeInSecondaryRole
            FailoverMode = $roleNode.primaryFailoverMode
            PsDscRunAsCredential = $LocalAdminCreds
            DependsOn = "[xSQLServerPermission]setPerms"

        }

**## This is the stack trace**

ERBOSE: [TESTPRIMARY]: LCM:  [ Start  Set      ]  [[xSQLServerAlwaysOnAvailabilityGroup]ensureCreated]
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroup]ensureCreated] SQLPS module changes CWD to SQLSERVER:\ when loading, pushing location to pop it when module is loaded.
VERBOSE: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroup]ensureCreated] 2017-03-17_15-13-05: Importing SQLPS module.
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroup]ensureCreated] SQLPS module imported.
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroup]ensureCreated] Popping location back to what it was before importing SQLPS module.
VERBOSE: [TESTPRIMARY]:                            [[xSQLServerAlwaysOnAvailabilityGroup]ensureCreated] 2017-03-17_15-13-05: Connected to SQL TESTPRIMARY\test
The term 'Invoke-Query' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Invoke-Query:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost
 
The term 'Invoke-Query' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    + CategoryInfo          : ObjectNotFound: (Invoke-Query:) [], CimException
    + FullyQualifiedErrorId : CommandNotFoundException
    + PSComputerName        : localhost

**Comment by johlju** [comment]
Seems that SQLPS is not loaded correctly so it can't find the cmdlet Invoke-Query. It do seem to load SQLPS correctly. Could you verify that the module exist on the node being configured, and that you can call Invoke-Query on the node?

**Comment by johlju** [comment]
My bad, I was thinking of the Invoke-Sqlcmd in SQLPS. Invoke-Query in a helper function. 
Very strange it can't find that! It should exist in he module file xSQLServerHelper.psm1 in the root of the module. And that is loaded at the start of the resource module you are using. 

What version of the xSQLServer are you using?

**Comment by joshan1120** [comment]
ahh let me update that, good call!!! I am not running the full package as I have a few customized resources.

**Comment by randomnote1** [comment]
Yup, Invoke-Query was added in v6 with the addition of that resource.

**Comment by johlju** [comment]
@joshan1120 Did that solve your problem? Labeling this as question for the time being.

**Comment by joshan1120** [comment]
Yes that resolved the issue thanks!!!

Now working through why when it adds instance name it is not putting in the slash looking now.

PowerShell DSC resource MSFT_xSQLServerAlwaysOnAvailabilityGroup  failed to execute Set-TargetResource functionality with error message: No database mirroring endpoint was found on 'TestPrimarytest'.


xSQLServerAlwaysOnAvailabilityGroup ensureCreated 
        {
            Name = $environmentNode.AvailabilityGroupName
            SqlServer = "TestPrimary"
            SqlInstanceName = "test"
            AutomatedBackupPreference = $roleNode.AutomatedBackupPreference
            AvailabilityMode = $roleNode.primaryAvailabilityMode
            ConnectionModeInPrimaryRole = $roleNode.ConnectionModeInPrimaryRole
            ConnectionModeInSecondaryRole  = $roleNode.ConnectionModeInSecondaryRole
            FailoverMode = $roleNode.primaryFailoverMode
            PsDscRunAsCredential = $LocalAdminCreds
            DependsOn = "[xSQLServerPermission]setPerms"

        }

**Comment by joshan1120** [comment]
Figured it out, I am required to set the endpoint first. AO Group created. Thanks for the help!!
