### ISSUE TITLE
MSFT_xSQLServerAvailabilityGroupListener - Trying to make a change to a listener that does not exist. 

### ISSUE THREAD

**Issue by joshan1120** [PowerShell/xSQLServer#449]
Sorry to be a pain :)

Trying to figure out why I cannot create a Listener with the script and the error messages are not helping me much. Any ideas or anyone seen this before? I am able to create the listener with the same settings without any issues inside of SSMS.

## **Parameters:**

xSQLServerAvailabilityGroupListener addListener
	{
		AvailabilityGroup = $environmentNode.AvailabilityGroupName
		InstanceName = $environmentNode.sqlInstanceName
		NodeName = $env:COMPUTERNAME
		Name = $environmentNode.listenerName
		IpAddress = $environmentNode.listenerIP
		Port = $environmentNode.listenerPort
            	PsDscRunAsCredential = $LocalAdminCreds
            	DependsOn = "[xSQLServerAlwaysOnAvailabilityGroup]ensureCreated"
	}

## **Stack Trace:**

DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] ItemExists: SQLSERVER:\SQL\TESTPRIMARY\test
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] Connecting to Microsoft.SqlServer.Management.PSProvider\SqlServer::SQLSERVER:\SQL\TESTPRIMARY\test\AvailabilityGroups\MS-WE-INF-AO-AG\AvailabilityGr
oupListeners as NT AUTHORITY\SYSTEM
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] ItemExists: SQLSERVER:\SQL\TESTPRIMARY\test\AvailabilityGroups\MS-WE-INF-AO-AG\AvailabilityGroupListeners
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] Get property 'AvailabilityGroups' from 'Server' object '[TESTPRIMARY\test]'
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] Query object: Server/AvailabilityGroup[@Name = 'MS-WE-INF-AO-AG']
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] succesful. 00:00:00.0090757
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] Get property 'AvailabilityGroupListeners' from 'AvailabilityGroup' object '[MS-WE-INF-AO-AG]'
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] GetChildItems(SQLSERVER:\SQL\TESTPRIMARY\test\AvailabilityGroups\MS-WE-INF-AO-AG\AvailabilityGroupListeners, recurse=False)
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] Query object: Server/AvailabilityGroup[@Name = 'MS-WE-INF-AO-AG']/AvailabilityGroupListener
DEBUG: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] Query finished. 00:00:00.0121462
VERBOSE: [TESTPRIMARY]:                            [[xSQLServerAvailabilityGroupListener]addListener] 2017-03-20_11-05-10: Listener MS-WE-INF-AO-LS does not exist
VERBOSE: [TESTPRIMARY]: LCM:  [ End    Set      ]  [[xSQLServerAvailabilityGroupListener]addListener]  in 2.4100 seconds.
PowerShell DSC resource MSFT_xSQLServerAvailabilityGroupListener  failed to execute Set-TargetResource functionality with error message: Trying to make a change to a listener that does not exist.

**Comment by joshan1120** [comment]
ok wow, embrassing...

ensure = "present" is my friend

**Comment by johlju** [comment]
@joshan1120 I'm happy that you ask question. Happy that you are using the resource!

I think we should have Ensure default to 'Present'. I'm fixing a issue for that.
