### ISSUE TITLE
xSQLAOGroupJoin - failed to execute Set-TargetResource functionality with error message: Unable to Join

### ISSUE THREAD

**Issue by joshan1120** [PowerShell/xSQLServer#451]
I know I am probably just missing something dumb and it is not a bug. But it works fine from SSMS direct.

A little backgrounds which may help to diagnose what my issues is. If I remove the PsDscRunAsCredential line in the params I can see it hit the secondary node, but it fails login as it uses the primary machine name. This leads me to believe it is a permissions issue, but the cluster service and system are both SA. Nothing gets written to logs.

**## Here are the Params:**

foreach ($secondary in $environmentNode.secondaryNodes) {
		xSQLAOGroupJoin "addSecondariesToAoGroup$($secondary)"
		{
			Ensure = "Present"
			AvailabilityGroupName = $environmentNode.AvailabilityGroupName
			SQLServer = $secondary
			SQLInstanceName = $environmentNode.sqlInstanceName
			SetupCredential = $LocalAdminCreds
                        PsDscRunAsCredential = $LocalAdminCreds
			DependsOn = "[xSQLServerAvailabilityGroupListener]addListener"
		}
}

## **Here is the stack:**

VERBOSE: [TESTPRIMARY]: LCM:  [ Start  Set      ]  [[xSQLAOGroupJoin]addSecondariesToAoGroupTestSecondary]
VERBOSE: [TESTPRIMARY]:                            [[xSQLAOGroupJoin]addSecondariesToAoGroupTestSecondary] 2017-03-20_13-10-40: Connected to SQL TestSecondary\test
VERBOSE: [TESTPRIMARY]:                            [[xSQLAOGroupJoin]addSecondariesToAoGroupTestSecondary] 2017-03-20_13-10-40: Connected to SQL TestSecondary\test
VERBOSE: [TESTPRIMARY]:                            [[xSQLAOGroupJoin]addSecondariesToAoGroupTestSecondary] 2017-03-20_13-10-40: Granted Permissions to NT AUTHORITY\SYSTEM
VERBOSE: [TESTPRIMARY]: LCM:  [ End    Set      ]  [[xSQLAOGroupJoin]addSecondariesToAoGroupTestSecondary]  in 0.6960 seconds.
PowerShell DSC resource MSFT_xSQLAOGroupJoin  failed to execute Set-TargetResource functionality with error message: Unable to Join  on TestSecondary\test

**Comment by joshan1120** [comment]
Here it is in easier to read format. I removed the loop and populated the variables.

I am running it on the primary which is server name "TestPrimary"

xSQLAOGroupJoin addSecondariesToAoGroup
			{
				Ensure = "Present"
				AvailabilityGroupName = "MS-WE-INF-AO-AG"
				SQLServer = "TestSecondary"
				SQLInstanceName = "test"
				SetupCredential = $LocalAdminCreds
                PsDscRunAsCredential = $LocalAdminCreds
}

Same error.

**Comment by joshan1120** [comment]
I think I see my issue, now I just have to figure out how to work through it. In nutshell, I am running everything as node = localhost. I was able to make this work for all my other resources (cluster, and all other SQL resources) but for the secondary node it seems to be trying to add it from the secondary node when I set that as SQLName, but it needs to do the add on the primary.

Primary replica = TestPrimary
Secondary replica - TestSecondary

I am able to run this without any issue on the primary
New-SqlAvailabilityReplica 
-Name "TestSecondary\test" 
-EndpointUrl "TCP://TestPrimary:5022" 
-FailoverMode Manual 
-AvailabilityMode synchronousCommit 
-ConnectionModeInSecondaryRole AllowAllConnections 
-Path "SQLSERVER:\Sql\TestPrimary\test\AvailabilityGroups\MS-WE-INF-AO-AG"

Here is my test config. I have most thing pulled out of the psd1 file as I been testing. (formatting gets messed up on the copy and paste)

Configuration test
{
	param (
		[string] $vmName,
		[string] $environment,
		[string] $role,

		[Parameter(Mandatory=$true)]
        [ValidateNotNullorEmpty()]
        [PsCredential] $azureCredential
	)

	Import-DscResource -ModuleName AonFailOverCluster
	Import-DscResource -ModuleName AonSqlServerModule
	Import-DscResource -ModuleName AzureRM.KeyVault -ModuleVersion 2.4.0
    Import-DscResource -ModuleName xSqlServerAlwaysOn
    Import-DscResource -ModuleName PSDesiredStateConfiguration

	$nonNodeData = $ConfigurationData.NonNodeData
    $roleNode = $ConfigurationData.Role.Where({$_.Role -eq $role})
	$environmentNode = $ConfigurationData.Environment.Where({$_.Environment -eq $environment})
	$subscriptionId = $nonNodeData.subscriptionId
    $tenantId = $nonNodeData.tenantId

	$vaultName = $environmentNode.vaultName
	$DomainAccountPw = (Get-AzureKeyVaultSecret -VaultName $vaultName -Name $nonNodeData.domainAccountSecretName).SecretValue
	$DomainAccountCreds = New-Object System.Management.Automation.PSCredential("$($environmentNode.domainName)\$($nonNodeData.domainAccountUserName)", $DomainAccountPw)
	$LocalAdminPw = (Get-AzureKeyVaultSecret -VaultName $vaultName -Name $nonNodeData.localAccountSecretName).SecretValue
	$LocalAdminCreds = New-Object System.Management.Automation.PSCredential("$($environmentNode.domainName)\$($nonNodeData.localAdminUserName)", $LocalAdminPw)

	Login-AzureRmAccount -Credential $azureCredential -TenantId $tenantId -ServicePrincipal


	Node ("localhost")
	{
		LocalConfigurationManager {
			ActionAfterReboot = 'ContinueConfiguration'
			ConfigurationMode = 'ApplyOnly'
			RebootNodeIfNeeded = $true
			AllowModuleOverwrite = $true
		}

		Cluster ensureCreated
        {
            Name = $environmentNode.clusterName
            StaticIPAddress = $environmentNode.clusterIP
            Servers = $environmentNode.clusterNodes
            DomainAdministratorCredential = $DomainAccountCreds
            PsDscRunAsCredential = $LocalAdminCreds		
	    }
		
		WaitForCluster waitForCluster
        {
            Name = $environmentNode.clusterName
            RetryIntervalSec = 10
            RetryCount = 60
			DependsOn = "[Cluster]ensureCreated"
		}

		ClusterQuorum createWitnessShare
		{
			IsSingleInstance = "yes"
			Type = $environmentNode.quorumType
			Resource = $environmentNode.witnessShare
		}

        # Set Preferred CLuster Host Owners
		$AG = $environmentNode.availabilityGroupName
		$HA = $environmentNode.haNodes
		Script setOwners {
			GetScript = {
				GetScript = {@{Result = Get-ClusterOwnerNode -Group $using:AG}}
			}
			SetScript = {
				Set-ClusterOwnerNode -Owners $using:HA -Group $using:AG
			}
			TestScript = {
				$test = Get-ClusterOwnerNode -Group $using:AG
				If ($test.OwnerNodes.Name -like $using:HA[1]) {Write-output $true}
				else
				{Write-output $false}
			}
			DependsOn = "[WaitForCluster]waitForCluster"
		}

	foreach ($server in $environmentNode.clusterNodes) {
            xSQLServerAlwaysOnService "enableAO$($server)"
            {
                Ensure = "Present"
                SQLInstanceName = $environmentNode.sqlInstanceName
                SQlServer = $server
                PsDscRunAsCredential = $LocalAdminCreds
            }
        }

	# Adding the required service account to allow the cluster to log into SQL
        xSQLServerLogin AddNTServiceClusSvc
        {
            Ensure = "Present"
            Name = "NT SERVICE\ClusSvc"
            LoginType = 'WindowsUser'
            SQLServer = "TestPrimary"
            SQLInstanceName = $environmentNode.sqlInstanceName
            PsDscRunAsCredential = $LocalAdminCreds
			DependsOn = "[Cluster]ensureCreated"
        }
		
		# Add the required permissions to the cluster service login
		xSQLServerPermission setPerms
		{
			Ensure = "Present"
			NodeName = $env:COMPUTERNAME
			InstanceName = $environmentNode.sqlInstanceName		
			Principal = 'NT SERVICE\ClusSvc'
			Permission = $roleNode.aoPermissions
			PsDscRunAsCredential = $LocalAdminCreds
			DependsOn = '[xSQLServerLogin]AddNTServiceClusSvc'
		}

	#Create a DatabaseMirroring endpoint
        xSQLServerEndpoint HADREndpoint
        {
            EndPointName = 'HADR_endpoint'
            Ensure = 'Present'
            Port = 5022
            AuthorizedUser = "Dev2i\svc-WinServerFA1"
            SQLServer = "TestPrimary"
            SQLInstanceName = "test"
            DependsOn = "[xSQLServerPermission]setPerms"
        } 

	# Create the availability group on the instance tagged as the primary replica
        xSQLServerAlwaysOnAvailabilityGroup ensureCreated 
        {
            Name = $environmentNode.AvailabilityGroupName
            SqlServer = "TestPrimary"
            SqlInstanceName = $environmentNode.sqlInstanceName
            AutomatedBackupPreference = $roleNode.AutomatedBackupPreference
            AvailabilityMode = $roleNode.primaryAvailabilityMode
            ConnectionModeInPrimaryRole = $roleNode.ConnectionModeInPrimaryRole
            ConnectionModeInSecondaryRole  = $roleNode.ConnectionModeInSecondaryRole
            FailoverMode = $roleNode.primaryFailoverMode
            EndpointHostName = "TestPrimary.Dev2i.Azure.aon.net"
            PsDscRunAsCredential = $LocalAdminCreds
            DependsOn = "[xSQLServerEndpoint]HADREndpoint"
        }

        xSQLServerAvailabilityGroupListener addListener
		{
            ensure = "Present"			
            AvailabilityGroup = $environmentNode.AvailabilityGroupName
			InstanceName = $environmentNode.sqlInstanceName
			NodeName = $env:COMPUTERNAME
			Name = $environmentNode.listenerName
			IpAddress = $environmentNode.listenerIP
			Port = $environmentNode.listenerPort
            DependsOn = "[xSQLServerAlwaysOnAvailabilityGroup]ensureCreated"
	}

	xSQLAOGroupJoin addSecondariesToAoGroup
		{
		Ensure = "Present"
		AvailabilityGroupName = "MS-WE-INF-AO-AG"
		SQLServer = "TestPrimary"
		SQLInstanceName = "test"
		SetupCredential = $LocalAdminCreds
                PsDscRunAsCredential = $LocalAdminCreds
		DependsOn = "[xSQLServerAvailabilityGroupListener]addListener"
	}
}	
}

$clientId = "xxxx"
$password =  ConvertTo-SecureString "xxxx" -AsPlainText -Force
$psCred = New-Object System.Management.Automation.PSCredential($clientId, $password)

test -vmName localhost -role AlwaysOnCluster -environment infra -azureCredential $psCred -ConfigurationData $configData
start-DscConfiguration test -Wait -Force -Debug

**Comment by johlju** [comment]
@joshan1120 Yeah, I don't think you can get that to work honestly. :/ That resource lack the functionality to find the primary replica. There is currently a new resource in PR #424 (`xSQLServerAlwaysOnAvailabilityGroupReplica`) that will do that, and you could test that resource instead. You can find it in the contributors working branch. Hopefully we get it merged into the Dev branch shortly.
If you need to use a released version then you will have to wait until v7.0 is released (it should be merged into Dev before then). 

And a side note, if you use ``` before and after the code, you get a codeblock, and you will get proper formatting. :)

**Comment by johlju** [comment]
xSQLAOGroupJoin will be deprecated when the new resource is merged.

**Comment by joshan1120** [comment]
I just used the new resource and it worked!!! I grabbed his pull request to test it. Nice work @randomnote1

**Comment by randomnote1** [comment]
Thanks! I'm working on making the tests a little bit more robust, and should have the pull request completed shortly.
