### ISSUE TITLE
xSQLServerSetup: Unable to map the specified paths to valid cluster storage.

### ISSUE THREAD

**Issue by rbg21** [PowerShell/xSQLServer#484]
**Details of the scenario you try and problem that is occurring:**
xSQLServerSetup - module
When trying to create a cluster using attached storage, I receive the following error.

PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Set-TargetResource 
functionality with error message: Unable to map the specified paths to valid cluster storage. 
Drives mapped:

This error seems to occur on the root lun that holds the other luns. 

When I jumped into the setup resource it looks to stop at:
$clusterSharedVolumes = Get-CimInstance -ClassName 'MSCluster_ClusterSharedVolume' -Namespace 'root/MSCluster'.

Everything works fine using the GUI for SQL cluster install.  

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows2012
PS 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Version: 6.0.0.0 (master)
xSQLServerSetup

**Comment by johlju** [comment]
Could you provide us with your configuration script? Stripped of any sensitive information? 

Also, what does `Get-CimInstance -ClassName 'MSCluster_ClusterSharedVolume' -Namespace 'root/MSCluster'` return? 
And what should `Get-CimInstance` return? What disks should it return?

**Comment by johlju** [comment]
It looks like it throw at [line 1024](https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L1024) so it looks like it does not find any shared disk.

Another question.
The disks, are they Cluster Shared Volumes or regular shared disk (LUN)? (I see you wrote LUN's above, just want to make sure)
Are you using mountpoints?

**Comment by rbg21** [comment]
I get nothing when running Get-CimInstance -ClassName 'MSCluster_ClusterSharedVolume' -Namespace 'root/MSCluster' 

So we have a root W drive that is a LUN then we have a folder structure of SQL\binaries(which is another lun set as a mount point to that folder), as well as a data and logs folder that has a common and lg_common luns as mount points. 

xSQLServerSetup ($Node.NodeName)
            {
                Action  = "InstallFailoverCluster"
                InstanceName  = "MSSQLSERVER"
                SetupCredential = $Credential
                SourcePath  = "c:\users\public\downloads\sql2016\source\" 
                Features  = "SQLENGINE, REPLICATION, FULLTEXT, DQ"
                InstanceID  = "MSSQLSERVER"
                UpdateEnabled  = "True"
                UpdateSource  = "MU"
                InstallSharedDir  = "c:\Program Files\Microsoft SQL Server\"
                InstallSharedWOWDir  = "c:\Program Files (x86)\Microsoft SQL Server\"
                InstanceDir  = "C:\Program Files\Microsoft SQL Server\"
                SQLSvcAccount  = $SQLSvcAccount
                AgtSvcAccount  = $AgtSvcAccount
                SQLCollation  = "SQL_Latin1_General_CP1_CI_AS"
                SQLSysAdminAccounts   = "$SQLAdmin"
                SecurityMode  = "SQL"
                SAPwd  = $SACreds
                InstallSQLDataDir  = "W:\sql\binaries"
                SQLUserDBDir = "W:\SQL\Data\COMMON"
                SQLUserDBLogDir = "W:\SQL\Logs\LG_COMMON"
                SQLTempDBDir = "H:\SQL\Data"
                SQLTempDBLogDir  = "H:\SQL\Logs"
                FailoverClusterGroupName  = "$FailoverClusterGroupName"
                FailoverClusterIPAddress  = "$FailoverClusterIPAddress"
                FailoverClusterNetworkName  = "$FailoverClusterNetworkName"
                PsDscRunAsCredential = $Credential

            }

**Comment by rbg21** [comment]
The H for the Temp drive is a local drive.

**Comment by johlju** [comment]
Thanks for the configuration and explanation. 

Okay so this might be a problem with mount points then. 

Can you send us what this command returns? But the command will only work if you still haven't installed SQL Server, and the disks can still be seen in Available Storage. 
If you still have the disk in Available Storage it would help to get the output of this command so I can mock a test to replicate the problem.

```
Get-CimInstance -Namespace 'root/MSCluster' -ClassName 'MSCluster_ResourceGroup' -Filter "Name = 'Available Storage'" | Get-CimAssociatedInstance -Association MSCluster_ResourceGroupToResource -ResultClassName MSCluster_Resource
```

**Comment by rbg21** [comment]
Caption                   :
Description               :
InstallDate               :
Name                      : lg_common
Status                    :
Characteristics           : 2081
Flags                     : 0
CoreResource              : False
CryptoCheckpoints         : {}
DeadlockTimeout           : 300000
DeleteRequiresAllNodes    : False
EmbeddedFailureAction     : 2
Id                        :  ########
IsAlivePollInterval       : 4294967295
IsClusterSharedVolume     : False
LastOperationStatusCode   : 0
LocalQuorumCapable        : False
LooksAlivePollInterval    : 4294967295
MonitorProcessId          : 3988
OwnerGroup                : Available Storage
OwnerNode                 : server1
PendingTimeout            : 180000
PersistentState           : True
PrivateProperties         : MSCluster_Property_Resource_Physical_Disk
QuorumCapable             : True
RegistryCheckpoints       : {}
RequiredDependencyClasses :
RequiredDependencyTypes   : {}
ResourceClass             : 1
ResourceSpecificData1     : 0
ResourceSpecificData2     : 0
ResourceSpecificStatus    :
RestartAction             : 2
RestartDelay              : 500
RestartPeriod             : 900000
RestartThreshold          : 1
RetryPeriodOnFailure      : 3600000
SeparateMonitor           : False
State                     : 2
StatusInformation         : 0
Subclass                  :
Type                      : Physical Disk
PSComputerName            :

Caption                   :
Description               :
InstallDate               :
Name                      : binaries
Status                    :
Characteristics           : 2081
Flags                     : 0
CoreResource              : False
CryptoCheckpoints         : {}
DeadlockTimeout           : 300000
DeleteRequiresAllNodes    : False
EmbeddedFailureAction     : 2
Id                        : ##########
IsAlivePollInterval       : 4294967295
IsClusterSharedVolume     : False
LastOperationStatusCode   : 0
LocalQuorumCapable        : False
LooksAlivePollInterval    : 4294967295
MonitorProcessId          : 3988
OwnerGroup                : Available Storage
OwnerNode                 : server1
PendingTimeout            : 180000
PersistentState           : True
PrivateProperties         : MSCluster_Property_Resource_Physical_Disk
QuorumCapable             : True
RegistryCheckpoints       : {}
RequiredDependencyClasses :
RequiredDependencyTypes   : {}
ResourceClass             : 1
ResourceSpecificData1     : 0
ResourceSpecificData2     : 0
ResourceSpecificStatus    :
RestartAction             : 2
RestartDelay              : 500
RestartPeriod             : 900000
RestartThreshold          : 1
RetryPeriodOnFailure      : 3600000
SeparateMonitor           : False
State                     : 2
StatusInformation         : 0
Subclass                  :
Type                      : Physical Disk
PSComputerName            :

Caption                   :
Description               :
InstallDate               :
Name                      : common
Status                    :
Characteristics           : 2081
Flags                     : 0
CoreResource              : False
CryptoCheckpoints         : {}
DeadlockTimeout           : 300000
DeleteRequiresAllNodes    : False
EmbeddedFailureAction     : 2
Id                        : ########
IsAlivePollInterval       : 4294967295
IsClusterSharedVolume     : False
LastOperationStatusCode   : 0
LocalQuorumCapable        : False
LooksAlivePollInterval    : 4294967295
MonitorProcessId          : 3988
OwnerGroup                : Available Storage
OwnerNode                 : server1
PendingTimeout            : 180000
PersistentState           : True
PrivateProperties         : MSCluster_Property_Resource_Physical_Disk
QuorumCapable             : True
RegistryCheckpoints       : {}
RequiredDependencyClasses :
RequiredDependencyTypes   : {}
ResourceClass             : 1
ResourceSpecificData1     : 0
ResourceSpecificData2     : 0
ResourceSpecificStatus    :
RestartAction             : 2
RestartDelay              : 500
RestartPeriod             : 900000
RestartThreshold          : 1
RetryPeriodOnFailure      : 3600000
SeparateMonitor           : False
State                     : 2
StatusInformation         : 0
Subclass                  :
Type                      : Physical Disk
PSComputerName            :

Caption                   :
Description               :
InstallDate               :
Name                      : san_root
Status                    :
Characteristics           : 2081
Flags                     : 0
CoreResource              : False
CryptoCheckpoints         : {}
DeadlockTimeout           : 300000
DeleteRequiresAllNodes    : False
EmbeddedFailureAction     : 2
Id                        : ########
IsAlivePollInterval       : 4294967295
IsClusterSharedVolume     : False
LastOperationStatusCode   : 0
LocalQuorumCapable        : False
LooksAlivePollInterval    : 4294967295
MonitorProcessId          : 3988
OwnerGroup                : Available Storage
OwnerNode                 : server1
PendingTimeout            : 180000
PersistentState           : True
PrivateProperties         : MSCluster_Property_Resource_Physical_Disk
QuorumCapable             : True
RegistryCheckpoints       : {}
RequiredDependencyClasses :
RequiredDependencyTypes   : {}
ResourceClass             : 1
ResourceSpecificData1     : 0
ResourceSpecificData2     : 0
ResourceSpecificStatus    :
RestartAction             : 2
RestartDelay              : 500
RestartPeriod             : 900000
RestartThreshold          : 1
RetryPeriodOnFailure      : 3600000
SeparateMonitor           : False
State                     : 2
StatusInformation         : 0
Subclass                  :
Type                      : Physical Disk
PSComputerName            :

**Comment by johlju** [comment]
My bad, I was to quick to send you the command to run and did not think it thru. :/
I wanted the path information as well. I rigged a code sample below (this is a snippet from code in the actual resource) that I would like you to run. I can not test it since I don't have a lab right now with available disk. I hope it will run without any problem. It just do a get of the disk as before but ouputs more information.

So my hope is that this will get all disks, and add a temporary property IsPossibleOwner to the returned object so we can see if it want to use the disk. It then outputs all the disks, it outputs all partitions regardless of IsPossibleOwner, and finally it outputs all disk partitions when IsPossibleOwner equals $true.

Conclusion: I need to see all paths that is available, and all paths it thinks it has available. It must be a problem here.
```
# Get the disk resources that are available (not assigned to a cluster role)
$availableStorage = Get-CimInstance -Namespace 'root/MSCluster' -ClassName 'MSCluster_ResourceGroup' -Filter "Name = 'Available Storage'" |
                        Get-CimAssociatedInstance -Association MSCluster_ResourceGroupToResource -ResultClassName MSCluster_Resource | `
                            Add-Member -MemberType NoteProperty -Name 'IsPossibleOwner' -Value $false -PassThru

foreach ($diskResource in $availableStorage)
{
    # Determine whether the current node is a possible owner of the disk resource
    $possibleOwners = $diskResource | Get-CimAssociatedInstance -Association 'MSCluster_ResourceToPossibleOwner' -KeyOnly | Select-Object -ExpandProperty Name

    if ($possibleOwners -icontains $env:COMPUTERNAME)
    {
        $diskResource.IsPossibleOwner = $true
    }
}

Write-Verbose 'All disks' -Verbose

$availableStorage

Write-Verbose 'Partitions regardless of IsPossibleOwner' -Verbose

foreach ($diskResource in ($availableStorage))
{
    $diskResource | Get-CimAssociatedInstance -ResultClassName 'MSCluster_DiskPartition' | Select-Object -ExpandProperty Path
}

Write-Verbose 'Partitions where {IsPossibleOwner -eq $true}' -Verbose

foreach ($diskResource in ($availableStorage | Where-Object {$_.IsPossibleOwner -eq $true}))
{
    $diskResource | Get-CimAssociatedInstance -ResultClassName 'MSCluster_DiskPartition' | Select-Object -ExpandProperty Path
}
```

**Comment by rbg21** [comment]
So the above output stayed the same except for the addition of IsPossibleOwner : $true was added and the following is what was displayed after...
VERBOSE: Partitions regardless of IsPossibleOwner
\\?\Volume{db3f1a04-586b-4532-bdc8-c67711b0fb6b}
\\?\Volume{a45209c2-59cf-4f58-b082-764225550bca}
\\?\Volume{d87a18bc-e223-4ce8-a9b6-4b45eb779805}
W:
VERBOSE: Partitions where {IsPossibleOwner -eq $true}
\\?\Volume{db3f1a04-586b-4532-bdc8-c67711b0fb6b}
\\?\Volume{a45209c2-59cf-4f58-b082-764225550bca}
\\?\Volume{d87a18bc-e223-4ce8-a9b6-4b45eb779805}
W:

And the funny thing is I noticed that the W: didnt the \\?\Volume{####} in the cluster diskc but then comparing to previous clusters we built with the SQL install GUI(current process still) it still shows W: in the cluster disks.

Thanks for all the help.

**Comment by johlju** [comment]
Happy to help. 😄 

Okay so this is the problem I think. It doesn't show the paths. It should have shown the mount points (for example) 'W:\SQL\Data\COMMON' here instead of the volume guid (for example) '\?\Volume{db3f1a04-586b-4532-bdc8-c67711b0fb6b}'. That is why it doesn't work. 😞 

Wonder what property contains the mount point path. 🤔 
I change the script so it should output all the properties on the partition, let's see if there is another property that holds that information.

```
# Get the disk resources that are available (not assigned to a cluster role)
$availableStorage = Get-CimInstance -Namespace 'root/MSCluster' -ClassName 'MSCluster_ResourceGroup' -Filter "Name = 'Available Storage'" |
                        Get-CimAssociatedInstance -Association MSCluster_ResourceGroupToResource -ResultClassName MSCluster_Resource | `
                            Add-Member -MemberType NoteProperty -Name 'IsPossibleOwner' -Value $false -PassThru

foreach ($diskResource in $availableStorage)
{
    # Determine whether the current node is a possible owner of the disk resource
    $possibleOwners = $diskResource | Get-CimAssociatedInstance -Association 'MSCluster_ResourceToPossibleOwner' -KeyOnly | Select-Object -ExpandProperty Name

    if ($possibleOwners -icontains $env:COMPUTERNAME)
    {
        $diskResource.IsPossibleOwner = $true
    }
}

Write-Verbose 'All disks' -Verbose

$availableStorage

Write-Verbose 'Partitions where {IsPossibleOwner -eq $true}' -Verbose

foreach ($diskResource in ($availableStorage | Where-Object {$_.IsPossibleOwner -eq $true}))
{
    $diskResource | Get-CimAssociatedInstance -ResultClassName 'MSCluster_DiskPartition' 
}
```

**Comment by rbg21** [comment]
ok here is the bottom piece with the paths. The top was the same as before 
VERBOSE: Partitions where {IsPossibleOwner -eq $true}
Caption                : 
Description            : 
InstallDate            : 
Name                   : 
Status                 : 
Characteristics        : 
Flags                  : 28
FileSystem             : NTFS
FileSystemFlags        : 65470703
FreeSpace              : 8103
MaximumComponentLength : 255
MountPoints            : {W:\sql\logs\lg_common}
PartitionNumber        : 2
Path                   : \\?\Volume{db3f1a04-586b-4532-bdc8-c67711b0fb6b}
SerialNumber           : 4262854417
TotalSize              : 8157
VolumeGuid             : db3f1a04-586b-4532-bdc8-c67711b0fb6b
VolumeLabel            : lg_common
PSComputerName         : 

Caption                : 
Description            : 
InstallDate            : 
Name                   : 
Status                 : 
Characteristics        : 
Flags                  : 28
FileSystem             : NTFS
FileSystemFlags        : 65470703
FreeSpace              : 6053
MaximumComponentLength : 255
MountPoints            : {W:\sql\binaries}
PartitionNumber        : 2
Path                   : \\?\Volume{a45209c2-59cf-4f58-b082-764225550bca}
SerialNumber           : 986772103
TotalSize              : 6109
VolumeGuid             : a45209c2-59cf-4f58-b082-764225550bca
VolumeLabel            : binaries
PSComputerName         : 

Caption                : 
Description            : 
InstallDate            : 
Name                   : 
Status                 : 
Characteristics        : 
Flags                  : 28
FileSystem             : NTFS
FileSystemFlags        : 65470703
FreeSpace              : 7082
MaximumComponentLength : 255
MountPoints            : {W:\sql\data\common}
PartitionNumber        : 2
Path                   : \\?\Volume{d87a18bc-e223-4ce8-a9b6-4b45eb779805}
SerialNumber           : 4228324648
TotalSize              : 7133
VolumeGuid             : d87a18bc-e223-4ce8-a9b6-4b45eb779805
VolumeLabel            : common
PSComputerName         : 

Caption                : 
Description            : 
InstallDate            : 
Name                   : 
Status                 : 
Characteristics        : 
Flags                  : 29
FileSystem             : NTFS
FileSystemFlags        : 65470703
FreeSpace              : 5038
MaximumComponentLength : 255
MountPoints            : {W:}
PartitionNumber        : 2
Path                   : W:
SerialNumber           : 2863695078
TotalSize              : 5085
VolumeGuid             : 607b2b07-f399-45e2-be58-92a63a75da93
VolumeLabel            : san_root
PSComputerName         :

**Comment by rbg21** [comment]
I almost feel like the resource is missing this piece that is in the ini file that was generated after a successful install using the gui.

; Specifies a cluster shared disk to associate with the SQL Server failover cluster instance. 

FAILOVERCLUSTERDISKS="san_root"

**Comment by johlju** [comment]
Okay, so when using mount points it seems that the path is in the `MountPoints` property, not the Path property. So we have to evaluate if the property `MountPoints` is set then that path must be used, I guess together with the `Path` property. And since the property is named `MountPoints` (plural) I guess that means it can hold more than one mount point as well, so we have to take that in account too. 

I can't see a reference anywhere (on the web) to what "san_root" could mean. 
Each needed disk is added to the FAILOVERCLUSTERDISKS setup parameter here:
https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L1028

**Comment by rbg21** [comment]
Sorry, san_root is more in house to what we call our W drive that gets mapped and then has the other drives mounted.

**Comment by johlju** [comment]
Ah I see, I see that on the Volume Label now, missed that :)

Yes adding that will add all mount point disks too. Maybe that is the problem, it shouldn't look for full paths, just the drive letter. Let me look at the code for a while, get back to you.

**Comment by rbg21** [comment]
Thanks again.

**Comment by johlju** [comment]
After setting up tests for this to test the scenario, I think it is neither mount points or that it is wrong property that is used.
The code should add the disk W: as one disk, and the other disk should follow, exactly as you point out it did in the .ini file when you installed from the GUI.

I think that it must be a problem with that you are using local drive for the temp drive. Do you see this in the verbose log? 
```
VERBOSE: 2017-04-11_18-30-56: Found assigned parameter 'SQLTempDBDir'. Adding path 'H:\SQL\Data' to list of paths that required cluster drive.
VERBOSE: 2017-04-11_18-30-56: Found assigned parameter 'SQLTempDBLogDir'. Adding path 'H:\SQL\Logs' to list of paths that required cluster drive.
```
It want to find a shared disk for the drive used in by the temp path. And since that is H: it cannot find a shared drive for that, and then it fails. The path it expects to find a shared drive for is the the following parameters that can be seen in [line 921-933](https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L921-L933)

If you could test to change the path for those two parameters to use a folder on one of the mount point disks? Then you should be able to install. It you could test this, to rule out any other problem, it would be awesome.

If that works, then we have a scenario where we must in some way take in account hat Temp drives can be used locally.

**Comment by rbg21** [comment]
This was from a previous deploy that failed. 
VERBOSE:  [[xSQLServerSetup]] 2017-04-07_15-30-19: Found assigned parameter 'SQLTempDBDir'. Adding path 'H:\SQL\Data' to list of paths that required cluster drive.
VERBOSE: [[xSQLServerSetup] 2017-04-07_15-30-19: Found assigned parameter 'SQLTempDBLogDir'. Adding path 'H:\SQL\Logs' to list of paths that required cluster drive.

But now WOW! 

So I created a folder within W (w:\tempdb\sql\data & logs). Made the changes in the config and ran into a few small errors. One was that SA password not strong enough(had a $ in there and it did not like that) and the other was the syntax of the features(needed single quotes, not double). Then it was working its magic. 

So it finished in about 208 seconds, sql resource is running in failover cluster which is great. 

The only question now is, it spit out this at the end complaining about DQ feature. Am I missing a requirement for it to install? 

VERBOSE:[[xSQLServerSetup] 2017-04-11_12-59-37: Features found: SQLENGINE,REPLICATION,FULLTEXT'
VERBOSE:[[xSQLServerSetup]] 2017-04-11_12-59-37: Unable to find feature 'DQ' among the installed features: 'SQLENGINE,REPLICATION,FULLTEXT'
VERBOSE:[[xSQLServerSetup]] 2017-04-11_12-59-37: Clustered install, checking parameters.
VERBOSE:  LCM:  [ End    Set      ]  [[xSQLServerSetup]  in 202.60
40 seconds.

PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Set-TargetResource 
functionality with error message: Test-TargetResource returned false after calling set. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : server1
 
VERBOSE:  LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], 
    CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : server1
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 208.814 seconds

**Comment by rbg21** [comment]
A follow up question. 

Say I was to use this way to create the SQL cluster where I create a dummy TempDB folder, but we then change it to the local drive after setup. Next time DSC runs will it flip it back? or because the config is 'installfailovercluster', it will pass over that section in the config data because its already configured?

**Comment by rbg21** [comment]
I found this from a previous cluster ini from a previous built cluster.  
SQLENGINE,REPLICATION,FULLTEXT,DQ,DQC,CONN,IS,BC,SDK,BOL,SSMS,ADV_SSMS,SNAC_SDK,MDS

I have a feeling i need the DQC along with DQ to make it work.

**Comment by johlju** [comment]
I'm afraid the resource does not supporting DQ currently. It is probably installed, but the test code does not know how to check for that feature, so the Test-method fails at the end of the Set-method. And on every subsequent run it will say it is missing the DQ feature, and will run the Set-method again to try to install it. 
If you know how we could implement a check for that (what registry key, service or file(s) etc) to determine if it is installed or not (also taking account if there can be two major SQL versions installed on the same server), then it would be quicker to implement it. 

Regarding creating a dummy TempDB and switching them to the local drive. That would work today, because the resource do not yet check so that configuration is in desired state (there is an issue for that). 
Today the resource only check to see if the feature are installed, and if a feature is missing it tries to install it. It does not enforce consistency today.
So in the future it might try to enforce the tempdb back to your dummy folders. But then again, it is not easy to move tempdb when they are in use, so in this case I think we can safely say that we won't try move tempdb, but instead output a warning that tempdb is not consistent.

So from this we have the following issues
* Not supporting having tempdb on local disk when SQL Server is 2012 an above. See article https://logicalread.com/sql-server-tempdb-best-practices-placement-w01
* Not supporting DQ and DQC

I will submit issues for these two.

**Comment by johlju** [comment]
I think you hit issue #444 now? If not, and you hit yet another issue, please submit a new issue for that 😄 It is easier for people with similar problem to search for issues then.

Let's close this issue if you feel it is solved (or at least it generated new known issue) 😄
