### ISSUE TITLE
xSQLServerSetup: Master Data Services (MDS) not detected by Get/Test-TargetResource

### ISSUE THREAD

**Issue by chris-bowman** [PowerShell/xSQLServer#486]
**Details of the scenario you try and problem that is occurring:**
I'm trying to install MDS feature by itself on a web server for hosting Master Data Services. When installing fails with the Test-TargetResource failing to find MDS feature. The feature itself installs okay, but the test can't find it.

I was thinking to just add in a check registry for the feature (seems to be in HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\<version>\Master Data Services\CurrentVersion)

Output error:
```
VERBOSE: An LCM method call arrived from computer servername with user sid S-1-5-21-291186265-3001357459-3569380570-500.
VERBOSE: [servername]: LCM:  [ Start  Set      ]
VERBOSE: [servername]: LCM:  [ Start  Resource ]  [[xSQLServerSetup]installSqlServer]
VERBOSE: [servername]: LCM:  [ Start  Test     ]  [[xSQLServerSetup]installSqlServer]
VERBOSE: [servername]:                            [[xSQLServerSetup]installSqlServer] 2017-04-11_05-48-54: Using path: C:\Deployment\Installs\SQLInstall\setup.exe
VERBOSE: [servername]:                            [[xSQLServerSetup]installSqlServer] 2017-04-11_05-48-55: Features found: ''
VERBOSE: [servername]: LCM:  [ End    Test     ]  [[xSQLServerSetup]installSqlServer]  in 0.7350 seconds.
VERBOSE: [servername]: LCM:  [ Start  Set      ]  [[xSQLServerSetup]installSqlServer]
VERBOSE: [servername]:                            [[xSQLServerSetup]installSqlServer] 2017-04-11_05-48-55: Using path: C:\Deployment\Installs\SQLInstall\setup.exe
VERBOSE: [servername]:                            [[xSQLServerSetup]installSqlServer] 2017-04-11_05-48-55: Using path: C:\Deployment\Installs\SQLInstall\setup.exe
VERBOSE: [servername]:                            [[xSQLServerSetup]installSqlServer] 2017-04-11_05-48-55: Starting setup using arguments: /ACTION="Install" /IACCEPTSQLSERVERLICENSETERMS="True" /QUIET="True" /INSTANCENAME="MSSQLSERVER" /FEATURES=MDS /UPDATEENABLED="True"
VERBOSE: [servername]:                            [[xSQLServerSetup]installSqlServer] 2017-04-11_05-48-56: Process matching path 'C:\Deployment\Installs\SQLInstall\setup.exe' started in process ID 3312
VERBOSE: [servername]:                            [[xSQLServerSetup]installSqlServer] 2017-04-11_05-53-10: Using path: C:\Deployment\Installs\SQLInstall\setup.exe
VERBOSE: [servername]:                            [[xSQLServerSetup]installSqlServer] 2017-04-11_05-53-10: Features found: ''
VERBOSE: [servername]: LCM:  [ End    Set      ]  [[xSQLServerSetup]installSqlServer]  in 255.2500 seconds.
PowerShell DSC resource MSFT_xSQLServerSetup  failed to execute Set-TargetResource functionality with error message: Test-TargetResource returned false after calling set. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
VERBOSE: [servername]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 257.712 seconds

```

**The DSC configuration that is using the resource (as detailed as possible):**
Here's the relevant snippet:
		xSQLServerSetup installSqlServer
		{
			InstanceName = "MSSQLSERVER"
			SetupCredential = $Admincreds
			UpdateEnabled = $true
			SourcePath = $sqlinstallpath
            Features= "MDS"
		}

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows 2012R2 / SQL2014 / PowerShell 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by chris-bowman** [comment]
Actually looking at it more, I think it would be better to check the ConfigurationState. I added the following to the Get-TargetResource, which seems to work well:
    
```
    # Check if MDS sub component is configured for this server
    New-VerboseMessage -Message "Detecting MDS feature (HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$($sqlVersion)0\ConfigurationState)"
    $isMDSInstalled = (Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Microsoft SQL Server\$($sqlVersion)0\ConfigurationState").MDSCoreFeature
    New-VerboseMessage -Message "MDS Value: $isMDSInstalled"
    if ($isMDSInstalled -eq 1)
    {
        New-VerboseMessage -Message 'MDS feature detected'
        $features += 'MDS,'
    }
    else
    {
        New-VerboseMessage -Message 'MDS feature not detected'
    }
```

**Comment by johlju** [comment]
That looks good to me! Could you send in a PR for this change? Or do you want help making this change?

**Comment by chris-bowman** [comment]
If you're able to show me how to do it, sure - first time user of github :)

**Comment by johlju** [comment]
I will be happy too. 😄 We were all new at this at one time :)

To start you should read this to get your environment up https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md

Then make sure you create a working branch like 'add-mds-support'. Best is not to make changes to your forks dev branch, that is used to have a base for new working branches.

When you done the changes and pushed them to your fork you can go to your fork at GitHub (or this resource) and go to the code section, there GitHub will let you know you have a branch that you can submit as a pull request (or choose the right working branch in GitHub and press the New Pull Request button). 

In the README.md under the contribution section you can read more about style guidelines, tests and so on. https://github.com/PowerShell/xSQLServer#contributing

Just ask questions along the way and I will help you. 

I label this as In progress.

**Comment by chris-bowman** [comment]
Thanks @johlju! PR #488 created. Hopefully I did everything correctly :)
I'm still awaiting the CLA from docusign, but will complete it when it arrives.

**Comment by johlju** [comment]
Did you receive the CLA from DocuSign? If you signed it I think I need to bump the CLA bot.
