### ISSUE TITLE
Multiple xSQLAOGroupEnsure

### ISSUE THREAD

**Issue by quizard** [PowerShell/xSQLServer#494]
I am trying to create multiple Availability groups.

xSQLAOGroupEnsure AG01
       {
          Ensure = "Present"
          AvailabilityGroupName = "AG01"
          AvailabilityGroupNameListener = "db-101"
          AvailabilityGroupNameIP = "20.0.0.205"
          AvailabilityGroupPort = "1433";
          AvailabilityGroupSubMask ="255.255.255.0"
          ############## this needs to be added to config data
          SetupCredential = $credential
          PsDscRunAsCredential = $credential
          SQLInstanceName = $Node.SQLInstanceName
          DependsOn = ("[xSQLServerEndpoint]" + $Node.NodeName),("[xSQLServerAlwaysOnService]" + $Node.NodeName),("[WindowsFeature]ADTools")
       }

       xSQLAOGroupEnsure AG02
       {
          Ensure = "Present"
          AvailabilityGroupName = "AG02"
          AvailabilityGroupNameListener = "db-102"
          AvailabilityGroupNameIP = "20.0.0.206"
          AvailabilityGroupPort = "1433";
          AvailabilityGroupSubMask ="255.255.255.0"
          ############## this needs to be added to config data
          SetupCredential = $credential
          PsDscRunAsCredential = $credential
          SQLInstanceName = $Node.SQLInstanceName
          DependsOn = ("[xSQLServerEndpoint]" + $Node.NodeName),("[xSQLServerAlwaysOnService]" + $Node.NodeName),("[WindowsFeature]ADTools")
       }

The first instance creates successfully. The second instance gets ignored even though it is in the .MOF that is generated. I also want to be able to specify SYNC or ASYNC. Am I on the right track? Should I create another instance and do a 1:1 on instance to AG?

**Comment by johlju** [comment]
xSQLAOGroupEnsure is deprecated. Please use [xSQLServerAlwaysOnAvailabilityGroup](https://github.com/PowerShell/xSQLServer#xsqlserveralwaysonavailabilitygroup) and [xSQLServerAlwaysOnAvailabilityGroupReplica](https://github.com/PowerShell/xSQLServer#xsqlserveralwaysonavailabilitygroupreplica) instead. Let me know if you have the same problem with those.

I will add to the README.md so that it is easier to see that they are deprecated. 
Closing this issue when that is done.

**Comment by quizard** [comment]
Awesome, going to try now. Thanks Johan!

**Comment by quizard** [comment]
xSQLServerAlwaysOnAvailabilityGroupReplica isn't found. I'll dig deeper now.

**Comment by johlju** [comment]
My bad. 😞  xSQLServerAlwaysOnAvailabilityGroupReplica hasn't been released yet. You need to download the Dev version from here. It will released in a few days. 😄

**Comment by quizard** [comment]
All good, I'll grab it now.

**Comment by johlju** [comment]
Great!

I will merge the fix to the README.md in an hour or so, this issue will auto-close then. If you have any further problems with please submit a new issue.

Thanks for submitting this issue! Thanks for contributing! 😄
