### ISSUE TITLE
xWaitForAvailabilityGroup: Should this move to xFailoverCluster?

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#502]
**Details of the scenario you try and problem that is occurring:**
This resource does not use any SQL objects to look at Availability Groups. It uses `Get-ClusterGroup` to check if the cluster group exist. In it's current form it would be better to move this over to xFailoverCluster where it would do more good for other use cases too (but with a better name of course).

Or we can make it actually connect to a primary replica to see that it has been configured correctly. I mean, even if the cluster group exist, maybe the configuration is not done on the first node, this might make the second node jump to quickly.

Or we can move this logic into xSQLServerAlwaysOnAvailabilityGroupReplica which already has parameters for the primary replica.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
@randomnote1 @Zuldan what do you think about this?

**Comment by johlju** [comment]
To all: Is anyone using this resource? Please let me know how you have used it and if you had any issue. Please also tell me if you did not have a use for it. That is as equal important. 😄

**Comment by randomnote1** [comment]
I haven't used this resource yet. Now that I'm thinking about it, I'm not sure if I would now that xSQLServerAlwaysOnAvailabilityGroup and xSQLServerAlwaysOnAvailabilityGroupReplica exist. I would probably only use this resource to wait for the replicas to be created prior to adding databases to the AG.

Is there any other value or scenarios I might be missing?

**Comment by johlju** [comment]
@randomnote1 maybe this?

Scenario:

So lets say you have two servers. First server should become primary replica (using xSQLServerAlwaysOnAvailabilityGroup, and the seconds server should become secondary replica (using xSQLServerAlwaysOnAvailabilityGroupReplica).
Let say we start the configuration on both servers at the same time, but the secondary node is faster so it want to join the AG but there is no primary replica yet. 

Question:
Do we need to use xWaitForAvailabilityGroup on the secondary replica to wait until the primary replica has finished and is available?

**Comment by randomnote1** [comment]
@johlju, you're absolutely right. For some reason I was thinking the resource would be run on the same node. I should know better than to think on a Monday!

Yes, we need xWaitForAvailabilityGroup on the secondary to be able to detect when the Availability Group has been created on the primary.

Should we rename this resource xWaitForAlwaysOnAvailabilityGroup?

**Comment by Zuldan** [comment]
@johlju we use this resource with all our AOAG cluster setups. Usually our primary and replica nodes are built at the exact same time so this resource is essential for us. We've also never had any issues with it. I don't have a preference with its future direction as long as the replica can wait for the primary node to become active some way or other.

**Comment by johlju** [comment]
@randomnote1 @Zuldan So you all vote to keep it in this module? 

If we move it to xFailoverCluster it could be renamed as 'xWaitForClusterGroup' or 'xClusterWaitForClusterGroup'.

If we keep it here would it be to long to rename the resource to xSQLServerAlwaysOnWaitForAvailabilityGroup? xWaitForAlwaysOnAvailabilityGroup works too, but would love for it to start with xSQLServer so it is easily found with `Get-DscResource xSQLServer*`. 
But maybe I am too finicky? 😄 

I have put some time to fix up the resource in PR #507. I thought that was needed regardless. I hope it went into the direction "to the better" :) So I can do the rename in that PR too.

**Comment by randomnote1** [comment]
I vote for it to remain here. I think it will make the resource more user friendly.

As for a rename, I imagine I'll get to that after the database membership resource.

**Comment by johlju** [comment]
@randomnote1 We can discuss the rename in issue #137. I'm closing this issue since i feel the right decision is to keep it here as you point out. If someone else feel differently we can always on it up again. 😄
