### ISSUE TITLE
xSQLAOGroupEnsure BackupPreference and Priority are hard coded. Implement as variables and default the values.

### ISSUE THREAD

**Issue by aultt** [PowerShell/xSQLServer#52]

**Comment by Matticusau** [comment]
There is already a parameter for the BackupPreference but it doesn't seem to be referenced. It is also misspelled. 

[ValidateSet("Primary","Secondary")]
        [System.String]
        $AutoBackupPrefernce ="Primary",

I am working on this and the Priority param in a branch.
