### ISSUE TITLE
Changing password for SQLInstall Credential -errors

### ISSUE THREAD

**Issue by crshnbrn66** [PowerShell/xSQLServer#529]
**Details of the scenario you tried and the problem that is occurring:**

Using this installation script: InstallNamedInstanceSingleServerFromUncPathUsingSourceCredential.ps1 (attached as .txt) and installing one time with valid credentials that can retrieve the setup files the configuration works as expected.   If you change the password for the installation user the script will not allow you to use the new password that is in the domain.  Rather it expects the password that the script was first run with 

[InstallNamedInstanceSingleServerFromUncPathUsingSourceCredential.txt](https://github.com/PowerShell/xSQLServer/files/955362/InstallNamedInstanceSingleServerFromUncPathUsingSourceCredential.txt)

Because the user was forced tochange the password the script now fails because the remote location is not accesible without the new password. 

with the new password when the configuration runs here is the detail for that run: 
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer DBServer1 with user sid S-1-5-21-1842424028-1716546704-1885625156-333430.
VERBOSE: [DBServer1]: LCM:  [ Start  Set      ]
VERBOSE: [DBServer1]: LCM:  [ Start  Resource ]  [[Log]ParamLog]
VERBOSE: [DBServer1]: LCM:  [ Start  Test     ]  [[Log]ParamLog]
VERBOSE: [DBServer1]: LCM:  [ End    Test     ]  [[Log]ParamLog]  in 0.0000 seconds.
VERBOSE: [DBServer1]: LCM:  [ Start  Set      ]  [[Log]ParamLog]
VERBOSE: [DBServer1]:                            [[Log]ParamLog] Running SQLInstall. PackagePath = \\phinstall1\dba\Microsoft SQL Server\2016
VERBOSE: [DBServer1]: LCM:  [ End    Set      ]  [[Log]ParamLog]  in 0.0000 seconds.
VERBOSE: [DBServer1]: LCM:  [ End    Resource ]  [[Log]ParamLog]
VERBOSE: [DBServer1]: LCM:  [ Start  Resource ]  [[WindowsFeature]NetFramework45Core]
VERBOSE: [DBServer1]: LCM:  [ Start  Test     ]  [[WindowsFeature]NetFramework45Core]
VERBOSE: [DBServer1]: LCM:  [ End    Test     ]  [[WindowsFeature]NetFramework45Core]  in 0.1090 seconds.
The user name or password is incorrect
    + CategoryInfo          : AuthenticationError: (:) [], CimException
    + FullyQualifiedErrorId : Win32Error:1326
    + PSComputerName        : DBServer1
 
VERBOSE: [DBServer1]: LCM:  [ Start  Resource ]  [[File]SQLServerIniFile]
VERBOSE: [DBServer1]: LCM:  [ Start  Test     ]  [[File]SQLServerIniFile]
VERBOSE: [DBServer1]:                            [[File]SQLServerIniFile] Building file list from cache.
VERBOSE: [DBServer1]:                            [[File]SQLServerIniFile] The destination object was found and no action is required.
VERBOSE: [DBServer1]: LCM:  [ End    Test     ]  [[File]SQLServerIniFile]  in 0.0470 seconds.
VERBOSE: [DBServer1]: LCM:  [ Skip   Set      ]  [[File]SQLServerIniFile]
VERBOSE: [DBServer1]: LCM:  [ End    Resource ]  [[File]SQLServerIniFile]
VERBOSE: [DBServer1]: LCM:  [ Start  Resource ]  [[Script]InstallSQLServer]
VERBOSE: [DBServer1]: LCM:  [ Start  Test     ]  [[Script]InstallSQLServer]
VERBOSE: [DBServer1]: LCM:  [ End    Test     ]  [[Script]InstallSQLServer]  in 0.0310 seconds.
The user name or password is incorrect
    + CategoryInfo          : AuthenticationError: (:) [], CimException
    + FullyQualifiedErrorId : Win32Error:1326
    + PSComputerName        : DBServer1
 
VERBOSE: [DBServer1]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : DBServer1
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 2.434 seconds
Start-DscConfiguration : The running command stopped because the user selected the Stop option.
At C:\temp\InstallNamedInstanceSingleServerFromUncPathUsingSourceCredential.ps1:122 char:1
+ Start-DscConfiguration -Path c:\temp\SQLInstall  -Wait -Force -Creden ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Start-DscConfiguration], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ActionPreferenceStop,Microsoft.PowerShell.DesiredStateConfiguration.Commands.StartDscConfigurationCommand
 

for the same configuration if you use the original password the results are below: 

VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
Access is denied.
    + CategoryInfo          : PermissionDenied: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070005
    + PSComputerName        : DBServer1
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.142 seconds

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Microsoft Windows Server 2016 Datacenter
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0       

Name                           Value                                                                                                                                                                         
----                           -----                                                                                                                                                                         
PSVersion                      5.1.14393.693                                                                                                                                                                 
PSEdition                      Desktop                                                                                                                                                                       
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                       
BuildVersion                   10.0.14393.693                                                                                                                                                                
CLRVersion                     4.0.30319.42000                                                                                                                                                               
WSManStackVersion              3.0                                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                                           
SerializationVersion           1.1.0.1                 
**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

Manifest   1.1        PSDesiredStateConfiguration         {Invoke-DscResource, Publish-DscConfiguration, Set-DscLocalConfigurationManager, Start-DscConfiguration...}                                                                 
7.0.0.0    xSQLServer

**Comment by johlju** [comment]
First, thanks for submitting an issue for this!

When the function `Sql2016-Install` was ran it (see below) it compiled a .mof file saving the password in that file. That password will never change unless you run the function ´Sql2016-Install` again and compile the file again containing the new password. This is how DSC is built and designed.
Normally you will use a certificate to encrypt the password which will be decrypted on the target node (and the password will be a very complex password). 

```
Sql2016-Install -ConfigurationData $ConfigurationData -PsDscRunAsCredential $credential -SqlInstallCredential $credential -SqlAdministratorCredential $credential -SqlServiceCredential $credential -SqlAgentServiceCredential $credential 
```

**Comment by crshnbrn66** [comment]
i deleted the mof deleted my profile and have tried some of the same things provided in this article that Steve commented on: 

[](http://stackoverflow.com/questions/25336842/remove-a-powershell-dsc-configuration)

No matter what I seem to try it still will not accept the actual password that my account is in Active directory.

**Comment by crshnbrn66** [comment]
If I use another user that has admin privs and I try and run the same DSC configuration I get the same message access denied when using an alternate user.  This is on the same host in which I ran the script previously.

**Comment by crshnbrn66** [comment]
I understand now... I had a misconfiguration on my directory structure.
