### ISSUE TITLE
BREAKING CHANGE: xSQLServerNetwork: Currently does not support to set static port when instance was  using dynamic ports

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#534]
**Details of the scenario you tried and the problem that is occurring:**
Currently to set a static port the dynamic ports must be set to blank. That is not possible today since parameter `TcpDynamicPorts` only allows to set '0' which means to use dynamic ports.

https://docs.microsoft.com/en-us/sql/tools/configuration-manager/tcp-ip-properties-ip-addresses-tab

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
I currently solved this by adding a blank value in the ValidateSet and the schema (it seems to work). 

But I think parameter `TcpDynamicPorts` really should be a `[System.Boolean]` value parameter, for example `UseDynamicPort`. That will be a breaking change.

**Comment by johlju** [comment]
Should the parameter `TcpDynamicPorts` be renamed to `TcpDynamicPort` (singular) since we do a breaking change regardless?

**Comment by nabrond** [comment]
@johlju I will take a stab at updating this resource.

**Comment by johlju** [comment]
Awesome! Labeling it as in progress. Thanks! 😄
