### ISSUE TITLE
AlwaysOnAvailabilityGroupReplica: Add replica fails

### ISSUE THREAD

**Issue by viksrini** [PowerShell/xSQLServer#541]
**Details of the scenario you tried and the problem that is occurring:**
Trying to add a secondary replica to a Always on group and seeing the following error.
It fails are '$availabilityGroupReplica = New-SqlAvailabilityReplica @newAvailabilityGroupReplicaParams' 

**ERROR**

Job {F35194A7-2F7B-11E7-A95A-02B1BBD665BB} : 
Message Creating the Availability Group Replica failed. 
HResult -2146233087 
StackTrack    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
   at System.Management.Automation.PowerShell.CoreInvokeRemoteHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.DesiredStateConfiguration.Internal.ResourceProviderAdapter.ExecuteCommand(PowerShell powerShell, ResourceModuleInfo resInfo, String operationCmd, List`1 acceptedProperties, CimInstance nonResourcePropeties, CimInstance resourceConfiguration, LCMDebugMode debugMode, PSInvocationSettings pSInvocationSettings, UInt32& resultStatusHandle, Collection`1& result, ErrorRecord& errorRecord, PSModuleInfo localRunSpaceModuleInfo)

**The DSC configuration that is using the resource (as detailed as possible):**
```
  xSQLServerAlwaysOnAvailabilityGroupReplica AddReplica
            {
                Ensure = 'Present'
                Name = $node.nodename
                AvailabilityGroupName = $Node.AGName
                SQLServer = $node.nodename
                SQLInstanceName = $Node.SQLInstanceName
                FailoverMode = 'Automatic'
                ConnectionModeInPrimaryRole = 'AllowAllConnections'
                ConnectionModeInSecondaryRole = 'AllowAllConnections'
                AvailabilityMode = 'SynchronousCommit'
                PrimaryReplicaSQLServer = ($AllNodes | Where-Object { $_.Role -eq 'PrimaryReplica'} ).NodeName
                PrimaryReplicaSQLInstanceName = ($AllNodes | Where-Object { $_.Role -eq 'PrimaryReplica' } ).SQLInstanceName
                PsDscRunAsCredential = $domainadmincred
                EndpointHostName = ($AllNodes | Where-Object { $_.Role -eq 'PrimaryReplica'} ).NodeName
            } 
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Server 2016,SQL 2016 and 

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSQLServer 7.0.0
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
xSQLServer 7.0.0

**Comment by johlju** [comment]
Anyone else seen this problem with AlwaysOnAvailabilityGroupReplica?

**Comment by asdglkjkwekdf** [comment]
HResult -2146233087 (80131501) is not something I would have expected; but,  I have to say "Creating the Availability Group Replica failed" is very unhelpful.

I usually have to run a profiler trace or debug the resource and inspect $_ to get anything useful. In this case $_ would probably be best.

Someone might be able to provide a better answer with this information attached.


Getting off topic perhaps it would be nice if the detailed error message was logged (to the verbose stream if required) for these try catches; but, I'm not sure of the rational for obscuring the error so I cannot really comment.

**Comment by randomnote1** [comment]
My bad on obfuscating the error. I didn't find the parameter to pass through the inner exception on New-TerminatingError until a couple weeks ago. I'll have to submit a pull request to fix that.

By the time the resource gets to that point it accounts for pretty much anything that could go wrong. I have not encountered a reason why it would fail at this point. That is the main reason the error is simply "Creating the availability group replica failed." Clearly though, there is a scenario in play that I didn't encounter in testing.

**Comment by johlju** [comment]
@randomnote1 I saw you created a separate issue for the "obfuscating error" since this issue could be another error.
I will get that PR through so we can determine whats causing this error.

Thank @randomnote1 for sending in the PR! And thanks to @asdglkjkwekdf for raising the issue!

**Comment by viksrini** [comment]
I have already run a debug on the module execution and was able to determine that it fails on the new-availabilitygroup command. I initially suspected this was something to do with my config but this works through the UI.

Inspecting the variable, as mentioned above, the error is obfuscated so thanks for creating a separate issue. I will continue debugging and post my results as I get them.

**Comment by johlju** [comment]
@viksrini I merged the fix by @randomnote1. Please download the Dev version of the module and see if it helps you determine the cause.

**Comment by viksrini** [comment]
@johlju  thank you. I will test it out and post back results.

**Comment by ScottArbeit** [comment]
I just tried the new version as well... I ended up breaking out the Set-TargetResource function just to debug it on the SQL Server I'm trying to set the replica on. I'm getting this error:

> 'ReadOnlyRoutingList' is a ReadOnly property.

Makes sense, [it's get only, no set](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.availabilityreplica.readonlyroutinglist.aspx). Same thing for [ReadonlyRoutingConnectionUrl](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.availabilityreplica.readonlyroutingconnectionurl.aspx) above it. I believe it's coming from line 416 in dev branch:

    if ( $ReadOnlyRoutingList -ne $availabilityGroupReplica.ReadOnlyRoutingList )
    {
        ---> $availabilityGroupReplica.ReadOnlyRoutingList = $ReadOnlyRoutingList
        Update-AvailabilityGroupReplica -AvailabilityGroupReplica $availabilityGroupReplica
    }

Not sure this is the same error as this issue, but xSqlServerAvailabilityGroupReplica is failing for me as well, so figured I'd join the thread.

**Comment by ScottArbeit** [comment]
Sorry... I just saw https://github.com/PowerShell/xSQLServer/issues/518, which is the issue I'm referring to. I'll focus there.

**Comment by randomnote1** [comment]
Looks like the documentation for ReadOnlyRoutingList is inconsistent. At the top it says "Gets or sets the read only routing connection list for the availability replica.", but in the example it shows `public StringCollection ReadonlyRoutingList { get; }`.

I didn't look at it in my lab to verify it's a read-only property on the actual object. I'm assuming you confirmed that?

The documentation for ReadOnlyRoutingUrl is get/set per the documentation. Is it different on the object?

**Comment by ScottArbeit** [comment]
I should have checked before I posted. Time to break out ILDasm...

[ReadOnlyRoutingList](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.availabilityreplica.readonlyroutinglist.aspx) is read-only.

[ReadOnlyRoutingConnectionUrl](https://msdn.microsoft.com/en-us/library/microsoft.sqlserver.management.smo.availabilityreplica.readonlyroutingconnectionurl.aspx) is read/write. I just assumed based on the "ReadOnly" part of it that it would actually be read-only (what was I thinking?!?), but it has a setter.

![image](https://cloud.githubusercontent.com/assets/2406993/25766004/cb16cb0c-31a4-11e7-9a4a-4231bf7e7612.png)

![image](https://cloud.githubusercontent.com/assets/2406993/25766079/26b286cc-31a5-11e7-81aa-03a661450cb7.png)

**Comment by viksrini** [comment]
I was able to successfully add the replica to to SQL. Turns out it was something in my test environment that was creating problems. 

The un hiding of the error messaage helped debug it quicker. Thanks for all the help.
