### ISSUE TITLE
xSQLServerScript: Could you please help me how to run a script with Credential

### ISSUE THREAD

**Issue by sguess** [PowerShell/xSQLServer#545]
Hi,
 
I try to used xSQLServerScript to do DB backup process. Below is my script.  It always response "Converting and storing encrypted passwords as plain text is not recommended." error when I execute "Start-DscConfiguration ....", no matter what I set how complex password.
Could you please give me an example for run SQL script? Thanks.

My env:
>`     OS: Windows Server 2008 R2 SP1                                             ` 
>`    SQL Server: Microsoft SQL Server 2014 Express (64-bit), (Ver 12.0.2000.8)  ` 
>`    WMF: 5.1.14409.1005                                                        ` 
>`    xSQLServer: 7.0.0.0                                                        ` 

PowerShell Script:
> `$backupPwd = ConvertTo-SecureString “my_Password01” -AsPlainText -Force              `
>`$backupCred = New-Object System.Management.Automation.PSCredential (“sp”, $backupPwd)`
>` Configuration BackUpDB                                                              `
>`{                                                                                    `
>`   param(                                                                            `
>`       [Parameter(Mandatory = $false)]                                               `
>`       [PSCredential]                                                                `
>`       $SqlCredential                                                                `
>`   )                                                                                 `
>`                                                                                     `
>`   Import-DscResource -ModuleName xSQLServer                                         `
>`                                                                                     `
>`    Node localhost                                                                   `
>`    {                                                                                `
>`        xSQLServerScript BackUpDB                                                    `
>`        {                                                                            `
>`            ServerInstance = 'MyServerName\SQLEXPRESS'                               `
>`            Credential = $SqlCredential                                              `
>`                                                                                     `
>`            SetFilePath = 'C:\DSCTemp\SQLScripts\Set-RunSQLScript.sql'               `
>`            TestFilePath = 'C:\DSCTemp\SQLScripts\Test-RunSQLScript.sql'             `
>`            GetFilePath = 'C:\DSCTemp\SQLScripts\Get-RunSQLScript.sql'               `
>`            Variable = @("FilePath=C:\temp\log\AuditFiles")                          `
>`        }                                                                            `
>`                                                                                     `
>`    }                                                                                `
>`}                                                                                    `
>`                                                                                     `
>  ` BackUpDB -SqlCredential $backupCred                                                 `
>  `                                                                                     `
>  ` Start-DscConfiguration -Path C:\DSC\BackUpDB -Wait -Verbose -Force                  `

Result:
>`ConvertTo-MOFInstance : System.InvalidOperationException error processing property 'Credential' OF TYPE 'xSQLServerScript': Converting and storing encrypted passwords as plain text is   `
>`not recommended. For more information on securing credentials in MOF file, please refer to MSDN blog: http://go.microsoft.com/fwlink/?LinkId=393729                                       `
>`At line:17 char:9                                                                                                                                                                         `
>`+   xSQLServerScript                                                                                                                                                                      `
>`At line:341 char:16                                                                                                                                                                       `
>`+     $aliasId = ConvertTo-MOFInstance $keywordName $canonicalizedValue                                                                                                                   `
>`+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                   `
>`    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException                                                                                              `
>`    + FullyQualifiedErrorId : FailToProcessProperty,ConvertTo-MOFInstance                                                                                                                 `
>`Compilation errors occurred while processing configuration 'BackUpDB'. Please review the errors reported in error stream and modify your configuration code appropriately.                `
>`At C:\windows\system32\WindowsPowerShell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:3917 char:5                                                            `
>`+     throw $ErrorRecord                                                                                                                                                                  `
>`+     ~~~~~~~~~~~~~~~~~~                                                                                                                                                                  `
>`    + CategoryInfo          : InvalidOperation: (BackUpDB:String) [], InvalidOperationException                                                                                           `
>`    + FullyQualifiedErrorId : FailToProcessConfiguration`
Thanks, 
Daniel

**Comment by johlju** [comment]
It has nothing to do with the resource. It is DSC that are not allowing you to store password unencrypted. In a production environment you should encrypt the password with a certificate.It referencing an URL in the error message on how to do this; [Securing the MOF File](http://go.microsoft.com/fwlink/?LinkId=393729)

In a lab environment you can override this my adding `PsDscAllowPlainTextPassword` to the configuration, but this is not recommended in production where you will leave your password unencrypted. You can read more about it here; [Using Credentials with PsDscAllowPlainTextPassword and PsDscAllowDomainUser in PowerShell DSC Configuration Data](https://blogs.technet.microsoft.com/ashleymcglone/2015/12/18/using-credentials-with-psdscallowplaintextpassword-and-psdscallowdomainuser-in-powershell-dsc-configuration-data)

**Comment by johlju** [comment]
Let me know if you this helped you.

**Comment by sguess** [comment]
@johlju  Many thanks for your help.  It is useful
