### ISSUE TITLE
Does xSQLServer can be run in Windows Server 2008 R2 SP1

### ISSUE THREAD

**Issue by sguess** [PowerShell/xSQLServer#546]
Hi,

Does xSQLServer support in Windows Server 2008 R2SP1?

I installed xSQLServer module in Windows Server 2008 R2SP1,  I can get the infromation with "Get-Module -ListAvailable".
But when I used start-DSCConfiguration to invoke it. it displayed "Module SqlServer not found, trying to use older SQLPS module." 
In fact, I can do successful in Windows Server 2012 R2 by same way.

> Windows version: Microsoft Windows Server 2008 R2 Enterprise (6.1.7601 Service Pack 1 Build 7601)
> WMF version:5.1.14409.1005 
> .Net version: 4.5.2

Error information:
>VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManage
r,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer MyServer with user sid S-1-5-21-4070628030-840234078-891559575-1109.
> VERBOSE: [MyServer]: LCM:  [ Start  Set      ]
> VERBOSE: [MyServer]:                            [DSCEngine] Importing the module C:\Program Files\WindowsPowerShell\Modules\xSQLServer\7.0.0.0\DscResour
> ces\MSFT_xSQLServerScript\MSFT_xSQLServerScript.psm1 in force mode.
> VERBOSE: [MyServer]: LCM:  [ Start  Resource ]  [[xSQLServerScript]BackUpDB]
> VERBOSE: [MyServer]: LCM:  [ Start  Test     ]  [[xSQLServerScript]BackUpDB]
> VERBOSE: [MyServer]:                            [[xSQLServerScript]BackUpDB] Importing the module MSFT_xSQLServerScript in force mode.
> VERBOSE: [MyServer]:                            [[xSQLServerScript]BackUpDB] 2017-05-05_10-54-03: Module SqlServer not found, trying to use older SQLPS 
> module.
> Unable to find type [Microsoft.SqlServer.Management.PowerShell.SqlPowerShellSqlExecutionException].
>     + CategoryInfo          : InvalidOperation: (Microsoft.SqlSe...cutionException:) [], CimException
>     + FullyQualifiedErrorId : TypeNotFound
>     + PSComputerName        : localhost
>  
> VERBOSE: [MyServer]: LCM:  [ End    Test     ]  [[xSQLServerScript]BackUpDB]  in 0.4060 seconds.
> The PowerShell DSC resource '[xSQLServerScript]BackUpDB' with SourceInfo '::16::9::xSQLServerScript' threw one or more non-terminating errors while running 
> the Test-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more 
> details.
>     + CategoryInfo          : InvalidOperation: (:) [], CimException
>     + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
>     + PSComputerName        : localhost
>  
> VERBOSE: [MyServer]: LCM:  [ End    Set      ]
> The SendConfigurationApply function did not succeed.
>     + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
>     + FullyQualifiedErrorId : MI RESULT 1
>     + PSComputerName        : localhost
>  
> VERBOSE: Operation 'Invoke CimMethod' complete.
> VERBOSE: Time taken for configuration job to complete is 4.183 seconds

Thanks
Daniel Pei

**Comment by luigilink** [comment]
SQL Server 2008R2 SP1 is not supported since 10/08/2013 😸 
But it's a good issue, we have to define what SQL version is supported with xSQLServer.
We are in 2017, so for my point of view, it's not a good idea to support the oldest (and the unsupported) SQL versions.
My2Cent

**Comment by johlju** [comment]
@sguess Thanks for submitting this issue. 

@luigilink Either i'm misreading, but can't find a reference to SQL Server 2008 R2 SP1? Only _Windows_ Server 2008 R2 SP1.

Either way, looks like it can't load the assembly types.
Can you verify that you have 'Microsoft® Windows PowerShell Extensions for SQL Server® 2008 R2', 'Microsoft System CLR Types for SQL Server' and 'Microsoft SQL Server Management Objects' installed? They can be found in either the SQL Server media or in the Feature Pack.

The reference to SqlServer means that it can't find the recommended SqlServer (which can replace SQLPS and is downloaded from PowerShell Gallery).

**Comment by luigilink** [comment]
Oups I read to quickly. You're right it's about Windows Server 2008 R2 SP1 and no SQL Server 2008 R2 SP1.
Sorry for this. 😞

**Comment by chancein007** [comment]
After installing 'Microsoft® Windows PowerShell Extensions for SQL Server® 2008 R2', 'Microsoft System CLR Types for SQL Server' and 'Microsoft SQL Server Management Objects', the issue still existed.

**Comment by chancein007** [comment]
The solution is that we should install sqlps module on this server.
For more detailed information, please refer to: http://blog.smu.edu/wis/2012/11/26/sql-server-powershell-module-sqlps/

**Comment by sguess** [comment]
@luigilink  Thanks for your help.  It looked original SQL Server 2008 R2 not support xSQLServer.
@johlju Thanks for your help.  Yes, it should install a feature pack for xSQLServer.  
@chancein007 Thanks for your solution. It is usefully and it was successful.
