### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroupReplica: Set-Resource fails to add named SQL Instance as secondary replica to AAG.

### ISSUE THREAD

**Issue by GoelPooja** [PowerShell/xSQLServer#548]
**Set-Resource fails to add named SQLInstance as secondary replica to AAG.**
```
xSQLServerAlwaysOnAvailabilityGroupReplica AddReplica
{
	Ensure = 'Present'
	Name = $SQLServer
	AvailabilityGroupName = "$AAGName"
	SQLServer = $SQLServer
	SQLInstanceName = $SqlInstanceName
	PrimaryReplicaSQLServer = $PrimaryReplicaSQLServer
	PrimaryReplicaSQLInstanceName = $PrimaryReplicaSQLInstanceName
	PsDscRunAsCredential = $SysAdminAccount
}
```
Fixing this by replacing server name with full SQLInstance name while adding secondary replica to AAG.

- Operating System: Windows Server 2012 R2
- SQL Server: 2014
- PowerShell: 5
- Module: xSQLServerSetup
- Version: 6.0.0.0

**Comment by GoelPooja** [comment]
It works after updating the DSC configuration to following without making changes to DSC resource.

xSQLServerAlwaysOnAvailabilityGroupReplica AddReplica
{
Ensure = 'Present'
Name = "$SQLServer\$SqlInstanceName"
AvailabilityGroupName = "$AAGName"
SQLServer = $SQLServer
SQLInstanceName = $SqlInstanceName
PrimaryReplicaSQLServer = $PrimaryReplicaSQLServer
PrimaryReplicaSQLInstanceName = $PrimaryReplicaSQLInstanceName
PsDscRunAsCredential = $SysAdminAccount
}

**Comment by johlju** [comment]
We should add that to the parameter description. It should say '...in the following format Computer\Instance'.

@GoelPooja Does this mean that PR #549 can be closed?

**Comment by johlju** [comment]
@GoelPooja Just want to check-in. What is the status on this issue? :smile: Can we close PR #549 without merging the code?

**Comment by GoelPooja** [comment]
That's correct.
Sorry for the delayed response.
PR can be closed without merging

**Comment by johlju** [comment]
No worries. I will close the PR and I will fix a new PR that fixes the parameter description. 
Thanks!
