### ISSUE TITLE
xSQLServerRSConfig: Remove parameter SQLAdminCredential

### ISSUE THREAD

**Issue by bozho** [PowerShell/xSQLServer#568]
There is no need for the $SQLAdminCredential parameter to be mandatory. Remove the restriction.

Update: In pr #573 it was decided to remove SQLAdminCredential. PR title changed accordingly,

**Comment by bozho** [comment]
Ok, I've made the changes to make $SQLAdminCredential optional, but I have two problems:

1. I'd like to fix issues #567, #568, #569 and #570 in order (#568 branch off #567, #569 branch off #568 and so on). If I submit a PR for #568, it is compared to the dev branch in this repository and shows changes from both #567 and #568, which makes it confusing. What would be the best workflow here? Should I wait until #567 is merged and then submit the PR for #568?

2. We still need to use CredSSP authentication when running Invoke-Sqlcmd with $SQLAdminCredential using Invoke-Command, even though we're running it on the same machine. I don't know how this behaves when run in a domain, but running it on a non-domain machine requires enabling/configuring CredSSP - I'm not sure if we should consider this to be within the remit of this resource, or just document the fact that CredSSP needs to be enabled and configured.

**Comment by johlju** [comment]
1. three ways of doing this I think, either
1.1 We do and merge each PR in turn before continuing on the next PR. 
1.2 You do all changes (all issues) in one PR.
1.3 You branch off to a new working branch from the previous working branch (your suggestion above). When sending in a PR for the branched off PR's, write in the PR description which PR(s) it depends on. I will review and merge them in the correct order. 

To have a flow I think we could go with 1.3, what do you think? After the first PR is merged, you can rebase the second PR (always rebase, no pull or merge) which will get the commit history in the right order and then replay each commit onto of that (after any conflicts are resolved).

**Comment by bozho** [comment]
Yeah, I agree with 1.3, review in order, rebase before the next PR.

**Comment by bozho** [comment]
I'll create a PR for this issue, since I'd like to discuss $SQLAdminCredential in the code...

**Comment by johlju** [comment]
I change the title of this issue. Since it was discussed in PR #573 that we should remove the parameter SQLAdminCredential

**Comment by johlju** [comment]
This issue was resolved in merged PR #573. Closing this issue.
