### ISSUE TITLE
xSQLServerRSConfig: Virtual directory creation for SQL 2016

### ISSUE THREAD

**Issue by bozho** [PowerShell/xSQLServer#569]
SQL Server 2016 introduced a breaking change by changing the web portal application name from "ReportManager" to "ReportServerWebApp": https://docs.microsoft.com/en-us/sql/reporting-services/breaking-changes-in-sql-server-reporting-services-in-sql-server-2016

The problem was reported in #202 and a pull request submitted (#220), but the pull request seems to have been abandoned.

**Comment by johlju** [comment]
I labeled this as in progress.
