### ISSUE TITLE
BREAKING CHANGE: xSQLServer: Remove support for WMF 4.0 (PowerShell 4.0)

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#574]
Are there users out there that still needs WMF 4.0?

Should we remove support for WMF 4.0 and makes this module WMF 5.x only? Meaning that if it works for WMF 4.0, then great, if it doesn't then we won't make an effort to make it work.

To support PowerShell 4.0 across the entire module will require a lot of work.

We have discussed this in various issues. We have also discussed this in the Community Calls where it was said, more or less, that generally it's okay to only support WMF 5.x, but if a resource can support PowerShell 4.0 then that would be better.

**Comment by Zuldan** [comment]
@johlju My thoughts are WMF 4 support can be dropped. There should be no reason why anyone hasn't upgraded their servers to WMF 5.1 (better performance and better security) unless your running Exchange and no one runs SQL Server on an Exchange Server. Your spending a lot of your time trying to maintain WMF 4 support. Your time is precious. If someone really wants WMF 4 support they can always download the older versions of xSQLServer.

**Comment by randomnote1** [comment]
When I submit the pull request for the availability group database membership resource, that will force the module to require WMF 5. I wrote it as a class based resource. I'm working on the unit tests now which are proving to be fun!

**Comment by johlju** [comment]
@Zuldan I though along those lines as well, that they can download an old version. Just want to make sure it is not an overwhelming need for WMF 4.0. But I would be surprised if it was.

@randomnote1 Do you mean the entire module, just not that resource? If you actually mean the entire module will require WMF 5.x, then that will tip the scale in favor of removing support for WMF 4.0.
Just curious what makes the entire module require WMF 5.x? Is it something in the .psd1 and how the module will be loaded? 

@randomnote1 I'm looking forward to seeing that resource and the tests! It will be a new experience reviewing that code. 😄

**Comment by randomnote1** [comment]
Yes, the entire module. PowerShell 4 can't import the module if there's is a class based resource referenced in the psd1.

Doing the review will be interesting. There will be a few decision points required.

**Comment by johlju** [comment]
Ah great @randomnote1. Then we can't support WMF 4.0 anymore. I will do that in the PR I'm working on now. Then I can clean out a lot of code and texts.
