### ISSUE TITLE
xSQLServerMaxDop and xSQLServerMemory: error when SQLServer property is empty

### ISSUE THREAD

**Issue by paugusto76** [PowerShell/xSQLServer#576]
Please mark the SQLServer property of xSQLServerMaxDop as mandatory. If it's not defined in the DSC script it will give an error.

**Details of the scenario you tried and the problem that is occurring:**

I'm using xSQLServer to define a template for my SQL Server for SharePoint (local VMs)

**The DSC configuration that is using the resource (as detailed as possible):**

xSQLServerMaxDop SQLMaxDop
{
    DependsOn = "..."
    MaxDop = 0
    SQLInstanceName = "MSSQLSERVER"
}

I could compile the script without any warnings, but when applying the DSC mof files it gives an error stating that SQLServer is null or empty.

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

Windows Server 2016, SQL Server 2016, PowerShell v5

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**

xSQLServer version 7.0.0.0

**Comment by johlju** [comment]
@paugusto76 Thanks for reporting this! Paramater `SQLServer` is set to the default value  `$env:COMPUTERNAME`, so it seems there is a bug in that it validates that parameter when it should not.

**Comment by paugusto76** [comment]
hum... ok, I'll check the code also to see if I can help

**Comment by johlju** [comment]
Would be awesome if you could help fix this :) Thanks!

**Comment by paugusto76** [comment]
Ok, found it :)

You are using the $PSBoundParameters that automatically creates a Dictionary with the parameters and their values, but this only stores values that are actually passed when invoking. It doesn't contain default values, so the SQLServer property in $PSBoundParameters will be $null.

You'll have to create a logic to ensure you are passing a value on this or just pass the $SQLServer instead of $PSBoundParameters.SQLServer

**Comment by johlju** [comment]
Yes right! Thank you for finding that. Are you interested to send in a PR fixing this?

Would be good with a regression unit test also, as it seems we didn't test for this scenario.

**Comment by paugusto76** [comment]
Sure. I can do that! :)

**Comment by johlju** [comment]
Awesome! I label this as in progress, please let me know if you need any assistance in any way. 😄
