### ISSUE TITLE
xSqlServerSetup: Conn, BC etc features only detected if SQLENGINE also installed

### ISSUE THREAD

**Issue by ChrisLGardner** [PowerShell/xSQLServer#591]
**Details of the scenario you tried and the problem that is occurring:**

When installing some of the tools features, in this case Conn and BC, but not installing SQLENGINE the Get-TargetResource is not returning them as installed features. Looking at the code the check for these features is within a check for a service named after the instance name. 

**The DSC configuration that is using the resource (as detailed as possible):**

```
xSqlServerSetup SqlInstall {
                DependsOn = '[xComputer]DomainJoin'
                Action = 'Install'
                InstanceName = 'MSSQLSERVER'
                SourcePath = $Node.SqlSourcePath
                SetupCredential = $LocalAdminCredential
                Features = 'Conn,BC,IS,SSMS,ADV_SSMS'
                ProductKey = '<stuff here>'
                UpdateEnabled = 'False'
                INSTALLSHAREDDIR="C:\Program Files\Microsoft SQL Server"
                INSTALLSHAREDWOWDIR="C:\Program Files (x86)\Microsoft SQL Server"
                INSTANCEDIR="C:\Program Files\Microsoft SQL Server"
                SQLSvcAccount = $SQLServerUAT
                AgtSvcAccount = $SQLServerAgentUAT
                SQLCollation = "Latin1_General_CI_AS"
                SecurityMode = 'SQL'
                SAPwd = $SAPWD
                ASCOLLATION = "Latin1_General_CI_AS"
                ASDATADIR = "Data"
                ASBACKUPDIR = "Backup"
                ASTEMPDIR = "Temp"
                ASCONFIGDIR = "Config"
                SQLSYSADMINACCOUNTS = "$DomainNetBiosName\Database Admins"
                SQLUSERDBDIR = (Join-Path -Path $DataDrive -ChildPath "Data\SQL")
                SQLUSERDBLOGDIR = (Join-Path -Path $DataDrive -ChildPath "Data\SQL")
                BROWSERSVCSTARTUPTYPE = "Disabled"
            }
```
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**

Server 2012R2, running SQL 2012, PSv5.1 and v7.0.0.0 of xSqlServer

The fix for this is reasonably simple, just moving the various checks which detect the tools features outside the current If block would work. I will have a look at putting in a PR for this at some point in the next few days.

**Comment by johlju** [comment]
@ChrisLGardner  Thanks for reporting this. I see you want to run with this, so I label this one as in progress! Thanks!
