### ISSUE TITLE
SourcePath and UpdateEnabled

### ISSUE THREAD

**Issue by TakeshiKovacs** [PowerShell/xSQLServer#6]
Hi Team
Having an issue with this module, not sure if it's my issue or issue with the code.
Using the sample included I cannot get the sourcepath or updateenabled/updatesource parameters to work.
Digging through the various modules I found that there were hard coded values in xSQLServerSetup.psm1 and they were not getting replaced with my parameter values.
I removed the hard coded values from the psm1 file and it correctly picked up my parameter values.
Is this expected behaviour?
Cheers

**Comment by oWretch** [comment]
Hi Takeshi,

The parameters are working for me. Can you post your $ConfigurationData section?
