### ISSUE TITLE
xSQLServerPowerPlan Get-DscConfiguration

### ISSUE THREAD

**Issue by spawluk** [PowerShell/xSQLServer#63]
`Get-DscConfiguration` of `xSQLServerPowerPlan` returns object:

```
ConfigurationName    : SQLServerInstance
DependsOn            : {[xSQLServerSetup]{name}}
ModuleName           : xSQLServer
ModuleVersion        : 1.6.0.0
PsDscRunAsCredential :
ResourceId           : [xSQLServerPowerPlan]{name}
SourceInfo           :
Ensure               : True
PSComputerName       : {server}
CimClassName         : MSFT_xSQLServerPowerPlan
```

Where `Ensure` Should be `Present`

**Comment by luigilink** [comment]
Release 4.0.0.0 => Removed xSQLServerPowerPlan from this module
@kwirkykat This issue can be closed.

**Comment by johlju** [comment]
Good catch @luigilink. I'm closing this on since this resource has moved to another module .

**Comment by johlju** [comment]
Good catch @luigilink. I'm closing this on since this resource has moved to another module .
