### ISSUE TITLE
xSQLServerDatabaseDefaultLocation: New Resource

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/xSQLServer#656]
**Details of the scenario you tried and the problem that is occurring:**
I propose a new resource called **xSQLServerDatabaseDefaultLocation** be created in order to manage the default data, log, and backup locations of an instance. Here is the proposed schema:

```
[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerDatabaseDefaultLocation")]
class MSFT_xSQLServerDatabaseDefaultLocation : OMI_BaseResource
{
    [Key, Description("The host name of the SQL Server to be configured.")] String SQLServer;
    [Key, Description("The name of the SQL instance to be configured.")] String SQLInstanceName;
    [Key, Description("The default location to set. Valid values are 'Data','Log', and 'Backup'."), ValueMap{"Data","Log","Backup"}, Values{"Data","Log","Backup"}] String Location;
    [Key, Description("The full path to the desired default location.")] String Path;
};
```

**The DSC configuration that is using the resource (as detailed as possible):**
N/A
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
N/A
**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
N/A
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
dev

**Comment by johlju** [comment]
Looks good to me! 😄

**Comment by PaulFeaser** [comment]
I will work on this issue.  I'm working with @randomnote1 on this.

**Comment by johlju** [comment]
@PaulFeaser awesome! I labeling this one as in progress. :smile:
