### ISSUE TITLE
Get-TargetResource Parameters Inconsistencies

### ISSUE THREAD

**Issue by NikCharlebois** [PowerShell/xSQLServer#679]
**Details of the scenario you tried and the problem that is occurring:**
As part of the SQLServer.Reverse script that extracts the DSC Configuration of an existing SQL Server installation (http://aka.ms/ReverseSQLServer), we are using the parameters' information on the Get-TargetResource function to determine the Data Type of each parameter. However, is most resources inside of xSQLServer, the Get and Set functions accept different parameters, where in most cases, the Get only accepts the mandatory ones. Get, Set and Test should expose the same set of parameters. The missing parameters on the Get-TargetResource function should be set as mandatory=false, but they should be listed no matter.

If we take the example of another great DSC module, SharePointDSC, all 3 functions (Get, Set and Test) always have the same parameter set.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Win 2012 R2/WMF 5.1/ SQL Server 2012 SP3

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
SQLServer

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
7.1.0.0 on the PoSh Gallery

**Comment by johlju** [comment]
It is not necessary to list non-mandatory parameters for the Get-TargetResource. It's a best practice from DscResources here https://github.com/PowerShell/DscResources/blob/master/BestPractices.md#get-targetresource-should-not-contain-unused-non-mandatory-parameters

So I suggest that you instead change to validate type by parsing the mof file or by the values returned in the hash tables of the Get-TargetResource.

**Comment by johlju** [comment]
Closing this since I see you opened an issue to fix this at your end.

Thanks for submitting the issue so we could clarify! 😄
