### ISSUE TITLE
xSqlServerSetup feature list is case sensitive

### ISSUE THREAD

**Issue by afscrome** [PowerShell/xSQLServer#72]
When specifying the Features attribute of xSqlServerSetup, the feature list is case sensitive

``` 
xSqlServerSetup SqlServer {
    Features= 'SqlEngine'
}
```

If case sensitivity is required by setup.exe, then some validation should be performed on the case of the given features.  If case sensitivity is not required, then it looks like this could be fixed by replacing calls to `$Features.Contains("SQLENGINE")` (which is case sensitive) with `$Features -contains 'SQLENGINE'` (which is not case sensitive)

**Comment by Arturas-K** [comment]
Hi i think it is duplicate of #38
