### ISSUE TITLE
xSQLServerSetup: Trailing Slash in UpdatePath

### ISSUE THREAD

**Issue by aboersch** [PowerShell/xSQLServer#720]
**Details of the scenario you tried and the problem that is occurring:**
I had specified an UpdateSource that contained a trailing slash e.g. "C:\SQL\Updates\\".

I then received the error "The /IAcceptSQLServerLicenseTerms command line parameter is missing or has not been set to true."

From what I can tell the xSQLServerSetup is sanitizing all paths in terms of trailing slashes EXCEPT UpdateSource. Should be an easy fix by adding ,'UpdateSource' at line 853 in the resource.
**The DSC configuration that is using the resource (as detailed as possible):**
UpdatePath = "C:\SQL\Updates\\"
**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Win2012R2
SQL2014Dev
WMF5.1
**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSqlServer 8.0.0.0
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Main / PSGET

Would be glad to make the contribution

**Comment by johlju** [comment]
@aboersch Thanks for reporting this! And you are correct, it should be sufficient to add this to the array at [line 838](https://github.com/PowerShell/xSQLServer/blob/dev/DSCResources/MSFT_xSQLServerSetup/MSFT_xSQLServerSetup.psm1#L838).

**Comment by johlju** [comment]
To all: This is an "easy fix", so if anyone want to contribute this change to the module, then this would be a good issue to start with. I'm here to help along the way.

**Comment by aboersch** [comment]
Me ;)

**Comment by johlju** [comment]
@aboersch awesome! Labeling this as in progress.
