### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroup : add Database Level Health Detection and Per Database DTC support

### ISSUE THREAD

**Issue by mdaniou** [PowerShell/xSQLServer#721]
**Details of the scenario you tried and the problem that is occurring:**

I work on the DSC configurations for an upgrade to SQL 2016. The environment uses an Always-On Cluster and we would like to use the option Database Level Health Detection.

I had a look at the resource and I can implement that. If you agree with this implementation, I will submit it to you. I also want to add the option Per Database DTC support in the resource at the same time.

Please share your thoughts.

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Windows Server 2016
SQL Server 2016 SP1 CU3
Powershell 5.1

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
xSQLServer 8.0.0.0

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

**Comment by johlju** [comment]
Yes, please, that would be a great addition to the resource. Could you please share the new suggested schema.mof so the community can have a chance to raise any suggestions/opinions while you code this? 

Will the resource xSQLServerAlwaysOnAvailabilityGroupReplica need to change as well? If so please submit an issue for that resource as well (with the new suggested schema.mof).

**Comment by mdaniou** [comment]
I am currently writing it. 

These options are to be configured at the AG level, hence I don't see any reason xSQLServerAlwaysOnAvailabilityGroupReplica would have to be changed.

I am not used to contribute in GitHub. I have read the guidelines but please let me know if I am doing something the wrong way.
It seems like I can't assign this issue to myself and set the correct labels.

Here is the schema.mof updated then :

`[ClassVersion("1.0.0.0"), FriendlyName("xSQLServerAlwaysOnAvailabilityGroup")]
class MSFT_xSQLServerAlwaysOnAvailabilityGroup : OMI_BaseResource
{
    [Key, Description("The name of the availability group.")] String Name;
    [Required, Description("Hostname of the SQL Server to be configured.")] String SQLServer;
    [Key, Description("Name of the SQL instance to be configured.")] String SQLInstanceName;
    [Write, Description("Specifies if the availability group should be present or absent. Default is Present."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Specifies the automated backup preference for the availability group. Default is None"), ValueMap{"Primary","SecondaryOnly","Secondary","None"}, Values{"Primary","SecondaryOnly","Secondary","None"}] String AutomatedBackupPreference;
    [Write, Description("Specifies the replica availability mode. Default is 'AsynchronousCommit'."), ValueMap{"AsynchronousCommit","SynchronousCommit"}, Values{"AsynchronousCommit","SynchronousCommit"}] String AvailabilityMode;
    [Write, Description("Specifies the desired priority of the replicas in performing backups. The acceptable values for this parameter are: integers from 0 through 100. Of the set of replicas which are online and available, the replica that has the highest priority performs the backup. Default is 50.")] UInt32 BackupPriority;
    [Write, Description("Specifies the type of availability group is Basic. This is only available is SQL Server 2016 and later and is ignored when applied to previous versions.")] Boolean BasicAvailabilityGroup;
    [Write, Description("Specifies if the option Database Level Health Detection is enabled. This is only available is SQL Server 2016 and later and is ignored when applied to previous versions.")] Boolean DatabaseLevelHealthDetection;
    [Write, Description("Specifies if the option Database DTC Support is enabled. This is only available is SQL Server 2016 and later and is ignored when applied to previous versions.")] Boolean DatabaseDTCSupport;
    [Write, Description("Specifies how the availability replica handles connections when in the primary role."), ValueMap{"AllowAllConnections","AllowReadWriteConnections"}, Values{"AllowAllConnections","AllowReadWriteConnections"}] String ConnectionModeInPrimaryRole;
    [Write, Description("Specifies how the availability replica handles connections when in the secondary role."), ValueMap{"AllowNoConnections","AllowReadIntentConnectionsOnly","AllowAllConnections"}, Values{"AllowNoConnections","AllowReadIntentConnectionsOnly","AllowAllConnections"}] String ConnectionModeInSecondaryRole;
    [Write, Description("Specifies the hostname or IP address of the availability group replica endpoint. Default is the instance network name.")] String EndpointHostName;
    [Write, Description("Specifies the automatic failover behavior of the availability group."), ValueMap{"OnServerDown","OnServerUnresponsive","OnCriticalServerErrors","OnModerateServerErrors","OnAnyQualifiedFailureCondition"}, Values{"OnServerDown","OnServerUnresponsive","OnCriticalServerErrors","OnModerateServerErrors","OnAnyQualifiedFailureCondition"}] String FailureConditionLevel;
    [Write, Description("Specifies the failover mode. Default is 'Manual'."), ValueMap{"Automatic","Manual"}, Values{"Automatic","Manual"}] String FailoverMode;
    [Write, Description("Specifies the length of time, in milliseconds, after which AlwaysOn availability groups declare an unresponsive server to be unhealthy. Default is 30000.")] UInt32 HealthCheckTimeout;
};
`

**Comment by johlju** [comment]
You doing everything correctly so far. 😄 You can't set labels yourself, I labeled the issue now (forgot to do it before when I commented). I labeled it as "in progress".

I fixed the formatting. You should surround code blocks with three back ticks at the beginning and at the end (edit your comment and you see what I changed).

When you send in the PR I will review your code and comment on anything that needs to be fix, like style.
If you need any help before then, just let me know. 😄
