### ISSUE TITLE
xSQLServerPermission: PSScriptAnalyzer errors need to be fixed

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#727]
**Details of the scenario you tried and the problem that is occurring:**
The following PSScriptAnalyzer errors need to be fixed:
MSFT_xSQLServerPermission.psm1 (Line 293): Mandatory parameters must use the correct format [Parameter(Mandatory = $true)] for the mandatory attribute. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block
MSFT_xSQLServerPermission.psm1 (Line 298): Mandatory parameters must use the correct format [Parameter(Mandatory = $true)] for the mandatory attribute. See https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-format-for-parameter-block

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by ChrisLGardner** [comment]
This is being triggered by: 
```
[Parameter(Mandatory = $true, ParameterSetName = 'Permission')]
```

But as far as I can tell the PSSA rule is looking for Parameter to only contain 'Mandatory = $true'. This is also happening in #726 for the same reasons. I'm not sure there is an easy fix without changing the custom PSSA rule a bit to account for multiple entries in the parameter attribute.

**Comment by johlju** [comment]
Ah, let me look at this one and I will get back to you. :) We might need to change the common test.

**Comment by ChrisLGardner** [comment]
I think this can be closed now following the changes to DscResource.Tests rules. There is still an error about not using Write-Verbose in Get-TargetResource and Set-TargetResource which might need fixing but a few other resources in this module also mention that.

**Comment by johlju** [comment]
@ChrisLGardner The Write-Verbose PSSA warnings will probably be resolved as soon as the resource is localized which will replace helper function `New-VerboseMessage` to `Write-Verbose`. See xSQLServerSetup which is localized. That is why I didn't add that to the issue.

I will close this issue since this was false warnings generated by a bug in the common tests.
