### ISSUE TITLE
SQL 2016 Support

### ISSUE THREAD

**Issue by forensicsguy20012004** [PowerShell/xSQLServer#75]
Could someone pick this up and run with it?

**Comment by aultt** [comment]
I have the code locally just need some additional testing and then I will submit a PR.

**Comment by forensicsguy20012004** [comment]
Thank you Troy. I saw you tried to get your PR into the main...how did that go?

**Comment by aultt** [comment]
It needs to be reviewed and merged PR is submitted.

**Comment by forensicsguy20012004** [comment]
That is good news...like I said where I can help let me know. Always good work my friend..."top-notch."

**Comment by johlju** [comment]
This is implemented and merged into dev in pull request #77. This one can be closed.

**Comment by forensicsguy20012004** [comment]
Thank you.... closing
