### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership: Relative path to long for Azure Automation

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#769]
**Details of the scenario you tried and the problem that is occurring:**
xSQLServer resources can't compile in Azure Automation, I have narrowed it down to that resources can't compile because of too long file paths. This seem to have started in version 8.0.0.0.

To solve issue PowerShell/xSQLServer#716 the relative file path can't be longer than 120 characters.

Because of this we need to rename the resource MSFT_xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership. I suggest we rename the folder and files to MSFT_xSQLServerAGDatabaseMembership but leave the friendly name as 'xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership' in the schema.mof.

**Other suggestion how to solve this is welcomed.**

**The DSC configuration that is using the resource (as detailed as possible):**
See issue https://github.com/PowerShell/DscResources/issues/310

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Azure Automation

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
8.0.0.0

**Comment by johlju** [comment]
I labeled this "on hold" and await a possible resolution from Azure Automation Team (which can be a while).

**Comment by arcotek-ltd** [comment]
Well "Azure Automation Team" need to work faster. This is a problem.

**Comment by johlju** [comment]
@arcotek-ltd I feel you. I hope there is a better fix than we have to rework this module. Please see workarounds in issue https://github.com/PowerShell/xSQLServer/issues/716 in the meantime.

**Comment by johlju** [comment]
Closing this as per comment https://github.com/PowerShell/xSQLServer/issues/716#issuecomment-332581352

We should need to change the resource. Tracking this problem in issue #716.
