### ISSUE TITLE
xSQLServerAvailabilityGroupListener: Relative path to long for Azure Automation

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#771]
**Details of the scenario you tried and the problem that is occurring:**
xSQLServer resources can't compile in Azure Automation, I have narrowed it down to that resources can't compile because of too long file paths. This seem to have started in version 8.0.0.0.

To solve issue PowerShell/xSQLServer#716 the relative file path can't be longer than 120 characters.

We need to rename the example files.
    * 5-AddAvailabilityGroupListenerUsingDHCPWithDefaultServerSubnet.ps1

**The DSC configuration that is using the resource (as detailed as possible):**
See issue PowerShell/DscResources#310

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Azure Automation

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
8.0.0.0

**Comment by kwirkykat** [comment]
@johlju I forwarded this issue to someone on the Azure Automation team. Waiting for a response

**Comment by johlju** [comment]
Thanks @kwirkykat!

**Comment by kwirkykat** [comment]
@johlju Here's their response:
"We have a bug tracking the long path issue. It’s currently assigned to Sourabh’s team. (Sourabh is out till 9/3). As for workaround right now, customer can compile the configuration locally first and import the Mof directly into AA either from portal or PowerShell. The xSQL resource can still be imported into AA module asset so it should be available for pulling."

**Comment by johlju** [comment]
Thanks Katie, that is great news! Then I will hold off making any changes for this issue until we see if this bug is resolved.
I will (tomorrow) label the issues "on hold" for now.

**Comment by johlju** [comment]
I labeled this "on hold" and await a possible resolution from Azure Automation Team (which can be a while).

**Comment by johlju** [comment]
Please see workarounds for this issue in issue #716.

**Comment by johlju** [comment]
Closing this as per comment https://github.com/PowerShell/xSQLServer/issues/716#issuecomment-332581352

We should need to change the resource. Tracking this problem in issue #716.
