### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroup: Should use the correct major version SQLPS stubs for unit tests

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#784]
**Details of the scenario you tried and the problem that is occurring:**
When running unit test for xSQLServerAlwaysOnAvailabilityGroup it should use SQLPS stubs from SQL Server 2014 when major version is 12, and SQLPS stubs from SQL Server 2016 when major version is 13. This would actually test so parameters are not used that are not supported in older versions. 

https://github.com/PowerShell/xSQLServer/blob/c290c0074ad34a1a5649b25a475f850008e525f3/Tests/Unit/MSFT_xSQLServerAlwaysOnAvailabilityGroup.Tests.ps1#L86-L88

Currently parameters are added to the existing SQLPS stubs making such test impossible. See for example the stub for `New-SqlAvailabilityGroup` which contains parameters not in SQL Server 2014.

```
function New-SqlAvailabilityGroup {
    [CmdletBinding(DefaultParameterSetName='ByPath', ConfirmImpact='Medium')]
    param(
        [Parameter(Mandatory=$true)]
        [ValidateNotNullOrEmpty()]
        [object]
        ${AvailabilityReplica},
 
        [ValidateNotNullOrEmpty()]
        [string[]]
        ${Database},
 
        [object]
        ${AutomatedBackupPreference},
 
        [object]
        ${FailureConditionLevel},
 
        [int]
        ${HealthCheckTimeout},
 
        [Parameter(Mandatory=$true, Position=1)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${Name},
 
        [Parameter(ParameterSetName='ByObject', Mandatory=$true, Position=2, ValueFromPipeline=$true)]
        [ValidateNotNullOrEmpty()]
        [object]
        ${InputObject},
 
        [Parameter(ParameterSetName='ByPath', Position=2)]
        [ValidateNotNullOrEmpty()]
        [string]
        ${Path},
 
        [switch]
        ${Script},
 
        [Parameter()]
        [switch]
        $BasicAvailabilityGroup,
 
        [Parameter()]
        [switch]
        $DatabaseHealthTrigger,
 
        [Parameter()]
        [switch]
        $DtcSupportEnabled
   )
 
    throw '{0}: StubNotImplemented' -f $MyInvocation.MyCommand
}
```

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
SQLPS

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
Maybe add a test helper function that loads the removes SQLPS stubs module and reloads the correct  SQLPS stubs module. Making sure the correct one is in the session, so it can be reused in other tests.

**Comment by randomnote1** [comment]
@johlju, do any of the other modules switch the stubs that are used based on the version of SQL being used?

**Comment by johlju** [comment]
You mean the other resources in this module? No, but I think they should. 
Reason for that I added this issue toward this resource is that it will be harder to integration test AG resources, so the unit tests need to handle more. But all resources using SQLPS I think should run unit tests against each version of stub file. 

We should also have another stub file for SqlServer module as well. 
Then we could run tests for each SQLPS module and also for SQL 2016 and higher we can run unit tests against the SqlServer stubs. But think the SqlServer stub part was filled in another issue.

**Comment by johlju** [comment]
Yes. And I suggest you use the same path and filename as here. 

https://github.com/PowerShell/xFailOverCluster/blob/dev/Tests/TestHelpers/CommonTestHelper.psm1

The helper functions in this should be moved over here later as well (another issue), but then we have the file already present to add the helper functions to. :)

**Comment by randomnote1** [comment]
Suggested function name: Import-SQLModuleStub

**Comment by randomnote1** [comment]
Ok, working this into my updates for issue #468.

**Comment by johlju** [comment]
Awesome! Function name works for me.
