### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroup: Get-TargetResource returns a property Version that is missing in the schema.mof

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#787]
**Details of the scenario you tried and the problem that is occurring:**
The function `Get-TargetResource` returns a property `Version` that is missing in the schema.mof. It should be added as a read-only parameter.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by randomnote1** [comment]
All read-only properties that are missing from the schema.mof:

- EndpointUrl
- EndpointPort
- SQLServerNetName
- Version

I'll fix this as soon as the current PR for this resource is finished.

**Comment by randomnote1** [comment]
This is a duplicate of #476

**Comment by johlju** [comment]
label this one as in progress
