### ISSUE TITLE
New Examples for 1.6 Release Missing

### ISSUE THREAD

**Issue by cjhenry** [PowerShell/xSQLServer#79]
I have really enjoyed working with the xSQLServer resource and have been looking forward to the 1.6 release. I'm reworking my deployments to include multiple AAG groups per instance and noticed that no new examples were released with 1.6 or 1.7.

Does anyone have a working example for creating AAG they could share as a starting point?

Thanks!

**Comment by aultt** [comment]
DSCClusterSqlBuild.ps1 has examples of the AlwaysOn Availability Groups.  Have you looked at this example?

**Comment by cjhenry** [comment]
Thanks for the quick answer.
