### ISSUE TITLE
Error when source path contains blank space in xSqlServerSetup

### ISSUE THREAD

**Issue by BenAffleckIsBatman** [PowerShell/xSQLServer#8]
Function netuse in xPDT doesn't quote the path so the command net use failes if source path contains a blank space and comes back with the help text. 

Example:
xSQLServerSetup "SQLServerSetup"
        {
            InstanceName = "MSSQLSERVER"
            SetupCredential = $Credential
            SourcePath = "\\ServerName\Sources\SQL 2012 SP2"
        }

I would recommend using a string builder as it makes quoting much easier.

By the way, same should happen when password contains a $ or an other symbol that is expected to be interpreted by net use.

**Comment by Arturas-K** [comment]
Hi, @BenAffleckIsBatman 

In #20 I have updated how net use is called, now it uses array to pass all the arguments instead of concatenated string, this way PowerShell handles all the escaping correctly.
So this should not be a problem anymore.

**Comment by NarineM** [comment]
Addressed by #20 changes. Thanks to @Arturas-K for fixing this bug.
