### ISSUE TITLE
Improvements to xSQLServerEndPoint

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#80]
Looking at `AuthorizedUser` parameter in particular. 

It is not required according to the schema. But without it you might get a terminating error, it will send a empty string into  `if(!$SQL.Logins.Contains($AuthorizedUser))` (not sure about this one).

Also if one sets the `AuthorizedUser` parameter to a user, if that user is not already present as a login you will get a termination error. This should be pointed out in the description of the parameter.

It also doesn't take in account if someone uses different users for each instance. If you use several accounts, then all those accounts need Connect permission in all instances. I would suggest making the AuthorizedUser optional, or change so it can handle more than one account. _If we make it optional, then I have an new resource in a PR (`xSQLServerEndpointPermission`) which sets Connect permission for an user._

@aultt, as orginal author, do you have any feedback on this?

**Comment by aultt** [comment]
I would agree with your recommendation.  Once your PR is merged I think it makes sense to make the change.

**Comment by johlju** [comment]
Looking at removing parameter AuthorizedUser altogether now, see issue #466
