### ISSUE TITLE
xSqlServerMaxDop: Measure-Resource value of Property is not valid

### ISSUE THREAD

**Issue by twerthi** [PowerShell/xSQLServer#801]
**Details of the scenario you tried and the problem that is occurring:**
Test section of xMaxDop is failing with: Error Message: Cannot process argument because the value of argument "Property" is not valid. 

Researched module and found that Function Get-SqlDscDynamicMaxDop was causing the problem the two lines

    $numProcs = (Measure-Object -InputObject $cimInstanceProc -Property NumberOfLogicalProcessors -Sum).Sum
    $numCores = (Measure-Object -InputObject $cimInstanceProc -Property NumberOfCores -Sum).Sum

both fail with Measure-Object : The property "NumberOfLogicalProcessors" cannot be found in the input for any objects.

and 

Measure-Object : The property "NumberOfCores" cannot be found in the input for any objects.

Replaced with

    foreach($Processor in $cimInstanceProc)
    {
        $numProcs += $Processor.NumberOfLogicalProcessors
        $numCores += $Processor.NumberOfCores
    }

and MaxDop gets set correctly.

**The DSC configuration that is using the resource (as detailed as possible):**
        # set max degree of parallelism
        xSqlServerMaxDop $Node.NodeName
        {
            SQLInstanceName = $Node.InstanceName
            SQLServer = $Node.SqlServerName
            Ensure = "Present" 
            DynamicAlloc = $Node.MaxDopDynamicAlloc #($true)
            MaxDop = $Node.MaxDop #$(null)
			DependsOn = "[xSqlServerSetup]$($Node.NodeName)"
        }

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Server 2016
SQL Server 2016

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
SqlServer

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
8.1.0.0

**Comment by twerthi** [comment]
I forgot to mention that this has been working as of two weeks ago.  I don't see any changes to the repository, which would lead one to conclude the problem is on my end :)  However, I didn't make any changes either :)

**Comment by twerthi** [comment]
Submitted the fix.

**Comment by johlju** [comment]
Very strange that it did work, an now it doesn't. But I guess your changes as as good as the previous code, so doesn't hurt to change it if this is actually a problem with new build of some external thing.

**Comment by twerthi** [comment]
I 100% agree with you on the strangeness, it didn’t make any sense since it was working before.

Shawn Sesna
DevOps Engineer

**Comment by nabrond** [comment]
A little late to this, but I curious whether you saw any additional errors logged around the call to `Get-CimInstance` in this resource? After reading through this issue and looking at the existing module's code, it sounds as if that call failed to return a valid object?

**Comment by twerthi** [comment]
I did not.  The cimInstance object is a valid object, however it appeared to be a collection of processor objects.  The processor objects had the property the Measure-Object cmdlet was looking for, but the cimInstance did not.

Shawn Sesna
DevOps Engineer
