### ISSUE TITLE
xSQLServerMaxDop: Fails on machines reporting 2+ CPUs

### ISSUE THREAD

**Issue by GArionMSFT** [PowerShell/xSQLServer#805]
## Scenario
Use a multi-CPU (e.g.: dual socket server) machine (you can try this with an Azure DS15_v2 VM in Azure), create a DSC config that uses xSqlServer and use xSQLServerMaxDop in Auto mode:

        xSQLServerMaxDop Set_SQLServerMaxDop_ToAuto
        {
            Ensure = 'Present'
            DynamicAlloc = $true
            SQLInstanceName = $SQLInstanceName
        }

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Using SQL Server 2016 SP1 Enterprise, Windows Server 2016 Datacenter, **xSQLServer 7.1** (8+ has some issues when deploying it through an Azure Automation Account due to too long path names).

**Issue**
On machines reporting multiple NUMA nodes/processors - the code fails as it only expects one processor.

E.g.:
On a single CPU machine:
`$cimInstanceProc = Get-CimInstance -ClassName Win32_Processor`
Returns a single object that has a property called NumberOfLogicalProcessors

On a multiple CPU machine:
`$cimInstanceProc = Get-CimInstance -ClassName Win32_Processor`
Returns an array of two objects, thus, the following line:
`$numProcs = (Measure-Object -InputObject $cimInstanceProc -Property NumberOfLogicalProcessors -Sum).Sum`
Fails with:

> Measure-Object : The property "NumberOfLogicalProcessors" cannot be found in the input for any objects.
> At line:1 char:14
> + ... numProcs = (Measure-Object -InputObject $cimInstanceProc -Property Nu ...
> +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [Measure-Object], PSArgumentException
>     + FullyQualifiedErrorId : GenericMeasurePropertyNotFound,Microsoft.PowerShell.Commands.MeasureObjectCommand
As the array does not have any property called "NumberOfLogicalProcessors".

In situations where there are multiple CPUs:
`if($cimInstanceProc -is [array]) ...`
Either the first CPU (if the CPUs are identical) should be used in that instance (which one would assume is the most frequently encountered scenario) or a combination of data from all the CPUs.

**Comment by twerthi** [comment]
Similar to issue 801, I have submitted a fix, it's in progress.

**Comment by johlju** [comment]
@GArionMSFT When PR #802 is merged, then please test again (with the Dev version). I will add this issue to the PR so it will auto-close on merge. If the PR does not solve your problem, then feel free to reopen this issue.
