### ISSUE TITLE
xSqlServerSetup: Updating SqlSysAdminAccounts doesn't update sysadmins on server

### ISSUE THREAD

**Issue by TraGicCode** [PowerShell/xSQLServer#823]
When i update the SqlSysAdminAccounts After installation they don't get updated.  Is this expected behavior or a bug?

**Comment by johlju** [comment]
xSQLServerSetup does not change this. xSQLServerSetup resource only installs components, that is, it does only do things that setup.exe does. 
To change group membership please try xSQLServerRole.

**Comment by TraGicCode** [comment]
Thanks for clearing this up @johlju

**Comment by johlju** [comment]
Closing this seems it was solved for you. Reopen if it weren't.
