### ISSUE TITLE
xSQLServerRSConfig: Add examples for the new parameters in this resource

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#844]
**Details of the scenario you tried and the problem that is occurring:**
This resource should have examples updated to reflect the new parameters in this resource (that was merged with PR #638).

These should also be added to the integration tests.
 
**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by johlju** [comment]
@bozho Do you have any examples you can PR in?

**Comment by bozho** [comment]
Yeah, I can whip something up

**Comment by johlju** [comment]
Awesome. Thank you.

**Comment by bozho** [comment]
Would you like separate examples, or would one with all four new options do?

**Comment by johlju** [comment]
One with all four options will do. Just explain them in the comment-based help.
