### ISSUE TITLE
xSQLServerDatabase: Get-TargetResource tests aren't giving accurate results due to scoping.

### ISSUE THREAD

**Issue by ChrisLGardner** [PowerShell/xSQLServer#849]
**Details of the scenario you tried and the problem that is occurring:**

The tests for Get-TargetResource are providing inaccurate results as the second It block in each Context is effectively doing `$null | Should Be $null` due to the variables being scoped in a different It block.

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

Dev.

I'm working on some changes to this Resource anyway so I'll fix this as part of that (or I can separate it out to different set of changes). I'm not sure if this is done elsewhere so it might effect other resources too.

This is the code, I'll just move the $testParameters assignment and the $result = Get-TargetResource outside the It block so it's part of the Context above it.

```
It 'Should return the state as present' {
                    $testParameters = $mockDefaultParameters
                    $testParameters += @{
                        Name = 'AdventureWorks'
                    }

                    $result = Get-TargetResource @testParameters
                    $result.Ensure | Should Be 'Present'
                }

                It 'Should return the same values as passed as parameters' {
                    $result.SQLServer | Should Be $testParameters.SQLServer
                    $result.SQLInstanceName | Should Be $testParameters.SQLInstanceName
                    $result.Name | Should Be $testParameters.Name
                }
```

**Comment by johlju** [comment]
Thanks for finding this.

Instead of moving it outside the It-block, add another `$result = Get-TargetResource @testParameters` to the second It-block. That is how it is done in other resources, and should be done here as well.

You decide if you can do this change in the same PR as another change, or in a separate PR. Either works for me.

**Comment by johlju** [comment]
@ChrisLGardner I label this as in progress since you could resolve this.

**Comment by ChrisLGardner** [comment]
That's what I've done.

I'll include it in the PR for adding the collation. Just working out the last few (obvious) bugs now and I'll hopefully have it in for review some time this week.

**Comment by johlju** [comment]
Awesome! looking forward to it! 😄
