### ISSUE TITLE
xSQLServer: Migrate Pester Test Syntax from v3 -> v4

### ISSUE THREAD

**Issue by johlju** [PowerShell/xSQLServer#863]
**Details of the scenario you tried and the problem that is occurring:**
As of Pester v4 the syntax of the Should cmdlet has changed from Should Be to Should -Be.

There is a helpful script that can be used to easily perform the conversion:
https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3

This script should be used to correct the Pester syntax.

**The DSC configuration that is using the resource (as detailed as possible):**
n/a

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
n/a

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
n/a

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Dev

**Comment by mnewswanger** [comment]
I'll knock this one out today
