### ISSUE TITLE
xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership: Should Be Cluster Aware

### ISSUE THREAD

**Issue by randomnote1** [PowerShell/xSQLServer#869]
**Details of the scenario you tried and the problem that is occurring:**
When the xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership resource is applied to all of the nodes in a Failover Cluster Instance (FCI), the nodes will "fight" with each other while trying to manage the database memberships in the availability group.

**The DSC configuration that is using the resource (as detailed as possible):**
When the following configuration is applied to two or more nodes of the FCI:
```
xSQLServerAlwaysOnAvailabilityGroupDatabaseMembership 'TestAGDatabaseMemberships'
{
    AvailabilityGroupName = $Node.AvailabilityGroupName
    BackupPath            = '\\SQL1\AgInitialize'
    DatabaseName          = 'DB*', 'AdventureWorks'
    SQLInstanceName       = $Node.SQLInstanceName
    SQLServer             = $Node.NodeName
    Ensure                = 'Present'
    PsDscRunAsCredential  = $SysAdminAccount
}
```

**Version of the Operating System, SQL Server and PowerShell the DSC Target Node is running:**
Any

**What module (SqlServer or SQLPS) and which version of the module the DSC Target Node is running:**
Any

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Any

**Comment by randomnote1** [comment]
The resource should evaluate if the current node is actively hosting the SQL instance. If it is not hosting the instance, it should write a verbose message stating that it does not own the instance, and then silently exit.

**Comment by johlju** [comment]
If I understand correctly. This will force the user to always add the same configuration to each node that is part of the availability group? It will no longer be enough (might never worked though?) to add this configuration to one of the nodes and that node will connect to the current primary replica (if needed) to do the changes?

**Comment by randomnote1** [comment]
Your assumption is correct. I had anticipated and assumed in the case of an FCI the same configuration would be pushed to all of the nodes to ensure seemless operation in the event of a node failure.

Currently if the resource detects the desired state is false, all the nodes will attempt to add the database to the availability group. Only one of the nodes will be successful in getting the whole way through the process. The other nodes will fail. However, the next time the desired state is tested, it will return true on all nodes.

**Comment by johlju** [comment]
This will essentially be a breaking change, right? Configurations out there that is only have the configuration on one node will "break" when the instance is moved to a node not having the configuration. 
This need to be documented in the resource and showed in examples.

I'm working on making a first version of a [README.md](https://github.com/johlju/xSQLServer/tree/remove-examples/Examples) in the examples folder that could contain, or link to, more descriptive examples (issue #462). This is to remove the old examples that is outdated. But haven't yet gotten as far as I hoped. Hope I get further this weekend.

**Comment by randomnote1** [comment]
I don't know. The way I've been using it will not result in a breaking change, however the scenario you describe it could be.

I don't know that I would consider it a breaking change because the design of DSC is to configure the current node. There is no reasonable assumption that DSC can or will configure resources on other nodes. That's my  2 cents anyway.

**Comment by johlju** [comment]
To all: Please share your opinion on this. Would you consider this be a breaking change?
 
@randomnote1 You have a point that DSC should configure the target node. But since the resource has up till now configured the instance regardless of active node, this would make it a functional breaking change.
Can this be considered as "Fundamentally changing an existing functionality of a resource" as of the [Breaking Changes](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#breaking-changes) guidelines?

If this change would be considered as a breaking change, then we will have breaking changes, and changing version number, quite often in the future. Worst case we would end up with version 28 or something in the end. :smile: If we consider this a breaking change, maybe we need to consolidate the changes in some way (different branch?).
So I rather not consider this as a breaking change. But I'm divided between your view of this (which I agree on), and the breaking changes guidelines.

**Comment by randomnote1** [comment]
@johlju, if we approach it the way I did in Pull Request #890, this will not be a breaking change. I added a parameter called `ProcessOnlyOnActiveNode` that must be set to `$true` in order for the resource to not process when the instance is not living on the node.

**Comment by johlju** [comment]
@randomnote1 A much better approach! Thanks for think of that! 😄 Looking good after just browsing the PR quick.

**Comment by randomnote1** [comment]
To resolve this issue, a parameter called `ProcessOnlyOnActiveNode` should be created on the `Set-TargetResource` and `Test-TargetResource` functions.

The `Get-TargetResource` function will execute the helper function `Test-ActiveNode` to determine if the current node is actively hosting the SQL instance and return the result via the read-only property `IsActiveNode`.

The `Test-TargetResource` function will use the value of `ProcessOnlyOnActiveNode` and `IsActiveNode` to determine if it should continue. If `ProcessOnlyOnActiveNode` is `$true` and `IsActiveNode` is `$false`, `Test-TargetResource` will return `$true`.

I put together [this gist](https://gist.github.com/randomnote1/c7a9adf740290cee0ba8e454323e9a7d) as a guide to updating the resource.

Also, see the xSQLServerAlwaysOnAvailabilityGroup resource for a completed example.

**Comment by randomnote1** [comment]
Starting this one.
