### ISSUE TITLE
BREAKING CHANGE: Check for SQLPS & SQLServer modules required

### ISSUE THREAD

**Issue by kilasuit** [PowerShell/xSQLServer#91]
With the latest updates to SSMS the SQLPS module was renamed to SQLServer so with this in mind we should have a check in all the resources for the change of module name for this along the lines of

``` powershell
If (Get-Module SQLPS -ListAvailable) 
    {
        Write-Verbose "SQLPS Module Found"
        $module = Get-Module SQLPS -ListAvailable
    } 
    else 
    {
    Write-Verbose "SQLPS Module Not found - Using updated SQLServer module "
    $module = Get-Module SQLServer -ListAvailable
    }

Import-Module $module -WarningAction SilentlyContinue -ErrorAction Stop
```

Though this would need to be actioned in the same way across all of the resources where 

``` powershell
Import-Module -Name SQLPS -WarningAction SilentlyContinue -ErrorAction Stop
```

is currently in place

**Comment by johlju** [comment]
If I look at a server with SQL Server 2016 installed without SSMS there is only SQLPS module.
If you install latest SSMS (July) on a server with SQL Server 2016 you get both SQLPS and SQLServer modules.

So I think if we want to use SQLServer before SQLPS, then the check should be switched. Like below. Or am I missing something?

```
If (Get-Module SQLServer -ListAvailable) 
{
    Write-Verbose "Preferred SQLServer module found"
    $module = Get-Module SQLServer -ListAvailable
} 
else 
{
    Write-Verbose "SQLServer module not found, using older SQLPS module "
    $module = Get-Module SQLPS -ListAvailable
}
```

**Comment by kilasuit** [comment]
Indeed - I wrote it very quickly last night to make sure that it was recorded as an issue to be aware of

Even moreso if the SQLServer Module gets published to the PowerShell Gallery as it wont require SSMS to be installed on that machine as well.

**Comment by johlju** [comment]
If it gets published to the gallery (and updated more frequently than SQL Server/SSMS) then it would be nice to have the option in the setup resource to pull that from the galley and install it.

**Comment by johlju** [comment]
I think this issue also needs to make sure that tests are run using both SQLPS and SQLServer stub module. If SQLServe module will be the preferred module if it exists. All tests needs to be verified to be able to work with both.

**Comment by johlju** [comment]
We also need to add a control question for this in the GitHub ISSUE_TEMPLATE - if the user is using SQLPS och SQLServer module, and what version om the module.
