### ISSUE TITLE
Pester Tests Need to be implemented for all existing Modules

### ISSUE THREAD

**Issue by aultt** [PowerShell/xSQLServer#92]
We need additional people to help write Pester tests.  This is a requirement to take the resource out of experimental status.

**Comment by johlju** [comment]
Note: We are also discussing mocking in issue #90

**Comment by johlju** [comment]
I on task to fix tests for xSQLServerEndpointState, xSQLServerAvailabilityGroupListener and xSQLServerEndpointPermission.

**Comment by aultt** [comment]
xSQLServerPermission is also failing in the build.  Doesn't look like it was tested when you did the intial push

**Comment by johlju** [comment]
The test was actually tested successfully by AppVoyer. The PR did not fail the tests (it wouldn't been merged otherwise I belive). Strange that it fails when it's tested together with your new tests. Does all tests work together in your dev environment?

@mbreakey3 Can you see why the tests fail? The error message (the types) failling from the resource aren't anywhere close to what's used in the resource. So it feels strange.

**Comment by mbreakey3** [comment]
Yeah, so the build that shows up for xSqlServer is actually from Master, not Dev. John's merge did run successfully actually. We're still looking into other causes for why this might be happening.

**Comment by johlju** [comment]
I have a new test finished (one, of the three I set out to do, is done). I can send in a PR of that test I got if that helps to debug.

**Comment by mbreakey3** [comment]
Is it for one of the resources that already has a test file?

**Comment by johlju** [comment]
No, it's a new one, for the resource xSQLServerEndpointState

**Comment by johlju** [comment]
Correction. It will send in a new version of the existing test as well, because I did small changes in it.

**Comment by mbreakey3** [comment]
Okay, I think it would probably be best to just roll it into one PR once you finish the other tests, and we'll try to get this issue figured out in the mean time.

**Comment by johlju** [comment]
Will do. Fixing rest of the test.

**Comment by aultt** [comment]
Currently have xSQLAOGroupJoin test complete moving on the xSQLDatabaseRecoveryModel next then to xSQLServerAlwayONService and working the way down the list.

**Comment by johlju** [comment]
New test in PR #106 for xSqlServerLogin

**Comment by johlju** [comment]
Working on a test for xSQLServerDatabaseRole. Will PR this weekend.

**Comment by luigilink** [comment]
New test in PR #138 for MSFT_xSQLServerDatabaseOwner

**Comment by luigilink** [comment]
New test in PR #140 for MSFT_xSQLServerDatabasePermissions

**Comment by johlju** [comment]
@luigilink Great work!! 😄

**Comment by nabrond** [comment]
Tests for xSQLServerConfiguration are in PR #143

**Comment by luigilink** [comment]
@aultt could you add the status of test development:

- [ ] MSFT_xSQLAlias
- [ ] MSFT_xSQLAOGroupEnsure
- [ ] MSFT_xSQLAOGroupJoin
- [ ] MSFT_xSQLDatabaseRecoveryModel
- [ ] MSFT_xSQLServerAlwaysOnService
- [ ] MSFT_xSQLServerAvailabilityGroupListener
- [ ] MSFT_xSQLServerConfiguration
- [ ] MSFT_xSQLServerDatabase
- [ ] MSFT_xSQLServerDatabaseOwner
- [ ] MSFT_xSQLServerDatabasePermissions
- [ ] MSFT_xSQLServerDatabaseRole
- [ ] MSFT_xSQLServerEndpoint
- [ ] MSFT_xSQLServerEndpointPermission
- [ ] MSFT_xSQLServerEndpointState
- [ ] MSFT_xSQLServerFailoverClusterSetup
- [ ] MSFT_xSQLServerFirewall
- [ ] MSFT_xSQLServerLogin
- [ ] MSFT_xSQLServerMaxDop
- [ ] MSFT_xSQLServerMemory
- [ ] MSFT_xSQLServerNetwork
- [ ] MSFT_xSQLServerPermission
- [ ] MSFT_xSQLServerPowerPlan
- [ ] MSFT_xSQLServerReplication
- [ ] MSFT_xSQLServerRole
- [ ] MSFT_xSQLServerRSConfig
- [ ] MSFT_xSQLServerRSSecureConnectionLevel
- [ ] MSFT_xSQLServerScript
- [ ] MSFT_xSQLServerSetup
- [ ] MSFT_xWaitForAvailabilityGroup

**Comment by johlju** [comment]
I added those I have in PR.

MSFT_xSQLServerPowerPlan we can skip, it's being moved. So it will be removed from this module as soon it is merged in repo xComputerManagement.

**Comment by luigilink** [comment]
#213

**Comment by johlju** [comment]
I closing this issue, and instead I open a new issue for each resource.
