### ISSUE TITLE
MSFT_xSQLServerSetup/StartWin32Process fails to execute setup.exe

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xSQLServer#93]
When xSQLServerSetup starts to execute setup.exe (line 782) it just sits there and does nothing (see verbose below). The setup.exe file is never executed and therefore no SQL setup logs are created. I cannot see any issues in Event Logs either.

If I use PsDscRunAsCredential and replace line 782 from

`$Process = StartWin32Process -Path $Path -Arguments $Arguments`

to

`$Process = StartWin32Process -Path $Path -Arguments $Arguments -AsTask -Credential $SetupCredential`

then the setup.exe file is executed and SQL Server is installed perfectly. So maybe adding a property called InstallFromScheduledTask added to xSQLServerSetup would be beneficial?

**xSQLServer** = 1.7.0.0
**WMF** = v5.0.10586.117
**.NET** = 3.5.1
**.NET** = v4.6.1 (tried v4.6.2 as well)
**OS** = Windows 2012 R2
**SQL** = 2012 (tried 2014 as well)
**Windows Updates** = Latest up to 05/08/2016
**UAC** = Disabled

VERBOSE: [TESTSERVER02]: LCM:  [ Start  Resource ]  [[xSQLServerSetup]SQLServerSetup]
VERBOSE: [TESTSERVER02]: LCM:  [ Start  Test     ]  [[xSQLServerSetup]SQLServerSetup]
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'GetxPDTVariable'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'NetUse'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'ResolvePath'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'StartWin32Process'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'WaitForWin32ProcessEnd'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Path: \myfileserver\SQLServer2014\Source\setup.exe
VERBOSE: [TESTSERVER02]: LCM:  [ End    Test     ]  [[xSQLServerSetup]SQLServerSetup]  in 0.7340 seconds.
VERBOSE: [TESTSERVER02]: LCM:  [ Start  Set      ]  [[xSQLServerSetup]SQLServerSetup]
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'GetxPDTVariable'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'NetUse'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'ResolvePath'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'StartWin32Process'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'WaitForWin32ProcessEnd'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Path: \myfileserver\SQLServer2014\Source\setup.exe
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'GetxPDTVariable'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'NetUse'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'ResolvePath'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'StartWin32Process'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Importing function 'WaitForWin32ProcessEnd'.
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Path: \myfileserver\SQLServer2014\Source\setup.exe
VERBOSE: [TESTSERVER02]:                            [[xSQLServerSetup]SQLServerSetup] Arguments: /Quiet="True" /IAcceptSQLServerLicenseTerms="True" /Action="Install" /AGTSVCSTARTUPTYPE=Automatic /InstanceName="MSSQLSERVER" /Features="SQLENGINE,FULLTEXT,IS
" /InstallSharedDir="C:\Program Files\Microsoft SQL Server" /InstallSharedWOWDir="C:\Program Files (x86)\Microsoft SQL Server" /InstanceDir="C:\Program Files\Microsoft SQL Server" /InstallSQLDataDir="S:\Data" /SQLUserDBDir="S:\Data" /SQLUserDBLogDir="L:\Logs
" /SQLTempDBDir="T:\Temp" /SQLTempDBLogDir="T:\Temp" /SQLSysAdminAccounts="MySQLAdmin"

**Comment by johlju** [comment]
Does PR #123 resolves this issue?

**Comment by johlju** [comment]
@Zuldan Is this still an issue?

**Comment by johlju** [comment]
@Zuldan Forget that last question. Was thinking of something else. This is still an issue.
