### ISSUE TITLE
Configure Roles for multiple Databases

### ISSUE THREAD

**Issue by typozh** [PowerShell/xSQLServer#99]
Hi,

I'm trying to create multiple dbs and then configure roles for multiple users. But I always get an error message "A conflict was detected between resources" when creating the .mof files. 

Example configuration:
        xSqlServerDatabase Database1 {
            Database = "Database_001"
            SQLServer = "SP2016_EXP"
            Ensure = "Present"
            PsDscRunAsCredential = $InstallAccount
        }
        xSQLServerDatabaseRole Database1_Role1 {
            Name = "Domain\User1"
            Database = "Database_001"
            SQLServer = "SP2016_EXP"
            Role = "db_owner"
            PsDscRunAsCredential = $InstallAccount
            Ensure = "Present"
            DependsOn = "[xSqlServerDatabase]Database1"
        }
        xSqlServerDatabase Database2 {
            Database = "Database_002"
            SQLServer = "SP2016_EXP"
            Ensure = "Present"
            PsDscRunAsCredential = $InstallAccount
        }
        xSQLServerDatabaseRole Database2_Role1 {
            Name = "Domain\User1"
            Database = "Database_002"
            SQLServer = "SP2016_EXP"
            Role = "db_owner"
            PsDscRunAsCredential = $InstallAccount
            Ensure = "Present"
            DependsOn = "[xSqlServerDatabase]Database2"
        }

How can I get around this error message?

Thanks for help

**Comment by johlju** [comment]
No workaround as of yet. This is the same issue as #108
